export const BLOCKING_RULES = {
  CASE_SCOPE_REQUIRED:
    "OG-BLOCKING-CASE-SCOPE-REQUIRED",

  ORGANIZATION_SCOPE_PRESERVED:
    "OG-BLOCKING-ORGANIZATION-SCOPE-PRESERVED",

  PARTICIPANT_VISIBILITY_PRESERVED:
    "OG-BLOCKING-PARTICIPANT-VISIBILITY-PRESERVED",

  AUTHORITATIVE_CONTEXT_REQUIRED:
    "OG-BLOCKING-AUTHORITATIVE-CONTEXT-REQUIRED",

  WORKFLOW_STATE_REQUIRED:
    "OG-BLOCKING-WORKFLOW-STATE-REQUIRED",

  RELATIONSHIP_CONTEXT_REQUIRED:
    "OG-BLOCKING-RELATIONSHIP-CONTEXT-REQUIRED",

  SOURCE_REFERENCES_PRESERVED:
    "OG-BLOCKING-SOURCE-REFERENCES-PRESERVED",

  NO_INDEPENDENT_SOURCE_QUERY:
    "OG-BLOCKING-NO-INDEPENDENT-SOURCE-QUERY",

  NO_BLOCKER_INFERENCE:
    "OG-BLOCKING-NO-BLOCKER-INFERENCE",

  NO_RELATIONSHIP_INFERENCE:
    "OG-BLOCKING-NO-RELATIONSHIP-INFERENCE",

  NO_PROTECTED_DETAIL_DISCLOSURE:
    "OG-BLOCKING-NO-PROTECTED-DETAIL-DISCLOSURE",

  PARTICIPANT_VISIBLE_EXPLANATION_REQUIRED:
    "OG-BLOCKING-PARTICIPANT-VISIBLE-EXPLANATION-REQUIRED",

  DETERMINISTIC_PRIORITY_REQUIRED:
    "OG-BLOCKING-DETERMINISTIC-PRIORITY-REQUIRED",

  FIRST_SATISFIED_RULE_WINS:
    "OG-BLOCKING-FIRST-SATISFIED-RULE-WINS",

  EXPLICIT_AUTHORITATIVE_CONDITIONS_PRESERVED:
    "OG-BLOCKING-EXPLICIT-AUTHORITATIVE-CONDITIONS-PRESERVED",

  INFORMATION_REQUEST_RESPONSE_BLOCKS_PROGRESSION:
    "OG-BLOCKING-INFORMATION-REQUEST-RESPONSE-BLOCKS-PROGRESSION",

  REMEDIATION_REQUIRED_BLOCKS_PROGRESSION:
    "OG-BLOCKING-REMEDIATION-REQUIRED-BLOCKS-PROGRESSION",

  EVIDENCE_REQUIRED_BLOCKS_PROGRESSION:
    "OG-BLOCKING-EVIDENCE-REQUIRED-BLOCKS-PROGRESSION",

  NO_AUTHORIZED_BLOCKING_RULE_SATISFIED:
    "OG-BLOCKING-NO-AUTHORIZED-BLOCKING-RULE-SATISFIED",

  NO_AUTOMATIC_RESOLUTION:
    "OG-BLOCKING-NO-AUTOMATIC-RESOLUTION",

  NO_WORKFLOW_MUTATION:
    "OG-BLOCKING-NO-WORKFLOW-MUTATION",

  NO_GOVERNANCE_RECOMPUTATION:
    "OG-BLOCKING-NO-GOVERNANCE-RECOMPUTATION",

  NO_AUTHORITY_CREATION:
    "OG-BLOCKING-NO-AUTHORITY-CREATION",
} as const;

export type BlockingRuleId =
  (typeof BLOCKING_RULES)[
    keyof typeof BLOCKING_RULES
  ];