export const NEXT_ACTION_RULES = {
  CASE_SCOPE_REQUIRED:
    "OG-NEXT-ACTION-CASE-SCOPE-REQUIRED",

  ORGANIZATION_SCOPE_PRESERVED:
    "OG-NEXT-ACTION-ORGANIZATION-SCOPE-PRESERVED",

  PARTICIPANT_VISIBILITY_PRESERVED:
    "OG-NEXT-ACTION-PARTICIPANT-VISIBILITY-PRESERVED",

  AUTHORITATIVE_CONTEXT_REQUIRED:
    "OG-NEXT-ACTION-AUTHORITATIVE-CONTEXT-REQUIRED",

  SOURCE_REFERENCES_PRESERVED:
    "OG-NEXT-ACTION-SOURCE-REFERENCES-PRESERVED",

  NO_INDEPENDENT_SOURCE_QUERY:
    "OG-NEXT-ACTION-NO-INDEPENDENT-SOURCE-QUERY",

  NO_RELATIONSHIP_INFERENCE:
    "OG-NEXT-ACTION-NO-RELATIONSHIP-INFERENCE",

  NO_BLOCKER_INFERENCE:
    "OG-NEXT-ACTION-NO-BLOCKER-INFERENCE",

  NO_WAITING_INFERENCE:
    "OG-NEXT-ACTION-NO-WAITING-INFERENCE",

  SINGLE_ACTION_ONLY:
    "OG-NEXT-ACTION-SINGLE-ACTION-ONLY",

  FIRST_SATISFIED_RULE_WINS:
    "OG-NEXT-ACTION-FIRST-SATISFIED-RULE-WINS",

  DETERMINISTIC_PRIORITY_REQUIRED:
    "OG-NEXT-ACTION-DETERMINISTIC-PRIORITY-REQUIRED",

  INFORMATION_REQUEST_RESPONSE_REQUIRED:
    "OG-NEXT-ACTION-INFORMATION-REQUEST-RESPONSE-REQUIRED",

  REMEDIATION_SUBMISSION_REQUIRED:
    "OG-NEXT-ACTION-REMEDIATION-SUBMISSION-REQUIRED",

  EVIDENCE_SUBMISSION_REQUIRED:
    "OG-NEXT-ACTION-EVIDENCE-SUBMISSION-REQUIRED",

  APPROVED_STATUS_REVIEW:
    "OG-NEXT-ACTION-APPROVED-STATUS-REVIEW",

  AUTHORIZED_REVIEW_PENDING:
    "OG-NEXT-ACTION-AUTHORIZED-REVIEW-PENDING",

  RELATIONSHIP_CONTEXT_UNRESOLVED:
    "OG-NEXT-ACTION-RELATIONSHIP-CONTEXT-UNRESOLVED",

  NO_AUTHORIZED_RULE_SATISFIED:
    "OG-NEXT-ACTION-NO-AUTHORIZED-RULE-SATISFIED",

  NO_WORKFLOW_MUTATION:
    "OG-NEXT-ACTION-NO-WORKFLOW-MUTATION",

  NO_GOVERNANCE_RECOMPUTATION:
    "OG-NEXT-ACTION-NO-GOVERNANCE-RECOMPUTATION",
} as const;

export type NextActionRuleId =
  (typeof NEXT_ACTION_RULES)[
    keyof typeof NEXT_ACTION_RULES
  ];