export const WAITING_ON_RULES = {
  CASE_SCOPE_REQUIRED:
    "OG-WAITING-ON-CASE-SCOPE-REQUIRED",

  ORGANIZATION_SCOPE_PRESERVED:
    "OG-WAITING-ON-ORGANIZATION-SCOPE-PRESERVED",

  PARTICIPANT_VISIBILITY_PRESERVED:
    "OG-WAITING-ON-PARTICIPANT-VISIBILITY-PRESERVED",

  AUTHORITATIVE_CONTEXT_REQUIRED:
    "OG-WAITING-ON-AUTHORITATIVE-CONTEXT-REQUIRED",

  WORKFLOW_STATE_REQUIRED:
    "OG-WAITING-ON-WORKFLOW-STATE-REQUIRED",

  RELATIONSHIP_CONTEXT_REQUIRED:
    "OG-WAITING-ON-RELATIONSHIP-CONTEXT-REQUIRED",

  SOURCE_REFERENCES_PRESERVED:
    "OG-WAITING-ON-SOURCE-REFERENCES-PRESERVED",

  NO_INDEPENDENT_SOURCE_QUERY:
    "OG-WAITING-ON-NO-INDEPENDENT-SOURCE-QUERY",

  NO_WAITING_INFERENCE:
    "OG-WAITING-ON-NO-WAITING-INFERENCE",

  NO_OWNER_INFERENCE:
    "OG-WAITING-ON-NO-OWNER-INFERENCE",

  NO_RELATIONSHIP_INFERENCE:
    "OG-WAITING-ON-NO-RELATIONSHIP-INFERENCE",

  NO_PROTECTED_DETAIL_DISCLOSURE:
    "OG-WAITING-ON-NO-PROTECTED-DETAIL-DISCLOSURE",

  PARTICIPANT_VISIBLE_EXPLANATION_REQUIRED:
    "OG-WAITING-ON-PARTICIPANT-VISIBLE-EXPLANATION-REQUIRED",

  SINGLE_WAITING_PARTY_REQUIRED:
    "OG-WAITING-ON-SINGLE-WAITING-PARTY-REQUIRED",

  DETERMINISTIC_PRIORITY_REQUIRED:
    "OG-WAITING-ON-DETERMINISTIC-PRIORITY-REQUIRED",

  FIRST_SATISFIED_RULE_WINS:
    "OG-WAITING-ON-FIRST-SATISFIED-RULE-WINS",

  EXPLICIT_AUTHORITATIVE_CONDITIONS_PRESERVED:
    "OG-WAITING-ON-EXPLICIT-AUTHORITATIVE-CONDITIONS-PRESERVED",

  CERTIFIED_BLOCKING_PARTICIPANT_PRESERVED:
    "OG-WAITING-ON-CERTIFIED-BLOCKING-PARTICIPANT-PRESERVED",

  APPLICANT_INFORMATION_RESPONSE_REQUIRED:
    "OG-WAITING-ON-APPLICANT-INFORMATION-RESPONSE-REQUIRED",

  APPLICANT_REMEDIATION_REQUIRED:
    "OG-WAITING-ON-APPLICANT-REMEDIATION-REQUIRED",

  APPLICANT_EVIDENCE_REQUIRED:
    "OG-WAITING-ON-APPLICANT-EVIDENCE-REQUIRED",

  OPERATIONS_REVIEW_PENDING:
    "OG-WAITING-ON-OPERATIONS-REVIEW-PENDING",

  GOVERNANCE_REVIEW_PENDING:
    "OG-WAITING-ON-GOVERNANCE-REVIEW-PENDING",

  CERTIFICATION_AUTHORITY_PENDING:
    "OG-WAITING-ON-CERTIFICATION-AUTHORITY-PENDING",

  NO_AUTHORIZED_WAITING_RULE_SATISFIED:
    "OG-WAITING-ON-NO-AUTHORIZED-WAITING-RULE-SATISFIED",

  NO_AUTOMATIC_REASSIGNMENT:
    "OG-WAITING-ON-NO-AUTOMATIC-REASSIGNMENT",

  NO_WORKFLOW_MUTATION:
    "OG-WAITING-ON-NO-WORKFLOW-MUTATION",

  NO_GOVERNANCE_RECOMPUTATION:
    "OG-WAITING-ON-NO-GOVERNANCE-RECOMPUTATION",

  NO_AUTHORITY_CREATION:
    "OG-WAITING-ON-NO-AUTHORITY-CREATION",
} as const;

export type WaitingOnRuleId =
  (typeof WAITING_ON_RULES)[
    keyof typeof WAITING_ON_RULES
  ];