-- ============================================================
-- 00_CORE_SETUP.sql
--
-- Purpose:
--   Baseline GAFAIG Snowflake environment setup
--   - Create database + schemas
--   - Create warehouse
--   - Create core runtime roles
--   - Create optional service user (no password in SQL)
--   - Grant baseline usage/read-write privileges
--
-- Hardening rules:
--   - Do NOT store passwords or secrets in SQL files
--   - Set or rotate GAFAIG_APP_USER credentials manually in Snowflake
--   - Store secrets only in local/env deployment settings
--
-- Notes:
--   - PARTICIPANTS is owned by 12_TABLES_PARTICIPANTS.sql
--   - Public registry views are owned by 21_VIEWS_PUBLIC_REGISTRY.sql
--   - Approval procedures are owned by 25_PROCEDURES_APPROVAL.sql
--
-- Safe to re-run.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------
-- 1) Database + Schemas
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS GAFAIG_DB;

CREATE SCHEMA IF NOT EXISTS GAFAIG_DB.CORE;
CREATE SCHEMA IF NOT EXISTS GAFAIG_DB.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS GAFAIG_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS GAFAIG_DB.AI_REGISTRY;

-- ------------------------------------------------------------
-- 2) Warehouse
-- ------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS GAFAIG_WH
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- ------------------------------------------------------------
-- 3) Roles
-- ------------------------------------------------------------
CREATE ROLE IF NOT EXISTS GAFAIG_APP_ROLE;
CREATE ROLE IF NOT EXISTS GAFAIG_PUBLISHER;
CREATE ROLE IF NOT EXISTS GAFAIG_PUBLIC_READER;

-- ------------------------------------------------------------
-- 4) Baseline Access Grants
-- ------------------------------------------------------------

-- Database + warehouse usage
GRANT USAGE ON DATABASE GAFAIG_DB TO ROLE GAFAIG_APP_ROLE;
GRANT USAGE ON WAREHOUSE GAFAIG_WH TO ROLE GAFAIG_APP_ROLE;

GRANT USAGE ON DATABASE GAFAIG_DB TO ROLE GAFAIG_PUBLISHER;
GRANT USAGE ON WAREHOUSE GAFAIG_WH TO ROLE GAFAIG_PUBLISHER;

GRANT USAGE ON DATABASE GAFAIG_DB TO ROLE GAFAIG_PUBLIC_READER;

-- Schema usage
GRANT USAGE ON SCHEMA GAFAIG_DB.CORE        TO ROLE GAFAIG_APP_ROLE;
GRANT USAGE ON SCHEMA GAFAIG_DB.GOVERNANCE  TO ROLE GAFAIG_APP_ROLE;
GRANT USAGE ON SCHEMA GAFAIG_DB.AUDIT       TO ROLE GAFAIG_APP_ROLE;
GRANT USAGE ON SCHEMA GAFAIG_DB.AI_REGISTRY TO ROLE GAFAIG_APP_ROLE;

GRANT USAGE ON SCHEMA GAFAIG_DB.CORE        TO ROLE GAFAIG_PUBLISHER;
GRANT USAGE ON SCHEMA GAFAIG_DB.GOVERNANCE  TO ROLE GAFAIG_PUBLISHER;
GRANT USAGE ON SCHEMA GAFAIG_DB.AUDIT       TO ROLE GAFAIG_PUBLISHER;
GRANT USAGE ON SCHEMA GAFAIG_DB.AI_REGISTRY TO ROLE GAFAIG_PUBLISHER;

GRANT USAGE ON SCHEMA GAFAIG_DB.CORE        TO ROLE GAFAIG_PUBLIC_READER;

-- Existing objects: tables
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA GAFAIG_DB.GOVERNANCE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA GAFAIG_DB.AUDIT
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA GAFAIG_DB.AI_REGISTRY
TO ROLE GAFAIG_APP_ROLE;

-- Existing objects: views
GRANT SELECT
ON ALL VIEWS IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA GAFAIG_DB.GOVERNANCE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA GAFAIG_DB.AUDIT
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA GAFAIG_DB.AI_REGISTRY
TO ROLE GAFAIG_APP_ROLE;

-- Future objects: tables
GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA GAFAIG_DB.GOVERNANCE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA GAFAIG_DB.AUDIT
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA GAFAIG_DB.AI_REGISTRY
TO ROLE GAFAIG_APP_ROLE;

-- Future objects: views
GRANT SELECT
ON FUTURE VIEWS IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA GAFAIG_DB.GOVERNANCE
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA GAFAIG_DB.AUDIT
TO ROLE GAFAIG_APP_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA GAFAIG_DB.AI_REGISTRY
TO ROLE GAFAIG_APP_ROLE;

-- Publisher role: focused approval/publish access
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_PUBLISHER;

GRANT SELECT
ON ALL VIEWS IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_PUBLISHER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_PUBLISHER;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_PUBLISHER;

-- Public reader: read-only registry access
GRANT SELECT
ON ALL VIEWS IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_PUBLIC_READER;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA GAFAIG_DB.CORE
TO ROLE GAFAIG_PUBLIC_READER;

-- ------------------------------------------------------------
-- 5) Optional Service User (No Password Here)
-- ------------------------------------------------------------
CREATE USER IF NOT EXISTS GAFAIG_APP_USER
  DEFAULT_ROLE = GAFAIG_APP_ROLE
  DEFAULT_WAREHOUSE = GAFAIG_WH
  DEFAULT_NAMESPACE = GAFAIG_DB.CORE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE GAFAIG_APP_ROLE TO USER GAFAIG_APP_USER;

-- ------------------------------------------------------------
-- 6) Default Context for Subsequent Setup
-- ------------------------------------------------------------
USE WAREHOUSE GAFAIG_WH;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;

-- ============================================================
-- END
-- ============================================================