-- ============================================================
-- 14_TABLES_REGISTRY_AI_SYSTEMS.sql
--
-- Purpose:
--   Create / align CORE.REGISTRY_AI_SYSTEMS for:
--   - public registry publication
--   - explorer surfaces
--   - governance transparency disclosures
--
-- Notes:
--   - Safe to run multiple times
--   - Creates the table if missing
--   - Adds any missing columns if the table already exists
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE GAFAIG_WH;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;

-- ------------------------------------------------------------
-- 1) Create table if missing
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS (
  SYSTEM_ID STRING NOT NULL,
  REGISTRY_ID STRING NOT NULL,
  APPLICATION_ID STRING,
  CASE_ID STRING,

  SYSTEM_NAME STRING NOT NULL,
  SYSTEM_TYPE STRING,
  INTENDED_USE STRING,

  DEPLOYMENT_STATUS STRING,
  OVERSIGHT_LEVEL STRING,
  RISK_TIER STRING,

  DEVELOPER_ORGANIZATION STRING,
  TRAINING_DATA_CATEGORY STRING,
  OVERSIGHT_MODEL STRING,
  HUMAN_REVIEW_REQUIRED BOOLEAN,
  EVALUATION_PROTOCOL STRING,
  AUDIT_FREQUENCY STRING,

  PUBLIC_SUMMARY STRING,

  IS_PUBLIC BOOLEAN DEFAULT TRUE,
  DISPLAY_ORDER NUMBER DEFAULT 100,

  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  CONSTRAINT PK_REGISTRY_AI_SYSTEMS PRIMARY KEY (SYSTEM_ID)
);

-- ------------------------------------------------------------
-- 2) Align schema if table already existed in an older form
-- ------------------------------------------------------------
ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS SYSTEM_ID STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS REGISTRY_ID STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS APPLICATION_ID STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS CASE_ID STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS SYSTEM_NAME STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS SYSTEM_TYPE STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS INTENDED_USE STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS DEPLOYMENT_STATUS STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS OVERSIGHT_LEVEL STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS RISK_TIER STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS DEVELOPER_ORGANIZATION STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS TRAINING_DATA_CATEGORY STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS OVERSIGHT_MODEL STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS HUMAN_REVIEW_REQUIRED BOOLEAN;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS EVALUATION_PROTOCOL STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS AUDIT_FREQUENCY STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS PUBLIC_SUMMARY STRING;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS IS_PUBLIC BOOLEAN DEFAULT TRUE;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS DISPLAY_ORDER NUMBER DEFAULT 100;

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();

-- ============================================================
-- END
-- ============================================================