-- =========================================================
-- 99_RUN_CANONICAL_PIPELINE.sql
-- GAFAIG — NON-DESTRUCTIVE CANONICAL VALIDATION RUNNER
-- Last Updated: 2026-05-15
-- =========================================================

-- Canonical doctrine:
-- Snowflake is the source of truth.
-- API is pass-through only.
-- UI is display only.
-- Registry is append-only.
-- Certification is private.
-- Publication is explicit.
-- Verification uses proof.messageString only.
-- AI is advisory only.
-- Simulation is operational only.
-- Governance intelligence must NEVER override deterministic trust.
-- Public governance trust surfaces must remain publication-controlled.
-- This runner is non-destructive and validation-only.
-- Operational sequencing must remain deterministic.
-- Operational dependency discipline must remain explicit.
-- Publication enforcement must remain deterministic.
-- Verification enforcement must remain deterministic.
-- Operational simplicity must remain protected.
-- Enterprise scalability must evolve progressively.
-- Adaptive governance infrastructure must remain deterministic.

USE ROLE ACCOUNTADMIN;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 00A. OPERATIONAL GOVERNANCE CONTEXT VALIDATION
-- =========================================================

SELECT
  'OPERATIONAL_GOVERNANCE_CONTEXT_VALIDATION' AS VALIDATION_NAME,
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS VALIDATED_AT;

SELECT
  'CANONICAL_OPERATIONAL_LAYERING_ACTIVE' AS STATUS,
  'Layer 1 — Deterministic Schema Build' AS LAYER_1,
  'Layer 2 — Governance Workflow Infrastructure' AS LAYER_2,
  'Layer 3 — Publication + Verification Infrastructure' AS LAYER_3,
  'Layer 4 — Operational Validation Infrastructure' AS LAYER_4;

-- =========================================================
-- 01. CORE TABLE EXISTENCE CHECKS
-- =========================================================

SHOW TABLES LIKE 'VERIFICATION_CASES' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_FINDINGS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'CASE_SCORE_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'DECISIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_AI_SYSTEMS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 02. AI TABLE EXISTENCE CHECKS
-- =========================================================

SHOW TABLES LIKE 'AI_OBSERVATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RECOMMENDATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RISK_PATTERNS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_STANDARD_UPDATES' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RECOMMENDATION_REVIEWS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_REVIEW_ASSIGNMENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_COMMITTEE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_CONSENSUS_DECISIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_POLICY_REQUIREMENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_POLICY_MAPPINGS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_RISK_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_DRIFT_EVENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_REMEDIATION_TASKS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_WORKFLOW_ACTIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_EXECUTIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_APPROVALS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_STATE_TRANSITIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_CONTINUOUS_MONITORING' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RECERTIFICATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_SIMULATION_SCENARIOS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_SIMULATION_RUNS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_SIMULATION_EVENTS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 03. CORE VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_REGISTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_LATEST_APPROVED' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_AI_SYSTEMS_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_CASE_RENEWAL_STATUS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 04. AI INPUT VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_AI_CASE_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_FINDING_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_EVIDENCE_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_EVENT_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_DECISION_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REGISTRY_SNAPSHOT_INPUT' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 05. AI ANALYTICS / OPERATIONS / ORCHESTRATION VIEW CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_AI_OBSERVATION_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_RECOMMENDATION_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REVIEW_AUDIT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_FEEDBACK' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_FEEDBACK_ROLLUP' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_PENDING_REVIEW_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_HIGH_CONFIDENCE_RECOMMENDATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_HIGH_SEVERITY_OBSERVATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_ACTION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REVIEWER_THROUGHPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_WORKFLOW_METRICS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_CASE_GOVERNANCE_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_ESCALATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_REVIEW_ROUTING_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REVIEW_SLA_AGING' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REVIEWER_WORKLOAD' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_CATEGORY_ROUTING' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_ORCHESTRATION_METRICS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_AUDIT_HISTORY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_CONSENSUS_READINESS' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_CONSENSUS_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_ESCALATED_CONSENSUS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REVIEW_ASSIGNMENT_STATUS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_COMMITTEE_WORKLOAD' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_CONSENSUS_AUDIT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_LATEST_CONSENSUS' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_POLICY_MATCHES' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_POLICY_EXPOSURES' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_LATEST_GOVERNANCE_RISK' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_OPEN_GOVERNANCE_DRIFT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_RISK_ANALYTICS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_DRIFT_ESCALATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_REMEDIATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_OVERDUE_REMEDIATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_RECOVERY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_DEBT_BURNDOWN' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_WORKFLOW_ACTION_AUDIT' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_DRIFT_REMEDIATION_CANDIDATES' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_STALE_REVIEW_CANDIDATES' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_POLICY_REMEDIATION_CANDIDATES' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_RECOVERY_READINESS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_AUTOMATION_COMMAND_QUEUE' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_LATEST_GOVERNANCE_STATE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_EXECUTION_AUDIT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_APPROVAL_AUDIT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_CERTIFICATION_ELIGIBILITY_CANDIDATES' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_TRUST_DECAY_ANALYTICS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_RECERTIFICATION_CANDIDATES' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_SIMULATION_SCENARIO_LIBRARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_SIMULATION_RUN_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_SIMULATION_IMPACT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_SIMULATION_DASHBOARD_ROLLUP' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_AI_GOVERNANCE_TIMELINE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_TIMELINE_LATEST' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_TIMELINE_ROLLUP' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 06. PROCEDURE EXISTENCE CHECKS
-- =========================================================

SHOW PROCEDURES LIKE 'SP_CREATE_CASE_FROM_APPLICATION' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_SCORE_CASE_ENTERPRISE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_PUBLISH_CASE_TO_REGISTRY_V4' IN SCHEMA GAFAIG_DB.CORE;

SHOW PROCEDURES LIKE 'SP_AI_GENERATE_CASE_OBSERVATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_REVIEW_RECOMMENDATION_V2' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_PROMOTE_APPROVED_RECOMMENDATION' IN SCHEMA GAFAIG_DB.CORE;

SHOW PROCEDURES LIKE 'SP_AI_RECORD_OBSERVATION' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_RECORD_RECOMMENDATION' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_RECORD_RISK_PATTERN' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_RECORD_STANDARD_UPDATE' IN SCHEMA GAFAIG_DB.CORE;

SHOW PROCEDURES LIKE 'SP_AI_FINALIZE_CONSENSUS' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_DETECT_POLICY_GAPS' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_MATCH_POLICY' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_CALCULATE_GOVERNANCE_RISK' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_CREATE_REMEDIATION_TASK' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_PROCESS_SLA_ESCALATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_PROCESS_AUTOMATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_TRANSITION_GOVERNANCE_STATE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_EXECUTE_REMEDIATION' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_APPROVE_GOVERNANCE_RECOVERY' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_RUN_CONTINUOUS_MONITORING' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_PROCESS_MONITORING_AGING' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_CREATE_SIMULATION_SCENARIO' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_RUN_GOVERNANCE_SIMULATION' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 06A. OPERATIONAL DEPENDENCY VALIDATION
-- =========================================================
-- These checks validate deterministic operational dependency integrity.
-- They do not mutate infrastructure.
-- They do not alter governance state.

SELECT
  'DEPENDENCY_CORE_PUBLIC_VIEW_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC';

SELECT
  'DEPENDENCY_CORE_AI_INPUT_VIEW_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_AI_CASE_INPUT';

SELECT
  'DEPENDENCY_PUBLISH_PROCEDURE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'CORE'
  AND PROCEDURE_NAME = 'SP_PUBLISH_CASE_TO_REGISTRY_V4';

SELECT
  'DEPENDENCY_SCORE_PROCEDURE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'CORE'
  AND PROCEDURE_NAME = 'SP_SCORE_CASE_ENTERPRISE';

SELECT
  'DEPENDENCY_CASE_TABLE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'VERIFICATION_CASES';

SELECT
  'DEPENDENCY_REGISTRY_SNAPSHOT_TABLE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'REGISTRY_SNAPSHOTS';

-- =========================================================
-- 07. PUBLIC GOVERNANCE TRUST SURFACE CHECK
-- =========================================================

SELECT
  COUNT(*) AS PUBLIC_GOVERNANCE_TRUST_SURFACES
FROM CORE.V_REGISTRY_PUBLIC;

SELECT
  REGISTRY_ID,
  ENTITY_NAME,
  CERTIFICATION_STATUS,
  VISIBILITY_STATUS,
  PUBLISHED_AT
FROM CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

SELECT
  'PUBLIC_GOVERNANCE_TRUST_CONTRACT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS PUBLIC_GOVERNANCE_TRUST_SURFACES
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') = 'public'
  AND PUBLISHED_AT IS NOT NULL;

-- =========================================================
-- 08. PUBLICATION STATE CHECKS
-- =========================================================

SELECT
  COUNT(*) AS TOTAL_SNAPSHOTS,
  COUNT_IF(PUBLISHED = TRUE) AS PUBLISHED_TRUE,
  COUNT_IF(COALESCE(PUBLISHED, FALSE) = FALSE) AS PUBLISHED_FALSE
FROM CORE.REGISTRY_SNAPSHOTS;

-- =========================================================
-- 09. PUBLIC GOVERNANCE TRUST VISIBILITY ENFORCEMENT CHECKS
-- =========================================================

SELECT
  'PUBLIC_VIEW_UNPUBLISHED_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

SELECT
  'PUBLIC_VIEW_MISSING_PUBLISHED_AT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE PUBLISHED_AT IS NULL;

SELECT
  'PUBLISH_V4_CONTRACT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.REGISTRY_SNAPSHOTS
WHERE PUBLISHED = FALSE
  AND PUBLISHED_AT IS NOT NULL;

SELECT
  'PUBLIC_GOVERNANCE_TRUST_SURFACE_STATUS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'
   OR PUBLISHED_AT IS NULL;

-- =========================================================
-- 09A. VERIFICATION ENFORCEMENT VALIDATION
-- =========================================================
-- These checks validate verification enforcement doctrine integrity.
-- Verification MUST remain publication-bound.
-- Verification MUST remain deterministic.

SELECT
  'PUBLIC_VERIFICATION_SURFACE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC';

SELECT
  'PUBLIC_VERIFICATION_SURFACE_REQUIRED_FIELDS' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE REGISTRY_ID IS NULL
   OR VISIBILITY_STATUS IS NULL
   OR PUBLISHED_AT IS NULL;

SELECT
  'PUBLIC_VERIFICATION_SURFACE_VISIBILITY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

-- =========================================================
-- 10. PRIVATE SNAPSHOT SUPPORT CHECK
-- =========================================================

SELECT
  'PRIVATE_SNAPSHOT_EXISTENCE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS PRIVATE_SNAPSHOTS
FROM CORE.REGISTRY_SNAPSHOTS
WHERE COALESCE(PUBLISHED, FALSE) = FALSE;

-- =========================================================
-- 10A. OPERATIONAL ISOLATION VALIDATION
-- =========================================================
-- These checks validate operational governance isolation integrity.

SELECT
  'AI_COLUMN_LEAKAGE_IN_PUBLIC_SURFACES' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  AND COLUMN_NAME LIKE 'AI_%';

SELECT
  'PRIVATE_PUBLICATION_STATE_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

-- =========================================================
-- 11. AI TABLE STRUCTURE VALIDATION
-- =========================================================

DESC TABLE CORE.AI_OBSERVATIONS;
DESC TABLE CORE.AI_RECOMMENDATIONS;
DESC TABLE CORE.AI_RISK_PATTERNS;
DESC TABLE CORE.AI_STANDARD_UPDATES;
DESC TABLE CORE.AI_RECOMMENDATION_REVIEWS;
DESC TABLE CORE.AI_REVIEW_ASSIGNMENTS;
DESC TABLE CORE.AI_GOVERNANCE_COMMITTEE;
DESC TABLE CORE.AI_CONSENSUS_DECISIONS;
DESC TABLE CORE.AI_POLICY_REQUIREMENTS;
DESC TABLE CORE.AI_POLICY_MAPPINGS;
DESC TABLE CORE.AI_GOVERNANCE_RISK_SNAPSHOTS;
DESC TABLE CORE.AI_GOVERNANCE_DRIFT_EVENTS;
DESC TABLE CORE.AI_GOVERNANCE_REMEDIATION_TASKS;
DESC TABLE CORE.AI_GOVERNANCE_WORKFLOW_ACTIONS;
DESC TABLE CORE.AI_GOVERNANCE_EXECUTIONS;
DESC TABLE CORE.AI_GOVERNANCE_APPROVALS;
DESC TABLE CORE.AI_GOVERNANCE_STATE_TRANSITIONS;
DESC TABLE CORE.AI_CONTINUOUS_MONITORING;
DESC TABLE CORE.AI_RECERTIFICATION_QUEUE;
DESC TABLE CORE.AI_GOVERNANCE_SIMULATION_SCENARIOS;
DESC TABLE CORE.AI_GOVERNANCE_SIMULATION_RUNS;
DESC TABLE CORE.AI_GOVERNANCE_SIMULATION_EVENTS;

-- =========================================================
-- 12. AI INPUT VIEW SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_CASE_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_FINDING_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_EVIDENCE_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_EVENT_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_DECISION_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_REGISTRY_SNAPSHOT_INPUT LIMIT 5;

-- =========================================================
-- 13. AI OUTPUT SMOKE TESTS
-- =========================================================

SELECT *
FROM CORE.AI_OBSERVATIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_RECOMMENDATIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT
  REVIEW_ID,
  AI_RECOMMENDATION_ID,
  REVIEW_DECISION,
  REVIEWER_ID,
  REVIEWED_AT,
  CREATED_AT
FROM CORE.AI_RECOMMENDATION_REVIEWS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_STANDARD_UPDATES
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_RISK_PATTERNS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_CONSENSUS_DECISIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_POLICY_MAPPINGS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_RISK_SNAPSHOTS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_DRIFT_EVENTS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_REMEDIATION_TASKS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_WORKFLOW_ACTIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_EXECUTIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_APPROVALS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_CONTINUOUS_MONITORING
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_RECERTIFICATION_QUEUE
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
ORDER BY CREATED_AT DESC
LIMIT 5;

-- =========================================================
-- 14. AI ANALYTICS VIEW SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_OBSERVATION_SUMMARY LIMIT 5;
SELECT * FROM CORE.V_AI_RECOMMENDATION_SUMMARY LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEW_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_FEEDBACK LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_FEEDBACK_ROLLUP LIMIT 5;

-- =========================================================
-- 15. AI OPERATIONS DASHBOARD SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_PENDING_REVIEW_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_HIGH_CONFIDENCE_RECOMMENDATIONS LIMIT 5;
SELECT * FROM CORE.V_AI_HIGH_SEVERITY_OBSERVATION_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_ACTION_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEWER_THROUGHPUT LIMIT 5;
SELECT * FROM CORE.V_AI_WORKFLOW_METRICS;
SELECT * FROM CORE.V_AI_CASE_GOVERNANCE_SUMMARY LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_ESCALATION_QUEUE LIMIT 5;

-- =========================================================
-- 16. AI ORCHESTRATION SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_REVIEW_ROUTING_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEW_SLA_AGING LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEWER_WORKLOAD LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_CATEGORY_ROUTING LIMIT 5;
SELECT * FROM CORE.V_AI_ORCHESTRATION_METRICS;
SELECT * FROM CORE.V_AI_GOVERNANCE_AUDIT_HISTORY LIMIT 5;
SELECT * FROM CORE.V_AI_CONSENSUS_READINESS LIMIT 5;

-- =========================================================
-- 17. AI CONSENSUS GOVERNANCE SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_CONSENSUS_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_ESCALATED_CONSENSUS LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEW_ASSIGNMENT_STATUS LIMIT 5;
SELECT * FROM CORE.V_AI_COMMITTEE_WORKLOAD LIMIT 5;
SELECT * FROM CORE.V_AI_CONSENSUS_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_LATEST_CONSENSUS LIMIT 5;

-- =========================================================
-- 18. AI POLICY / RISK / DRIFT SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_POLICY_MATCHES LIMIT 5;
SELECT * FROM CORE.V_AI_POLICY_EXPOSURES LIMIT 5;
SELECT * FROM CORE.V_AI_LATEST_GOVERNANCE_RISK LIMIT 5;
SELECT * FROM CORE.V_AI_OPEN_GOVERNANCE_DRIFT LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_RISK_ANALYTICS LIMIT 5;
SELECT * FROM CORE.V_AI_DRIFT_ESCALATION_QUEUE LIMIT 5;

-- =========================================================
-- 19. AI REMEDIATION / AUTOMATION / EXECUTION SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_REMEDIATION_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_OVERDUE_REMEDIATIONS LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_RECOVERY LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_DEBT_BURNDOWN LIMIT 5;
SELECT * FROM CORE.V_AI_WORKFLOW_ACTION_AUDIT LIMIT 5;

SELECT * FROM CORE.V_AI_DRIFT_REMEDIATION_CANDIDATES LIMIT 5;
SELECT * FROM CORE.V_AI_STALE_REVIEW_CANDIDATES LIMIT 5;
SELECT * FROM CORE.V_AI_POLICY_REMEDIATION_CANDIDATES LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_RECOVERY_READINESS LIMIT 5;
SELECT * FROM CORE.V_AI_AUTOMATION_COMMAND_QUEUE LIMIT 5;

SELECT * FROM CORE.V_AI_LATEST_GOVERNANCE_STATE LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_EXECUTION_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_APPROVAL_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_CERTIFICATION_ELIGIBILITY_CANDIDATES LIMIT 5;

-- =========================================================
-- 20. AI CONTINUOUS MONITORING SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_TRUST_DECAY_ANALYTICS LIMIT 10;
SELECT * FROM CORE.V_AI_RECERTIFICATION_CANDIDATES LIMIT 10;

SELECT
  COUNT(*) AS ACTIVE_MONITORING_COUNT
FROM CORE.AI_CONTINUOUS_MONITORING
WHERE MONITORING_STATUS = 'ACTIVE';

SELECT
  CASE_ID,
  REGISTRY_ID,
  COUNT(*) AS ACTIVE_ROWS
FROM CORE.AI_CONTINUOUS_MONITORING
WHERE MONITORING_STATUS = 'ACTIVE'
GROUP BY CASE_ID, REGISTRY_ID
HAVING COUNT(*) > 1;

-- =========================================================
-- 20A. GOVERNANCE CONTINUITY VALIDATION
-- =========================================================
-- These checks validate deterministic governance continuity integrity.

SELECT
  'ACTIVE_MONITORING_DUPLICATE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    CASE_ID,
    REGISTRY_ID,
    COUNT(*) AS ACTIVE_ROWS
  FROM CORE.AI_CONTINUOUS_MONITORING
  WHERE MONITORING_STATUS = 'ACTIVE'
  GROUP BY CASE_ID, REGISTRY_ID
  HAVING COUNT(*) > 1
);

SELECT
  'RECERTIFICATION_QUEUE_NULL_CASE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RECERTIFICATION_QUEUE
WHERE CASE_ID IS NULL;

SELECT
  'RECERTIFICATION_QUEUE_NULL_REGISTRY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RECERTIFICATION_QUEUE
WHERE REGISTRY_ID IS NULL;

-- =========================================================
-- 21. AI SIMULATION / STRESS TESTING SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_SIMULATION_SCENARIO_LIBRARY LIMIT 10;

SELECT *
FROM CORE.V_AI_SIMULATION_RUN_SUMMARY
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT *
FROM CORE.V_AI_SIMULATION_IMPACT
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT *
FROM CORE.V_AI_SIMULATION_DASHBOARD_ROLLUP;

-- =========================================================
-- 22. AI GOVERNANCE TIMELINE SMOKE TESTS
-- =========================================================

SELECT *
FROM CORE.V_AI_GOVERNANCE_TIMELINE_LATEST
LIMIT 25;

SELECT *
FROM CORE.V_AI_GOVERNANCE_TIMELINE_ROLLUP
ORDER BY LATEST_EVENT_AT DESC
LIMIT 25;

SELECT *
FROM CORE.V_AI_GOVERNANCE_TIMELINE
WHERE CASE_ID = 'CASE-1001'
ORDER BY EVENT_AT DESC
LIMIT 25;

-- =========================================================
-- 23A. PUBLIC GOVERNANCE TRUST DOCTRINE CHECKS
-- =========================================================
-- These checks validate publication-safe public governance trust surfaces.
-- They do not mutate data and do not alter verification logic.

SELECT
  'PUBLIC_GOVERNANCE_TRUST_SURFACE_COUNT' AS VALIDATION_NAME,
  COUNT(*) AS PUBLIC_GOVERNANCE_TRUST_SURFACES
FROM CORE.V_REGISTRY_PUBLIC;

SELECT
  'PUBLIC_GOVERNANCE_TRUST_SURFACE_REQUIRED_FIELDS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE REGISTRY_ID IS NULL
   OR ENTITY_NAME IS NULL
   OR CERTIFICATION_STATUS IS NULL
   OR VISIBILITY_STATUS IS NULL
   OR PUBLISHED_AT IS NULL;

-- =========================================================
-- 23B. PUBLICATION ENFORCEMENT HARDENING CHECKS
-- =========================================================
-- These checks validate publication-bound governance trust integrity.

SELECT
  'PUBLICATION_BOUND_VISIBILITY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

SELECT
  'PUBLICATION_BOUND_PUBLISHED_AT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE PUBLISHED_AT IS NULL;

SELECT
  'APPEND_ONLY_PUBLIC_GOVERNANCE_SURFACE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE REGISTRY_ID IS NULL;

-- =========================================================
-- 23. AI / CERTIFICATION ISOLATION CHECK
-- =========================================================

SELECT
  'AI_LEAKAGE_IN_PUBLIC_VIEW_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  AND COLUMN_NAME LIKE 'AI_%';

-- =========================================================
-- 24. REVIEW STATUS VALIDATION
-- =========================================================

SELECT
  'AI_REVIEW_STATUS_INVALID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RECOMMENDATIONS
WHERE REVIEW_STATUS IS NOT NULL
  AND REVIEW_STATUS NOT IN (
    'PENDING',
    'APPROVED',
    'REJECTED',
    'DEFERRED',
    'NEEDS_MORE_EVIDENCE'
  );

-- =========================================================
-- 25. OBSERVATION DATA VALIDATION
-- =========================================================

SELECT
  'AI_OBSERVATIONS_WITHOUT_CASE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_OBSERVATIONS
WHERE CASE_ID IS NULL;

-- =========================================================
-- 26. GOVERNANCE FEEDBACK VALIDATION
-- =========================================================

SELECT
  'STANDARD_UPDATES_WITHOUT_APPROVED_RECOMMENDATION_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_STANDARD_UPDATES su
LEFT JOIN CORE.AI_RECOMMENDATIONS r
  ON TRIM(UPPER(su.RECOMMENDATION_ID)) = TRIM(UPPER(r.AI_RECOMMENDATION_ID))
WHERE su.RECOMMENDATION_ID IS NOT NULL
  AND COALESCE(UPPER(TRIM(r.REVIEW_STATUS)), '') <> 'APPROVED';

SELECT
  'RISK_PATTERNS_MISSING_DESCRIPTION_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RISK_PATTERNS
WHERE TRIM(COALESCE(PATTERN_DESCRIPTION, '')) = '';

SELECT
  'STANDARD_UPDATES_MISSING_PROPOSED_CHANGE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_STANDARD_UPDATES
WHERE TRIM(COALESCE(PROPOSED_CHANGE, '')) = '';

-- =========================================================
-- 27. OPERATIONS / ORCHESTRATION VALIDATION
-- =========================================================

SELECT
  'AI_CONSENSUS_INVALID_REVIEW_COUNT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_CONSENSUS_READINESS
WHERE REVIEW_COUNT < DISTINCT_REVIEWER_COUNT;

SELECT
  'AI_ORCHESTRATION_NEGATIVE_METRICS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_ORCHESTRATION_METRICS
WHERE PENDING_REVIEW_COUNT < 0
   OR APPROVED_REVIEW_COUNT < 0
   OR REJECTED_REVIEW_COUNT < 0
   OR SLA_BREACHED_COUNT < 0
   OR SLA_AT_RISK_COUNT < 0
   OR CRITICAL_REVIEW_COUNT < 0
   OR HIGH_PRIORITY_REVIEW_COUNT < 0;

SELECT
  'AI_WORKFLOW_NEGATIVE_METRICS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_WORKFLOW_METRICS
WHERE TOTAL_OBSERVATIONS < 0
   OR TOTAL_RECOMMENDATIONS < 0
   OR PENDING_RECOMMENDATIONS < 0
   OR APPROVED_RECOMMENDATIONS < 0
   OR REJECTED_RECOMMENDATIONS < 0
   OR TOTAL_STANDARD_UPDATES < 0
   OR TOTAL_RISK_PATTERNS < 0;

-- =========================================================
-- 28. ADVANCED AI GOVERNANCE VALIDATION
-- =========================================================

SELECT
  'AI_LATEST_CONSENSUS_DUPLICATE_RECOMMENDATION_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    AI_RECOMMENDATION_ID,
    COUNT(*) AS ROW_COUNT
  FROM CORE.V_AI_LATEST_CONSENSUS
  GROUP BY AI_RECOMMENDATION_ID
  HAVING COUNT(*) > 1
);

SELECT
  'AI_GOVERNANCE_RISK_NEGATIVE_SCORE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_LATEST_GOVERNANCE_RISK
WHERE GOVERNANCE_RISK_SCORE < 0
   OR GOVERNANCE_DEBT_COUNT < 0;

SELECT
  'AI_OPEN_DRIFT_RESOLVED_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_OPEN_GOVERNANCE_DRIFT
WHERE UPPER(COALESCE(RESOLUTION_STATUS, '')) <> 'OPEN';

SELECT
  'AI_REMEDIATION_QUEUE_RESOLVED_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_REMEDIATION_QUEUE
WHERE UPPER(COALESCE(TASK_STATUS, '')) = 'RESOLVED';

SELECT
  'AI_DUPLICATE_ACTIVE_MONITORING_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    CASE_ID,
    REGISTRY_ID,
    COUNT(*) AS ACTIVE_ROWS
  FROM CORE.AI_CONTINUOUS_MONITORING
  WHERE MONITORING_STATUS = 'ACTIVE'
  GROUP BY CASE_ID, REGISTRY_ID
  HAVING COUNT(*) > 1
);

SELECT
  'AI_SIMULATION_RECENT_DUPLICATE_RUN_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    CASE_ID,
    REGISTRY_ID,
    AI_SIMULATION_SCENARIO_ID,
    COUNT(*) AS RUN_COUNT
  FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
  WHERE CREATED_AT >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP())
  GROUP BY CASE_ID, REGISTRY_ID, AI_SIMULATION_SCENARIO_ID
  HAVING COUNT(*) > 1
);

SELECT
  'AI_TIMELINE_EMPTY_CASE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_GOVERNANCE_TIMELINE_ROLLUP
WHERE TOTAL_TIMELINE_EVENTS <= 0;

SELECT
  'AI_TIMELINE_NULL_EVENT_AT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_GOVERNANCE_TIMELINE
WHERE EVENT_AT IS NULL;

SELECT
  'AI_TIMELINE_NULL_CASE_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_GOVERNANCE_TIMELINE
WHERE CASE_ID IS NULL;

-- =========================================================
-- 29. CANONICAL PASS / FAIL SUMMARY
-- =========================================================

WITH CHECKS AS (

  SELECT
    'PUBLIC_VIEW_MISSING_PUBLISHED_AT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'PUBLIC_VIEW_UNPUBLISHED_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'

  UNION ALL

  SELECT
    'PUBLISH_V4_CONTRACT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.REGISTRY_SNAPSHOTS
  WHERE PUBLISHED = FALSE
    AND PUBLISHED_AT IS NOT NULL

  UNION ALL

  SELECT
    'AI_REVIEW_STATUS_INVALID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RECOMMENDATIONS
  WHERE REVIEW_STATUS IS NOT NULL
    AND REVIEW_STATUS NOT IN (
      'PENDING',
      'APPROVED',
      'REJECTED',
      'DEFERRED',
      'NEEDS_MORE_EVIDENCE'
    )

  UNION ALL

  SELECT
    'AI_OBSERVATIONS_WITHOUT_CASE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_OBSERVATIONS
  WHERE CASE_ID IS NULL

  UNION ALL

  SELECT
    'AI_LEAKAGE_IN_PUBLIC_VIEW' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
    AND COLUMN_NAME LIKE 'AI_%'

  UNION ALL

  SELECT
    'STANDARD_UPDATES_WITHOUT_APPROVED_RECOMMENDATION' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_STANDARD_UPDATES su
  LEFT JOIN CORE.AI_RECOMMENDATIONS r
    ON TRIM(UPPER(su.RECOMMENDATION_ID)) = TRIM(UPPER(r.AI_RECOMMENDATION_ID))
  WHERE su.RECOMMENDATION_ID IS NOT NULL
    AND COALESCE(UPPER(TRIM(r.REVIEW_STATUS)), '') <> 'APPROVED'

  UNION ALL

  SELECT
    'RISK_PATTERNS_MISSING_DESCRIPTION' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RISK_PATTERNS
  WHERE TRIM(COALESCE(PATTERN_DESCRIPTION, '')) = ''

  UNION ALL

  SELECT
    'STANDARD_UPDATES_MISSING_PROPOSED_CHANGE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_STANDARD_UPDATES
  WHERE TRIM(COALESCE(PROPOSED_CHANGE, '')) = ''

  UNION ALL

  SELECT
    'AI_CONSENSUS_INVALID_REVIEW_COUNT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_CONSENSUS_READINESS
  WHERE REVIEW_COUNT < DISTINCT_REVIEWER_COUNT

  UNION ALL

  SELECT
    'AI_ORCHESTRATION_NEGATIVE_METRICS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_ORCHESTRATION_METRICS
  WHERE PENDING_REVIEW_COUNT < 0
     OR APPROVED_REVIEW_COUNT < 0
     OR REJECTED_REVIEW_COUNT < 0
     OR SLA_BREACHED_COUNT < 0
     OR SLA_AT_RISK_COUNT < 0
     OR CRITICAL_REVIEW_COUNT < 0
     OR HIGH_PRIORITY_REVIEW_COUNT < 0

  UNION ALL

  SELECT
    'AI_WORKFLOW_NEGATIVE_METRICS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_WORKFLOW_METRICS
  WHERE TOTAL_OBSERVATIONS < 0
     OR TOTAL_RECOMMENDATIONS < 0
     OR PENDING_RECOMMENDATIONS < 0
     OR APPROVED_RECOMMENDATIONS < 0
     OR REJECTED_RECOMMENDATIONS < 0
     OR TOTAL_STANDARD_UPDATES < 0
     OR TOTAL_RISK_PATTERNS < 0

  UNION ALL

  SELECT
    'AI_LATEST_CONSENSUS_DUPLICATE_RECOMMENDATION' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      AI_RECOMMENDATION_ID,
      COUNT(*) AS ROW_COUNT
    FROM CORE.V_AI_LATEST_CONSENSUS
    GROUP BY AI_RECOMMENDATION_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'AI_GOVERNANCE_RISK_NEGATIVE_SCORE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_LATEST_GOVERNANCE_RISK
  WHERE GOVERNANCE_RISK_SCORE < 0
     OR GOVERNANCE_DEBT_COUNT < 0

  UNION ALL

  SELECT
    'AI_OPEN_DRIFT_RESOLVED_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_OPEN_GOVERNANCE_DRIFT
  WHERE UPPER(COALESCE(RESOLUTION_STATUS, '')) <> 'OPEN'

  UNION ALL

  SELECT
    'AI_REMEDIATION_QUEUE_RESOLVED_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_REMEDIATION_QUEUE
  WHERE UPPER(COALESCE(TASK_STATUS, '')) = 'RESOLVED'

  UNION ALL

  SELECT
    'AI_DUPLICATE_ACTIVE_MONITORING' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      CASE_ID,
      REGISTRY_ID,
      COUNT(*) AS ACTIVE_ROWS
    FROM CORE.AI_CONTINUOUS_MONITORING
    WHERE MONITORING_STATUS = 'ACTIVE'
    GROUP BY CASE_ID, REGISTRY_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'AI_SIMULATION_RECENT_DUPLICATE_RUN' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      CASE_ID,
      REGISTRY_ID,
      AI_SIMULATION_SCENARIO_ID,
      COUNT(*) AS RUN_COUNT
    FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
    WHERE CREATED_AT >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP())
    GROUP BY CASE_ID, REGISTRY_ID, AI_SIMULATION_SCENARIO_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'AI_TIMELINE_EMPTY_CASE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_GOVERNANCE_TIMELINE_ROLLUP
  WHERE TOTAL_TIMELINE_EVENTS <= 0

  UNION ALL

  SELECT
    'AI_TIMELINE_NULL_EVENT_AT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_GOVERNANCE_TIMELINE
  WHERE EVENT_AT IS NULL

  UNION ALL

  SELECT
    'AI_TIMELINE_NULL_CASE_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_GOVERNANCE_TIMELINE
  WHERE CASE_ID IS NULL

  UNION ALL

  SELECT
    'PUBLIC_GOVERNANCE_TRUST_SURFACE_STATUS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'
     OR PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'PUBLIC_GOVERNANCE_TRUST_SURFACE_REQUIRED_FIELDS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE REGISTRY_ID IS NULL
     OR ENTITY_NAME IS NULL
     OR CERTIFICATION_STATUS IS NULL
     OR VISIBILITY_STATUS IS NULL
     OR PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'DEPENDENCY_CORE_PUBLIC_VIEW_EXISTS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  HAVING COUNT(*) = 0

  UNION ALL

  SELECT
    'DEPENDENCY_PUBLISH_PROCEDURE_EXISTS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
  WHERE PROCEDURE_SCHEMA = 'CORE'
    AND PROCEDURE_NAME = 'SP_PUBLISH_CASE_TO_REGISTRY_V4'
  HAVING COUNT(*) = 0

  UNION ALL

  SELECT
    'PUBLIC_VERIFICATION_SURFACE_VISIBILITY_CHECK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'

  UNION ALL

  SELECT
    'AI_COLUMN_LEAKAGE_IN_PUBLIC_SURFACES' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
    AND COLUMN_NAME LIKE 'AI_%'

  UNION ALL

  SELECT
    'RECERTIFICATION_QUEUE_NULL_CASE_CHECK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RECERTIFICATION_QUEUE
  WHERE CASE_ID IS NULL

)

SELECT
  CHECK_NAME,
  BAD_ROWS,
  CASE
    WHEN BAD_ROWS = 0 THEN 'PASS'
    ELSE 'FAIL'
  END AS STATUS
FROM CHECKS;

-- =========================================================
-- 30. FINAL MARKER
-- =========================================================

SELECT
  'GAFAIG_CANONICAL_PIPELINE_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_PUBLIC_GOVERNANCE_TRUST_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_NARRATIVE_STABILIZATION_ALIGNMENT_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_OPERATIONAL_GOVERNANCE_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_PUBLICATION_ENFORCEMENT_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_VERIFICATION_ENFORCEMENT_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_OPERATIONAL_DEPENDENCY_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;
