-- 99_RUN_CANONICAL_PIPELINE.sql
-- GAFAIG non-destructive canonical smoke test runner
-- Last Updated: 2026-04-28
--
-- Purpose:
-- Validate that the current Snowflake environment contains the required
-- GAFAIG tables, views, procedures, and API-critical query paths.
--
-- This file is intentionally NON-DESTRUCTIVE.
-- Do not add DROP, TRUNCATE, DELETE, or CREATE OR REPLACE DATABASE here.

USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 01. CORE TABLE EXISTENCE CHECKS
-- =========================================================

SHOW TABLES LIKE 'APPLICATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_CASES' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_FINDINGS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_FINDING_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'CASE_SCORE_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'DECISIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 02. CORE TABLE SHAPE CHECKS
-- =========================================================

DESC TABLE GAFAIG_DB.CORE.APPLICATIONS;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_CASES;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_FINDINGS;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_EVIDENCE;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_FINDING_EVIDENCE;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_EVENTS;
DESC TABLE GAFAIG_DB.CORE.CASE_SCORE_SNAPSHOTS;
DESC TABLE GAFAIG_DB.CORE.DECISIONS;
DESC TABLE GAFAIG_DB.CORE.REGISTRY_SNAPSHOTS;

-- =========================================================
-- 03. CRITICAL VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_GOVERNANCE_SCORE_CASE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_LATEST_APPROVED' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_AI_SYSTEMS_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 04. CRITICAL VIEW COMPILE CHECKS
-- =========================================================

SELECT * FROM GAFAIG_DB.CORE.V_GOVERNANCE_SCORE_CASE LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_REGISTRY_LATEST_APPROVED LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC LIMIT 5;

-- =========================================================
-- 05. CRITICAL PROCEDURE EXISTENCE CHECKS
-- =========================================================

SHOW PROCEDURES LIKE 'SP_SCORE_CASE_ENTERPRISE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_PUBLISH_CASE_TO_REGISTRY_V3' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_UPDATE_FINDING' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_LINK_FINDING_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_UNLINK_FINDING_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 06. API-CRITICAL TABLE QUERY SMOKE TESTS
-- =========================================================

SELECT
  APPLICATION_ID,
  REQUEST_ID,
  STATUS,
  ORG_NAME,
  CREATED_AT
FROM GAFAIG_DB.CORE.APPLICATIONS
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  CASE_ID,
  APPLICATION_ID,
  STATUS,
  CREATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_CASES
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  FINDING_ID,
  CASE_ID,
  CONTROL_ID,
  CONTROL_TITLE,
  RESULT,
  SEVERITY,
  CREATED_AT,
  UPDATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_FINDINGS
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  EVIDENCE_ID,
  CASE_ID,
  EVIDENCE_TYPE,
  TITLE,
  SOURCE_URL,
  CREATED_AT,
  UPDATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_EVIDENCE
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  FINDING_ID,
  EVIDENCE_ID,
  CREATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_FINDING_EVIDENCE
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  EVENT_ID,
  CASE_ID,
  EVENT_TYPE,
  CREATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_EVENTS
ORDER BY CREATED_AT DESC
LIMIT 10;

-- =========================================================
-- 07. CURRENT FINDINGS + EVIDENCE LINK SMOKE TEST
-- =========================================================

SELECT
  F.FINDING_ID,
  F.CASE_ID,
  F.CONTROL_TITLE,
  F.RESULT,
  F.SEVERITY,
  FE.EVIDENCE_ID,
  FE.CREATED_AT AS LINKED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_FINDINGS F
LEFT JOIN GAFAIG_DB.CORE.VERIFICATION_FINDING_EVIDENCE FE
  ON F.FINDING_ID = FE.FINDING_ID
ORDER BY F.CREATED_AT DESC
LIMIT 25;

-- =========================================================
-- 08. REGISTRY QUERY SMOKE TESTS
-- =========================================================

SELECT
  REGISTRY_ID,
  CASE_ID,
  ENTITY_NAME,
  CERTIFICATION_STATUS,
  CERTIFIED_TIER,
  CERTIFIED_BAND,
  PUBLISHED_AT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

-- =========================================================
-- 09. SCORE QUERY SMOKE TEST
-- =========================================================

SELECT
  CASE_ID,
  FINAL_SCORE,
  CERTIFIED_TIER,
  CERTIFIED_BAND
FROM GAFAIG_DB.CORE.V_GOVERNANCE_SCORE_CASE
ORDER BY CASE_ID
LIMIT 10;

-- =========================================================
-- 10. DECISION QUERY SMOKE TEST
-- =========================================================

SELECT
  DECISION_ID,
  CASE_ID,
  APPLICATION_ID,
  DECISION_STATUS,
  CERTIFICATION_TIER,
  CERTIFICATION_BAND,
  VALID_FROM,
  VALID_TO,
  CREATED_AT
FROM GAFAIG_DB.CORE.DECISIONS
ORDER BY CREATED_AT DESC
LIMIT 10;

-- =========================================================
-- 11. REGISTRY SNAPSHOT QUERY SMOKE TEST
-- =========================================================

SELECT
  REGISTRY_SNAPSHOT_ID,
  REGISTRY_ID,
  CASE_ID,
  ENTITY_NAME,
  DECISION_STATUS,
  REGISTRY_STATUS,
  PUBLISHED_AT
FROM GAFAIG_DB.CORE.REGISTRY_SNAPSHOTS
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

-- =========================================================
-- 12. FINAL NON-DESTRUCTIVE VALIDATION MARKER
-- =========================================================

SELECT
  'GAFAIG_CANONICAL_SMOKE_TEST_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;