-- =========================================================
-- 99_RUN_CANONICAL_PIPELINE.sql
-- GAFAIG — NON-DESTRUCTIVE CANONICAL VALIDATION RUNNER
-- Last Updated: 2026-05-04
--
-- PURPOSE
--   Validate that the current Snowflake environment contains the required
--   GAFAIG tables, views, procedures, data contracts, lifecycle rules,
--   public registry contracts, cryptographic verification dependencies,
--   and API-critical query paths.
--
-- IMPORTANT
--   This file is intentionally NON-DESTRUCTIVE.
--
--   DO NOT add:
--     DROP
--     TRUNCATE
--     DELETE
--     INSERT
--     UPDATE
--     CREATE OR REPLACE DATABASE
--     CREATE OR REPLACE SCHEMA
--
--   This runner validates the current environment only.
-- =========================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 01. CORE TABLE EXISTENCE CHECKS
-- =========================================================

SHOW TABLES LIKE 'APPLICATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'PARTICIPANTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_CASES' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_FINDINGS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_FINDING_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'CASE_SCORE_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'DECISIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_AI_SYSTEMS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_ENTITIES' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 02. CORE TABLE SHAPE CHECKS
-- =========================================================

DESC TABLE GAFAIG_DB.CORE.APPLICATIONS;
DESC TABLE GAFAIG_DB.CORE.PARTICIPANTS;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_CASES;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_FINDINGS;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_EVIDENCE;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_FINDING_EVIDENCE;
DESC TABLE GAFAIG_DB.CORE.VERIFICATION_EVENTS;
DESC TABLE GAFAIG_DB.CORE.CASE_SCORE_SNAPSHOTS;
DESC TABLE GAFAIG_DB.CORE.DECISIONS;
DESC TABLE GAFAIG_DB.CORE.REGISTRY_SNAPSHOTS;
DESC TABLE GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS;
DESC TABLE GAFAIG_DB.CORE.REGISTRY_ENTITIES;

-- =========================================================
-- 03. CRITICAL VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_GOVERNANCE_SCORE_CASE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_CASE_RENEWAL_STATUS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_LATEST_APPROVED' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_AI_SYSTEMS_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_EXPLORER_STATS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 04. CRITICAL VIEW COMPILE CHECKS
-- =========================================================

SELECT * FROM GAFAIG_DB.CORE.V_GOVERNANCE_SCORE_CASE LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_CASE_RENEWAL_STATUS LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_REGISTRY_LATEST_APPROVED LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC LIMIT 5;
SELECT * FROM GAFAIG_DB.CORE.V_EXPLORER_STATS LIMIT 5;

-- =========================================================
-- 05. CRITICAL PROCEDURE EXISTENCE CHECKS
-- =========================================================

SHOW PROCEDURES LIKE 'SP_CREATE_CASE_FROM_APPLICATION' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_SCORE_CASE_ENTERPRISE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'APPROVE_CASE_V1' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'UNAPPROVE_CASE_V1' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_PUBLISH_CASE_TO_REGISTRY_V3' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_CREATE_FINDING' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_UPDATE_FINDING' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_CREATE_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_LINK_FINDING_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_UNLINK_FINDING_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 06. API-CRITICAL TABLE QUERY SMOKE TESTS
-- =========================================================

SELECT
  APPLICATION_ID,
  REQUEST_ID,
  STATUS,
  ORG_NAME,
  CREATED_AT
FROM GAFAIG_DB.CORE.APPLICATIONS
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  CASE_ID,
  APPLICATION_ID,
  STATUS,
  CREATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_CASES
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  FINDING_ID,
  CASE_ID,
  CONTROL_ID,
  CONTROL_TITLE,
  RESULT,
  SEVERITY,
  CREATED_AT,
  UPDATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_FINDINGS
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  EVIDENCE_ID,
  CASE_ID,
  EVIDENCE_TYPE,
  TITLE,
  SOURCE_URL,
  CREATED_AT,
  UPDATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_EVIDENCE
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  FINDING_ID,
  EVIDENCE_ID,
  CREATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_FINDING_EVIDENCE
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT
  EVENT_ID,
  CASE_ID,
  EVENT_TYPE,
  CREATED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_EVENTS
ORDER BY CREATED_AT DESC
LIMIT 10;

-- =========================================================
-- 07. CURRENT FINDINGS + EVIDENCE LINK SMOKE TEST
-- =========================================================

SELECT
  F.FINDING_ID,
  F.CASE_ID,
  F.CONTROL_TITLE,
  F.RESULT,
  F.SEVERITY,
  FE.EVIDENCE_ID,
  FE.CREATED_AT AS LINKED_AT
FROM GAFAIG_DB.CORE.VERIFICATION_FINDINGS F
LEFT JOIN GAFAIG_DB.CORE.VERIFICATION_FINDING_EVIDENCE FE
  ON TRIM(UPPER(F.FINDING_ID)) = TRIM(UPPER(FE.FINDING_ID))
ORDER BY F.CREATED_AT DESC
LIMIT 25;

-- =========================================================
-- 08. REGISTRY QUERY SMOKE TESTS
-- =========================================================

SELECT
  REGISTRY_ID,
  CASE_ID,
  APPLICATION_ID,
  ENTITY_NAME,
  ENTITY_TYPE,
  COUNTRY,
  CERTIFICATION_STATUS,
  CERTIFIED_AT,
  VALID_FROM,
  VALID_TO,
  RENEWAL_STATUS,
  LIFECYCLE_STATUS,
  VISIBILITY_STATUS,
  VERIFICATION_ELIGIBLE,
  BADGE_ELIGIBLE,
  PUBLISHED_AT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

-- =========================================================
-- 09. SCORE QUERY SMOKE TEST
-- Private scoring layer only.
-- Score/tier/band must originate here, not public views.
-- =========================================================

SELECT
  CASE_ID,
  MODEL_VERSION,
  FINAL_SCORE,
  SCORE,
  TIER,
  BAND,
  RENEWAL_STATUS,
  IS_CURRENTLY_VALID,
  SCORED_AT
FROM GAFAIG_DB.CORE.V_GOVERNANCE_SCORE_CASE
ORDER BY CASE_ID
LIMIT 10;

-- =========================================================
-- 10. DECISION QUERY SMOKE TEST
-- =========================================================

SELECT
  DECISION_ID,
  CASE_ID,
  APPLICATION_ID,
  SNAPSHOT_ID,
  DECISION_STATUS,
  CERTIFICATION_TIER,
  CERTIFICATION_BAND,
  VALID_FROM,
  VALID_TO,
  CREATED_AT
FROM GAFAIG_DB.CORE.DECISIONS
ORDER BY CREATED_AT DESC
LIMIT 10;

-- =========================================================
-- 11. REGISTRY SNAPSHOT QUERY SMOKE TEST
-- =========================================================

SELECT
  REGISTRY_SNAPSHOT_ID,
  REGISTRY_ID,
  CASE_ID,
  ENTITY_NAME,
  VERIFICATION_TYPE,
  MODEL_VERSION,
  RENEWAL_STATUS,
  APPROVED_AT,
  PUBLISHED_AT,
  CREATED_AT
FROM GAFAIG_DB.CORE.REGISTRY_SNAPSHOTS
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

-- =========================================================
-- 12. DECISION INTEGRITY CHECKS
-- =========================================================

SELECT
  'DECISION_CASE_ID_NULL_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.CORE.DECISIONS
WHERE CASE_ID IS NULL
   OR TRIM(CASE_ID) = '';

SELECT
  'APPROVED_DECISION_VALIDITY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.CORE.DECISIONS
WHERE UPPER(TRIM(COALESCE(DECISION_STATUS, ''))) = 'APPROVED'
  AND (VALID_FROM IS NULL OR VALID_TO IS NULL);

SELECT
  'APPROVED_DECISION_DURATION_SAMPLE' AS VALIDATION_NAME,
  DECISION_ID,
  CASE_ID,
  DECISION_STATUS,
  VALID_FROM,
  VALID_TO,
  DATEDIFF('day', VALID_FROM, VALID_TO) AS DURATION_DAYS,
  CREATED_AT
FROM GAFAIG_DB.CORE.DECISIONS
WHERE UPPER(TRIM(COALESCE(DECISION_STATUS, ''))) = 'APPROVED'
ORDER BY CREATED_AT DESC
LIMIT 25;

-- =========================================================
-- 13. DECISION OVERLAP CHECK
-- Expected: 0 rows
-- =========================================================

SELECT
  'DECISION_OVERLAP_CHECK' AS VALIDATION_NAME,
  D1.CASE_ID,
  D1.DECISION_ID AS DECISION_ID_1,
  D1.VALID_FROM AS VALID_FROM_1,
  D1.VALID_TO AS VALID_TO_1,
  D2.DECISION_ID AS DECISION_ID_2,
  D2.VALID_FROM AS VALID_FROM_2,
  D2.VALID_TO AS VALID_TO_2
FROM GAFAIG_DB.CORE.DECISIONS D1
JOIN GAFAIG_DB.CORE.DECISIONS D2
  ON TRIM(UPPER(D1.CASE_ID)) = TRIM(UPPER(D2.CASE_ID))
 AND D1.DECISION_ID < D2.DECISION_ID
WHERE D1.VALID_FROM < D2.VALID_TO
  AND D2.VALID_FROM < D1.VALID_TO
ORDER BY D1.CASE_ID;

-- =========================================================
-- 14. RENEWAL VIEW VALIDATION
-- =========================================================

SELECT
  CASE_ID,
  DECISION_STATUS,
  VALID_FROM,
  VALID_TO,
  DAYS_TO_EXPIRY,
  RENEWAL_STATUS,
  IS_CURRENTLY_VALID
FROM GAFAIG_DB.CORE.V_CASE_RENEWAL_STATUS
ORDER BY CASE_ID
LIMIT 25;

SELECT
  'ACTIVE_RENEWAL_DAYS_TO_EXPIRY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.CORE.V_CASE_RENEWAL_STATUS
WHERE IS_CURRENTLY_VALID = TRUE
  AND DAYS_TO_EXPIRY IS NULL;

-- =========================================================
-- 15. PUBLIC REGISTRY CONTRACT CHECKS
-- =========================================================

SELECT
  'PUBLIC_REGISTRY_REQUIRED_FIELD_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
WHERE REGISTRY_ID IS NULL
   OR TRIM(REGISTRY_ID) = ''
   OR CASE_ID IS NULL
   OR TRIM(CASE_ID) = ''
   OR CERTIFICATION_STATUS IS NULL
   OR VALID_FROM IS NULL
   OR VALID_TO IS NULL
   OR PUBLISHED_AT IS NULL;

SELECT
  'PUBLIC_REGISTRY_PUBLIC_UI_FIELD_SAMPLE' AS VALIDATION_NAME,
  REGISTRY_ID,
  ENTITY_NAME,
  ENTITY_TYPE,
  COUNTRY,
  CERTIFICATION_STATUS,
  CERTIFIED_AT,
  VALID_FROM,
  VALID_TO,
  LIFECYCLE_STATUS,
  RENEWAL_STATUS,
  VISIBILITY_STATUS,
  VERIFICATION_ELIGIBLE,
  BADGE_ELIGIBLE,
  PUBLISHED_AT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

SELECT
  'PUBLIC_REGISTRY_DUPLICATE_CASE_CHECK' AS VALIDATION_NAME,
  CASE_ID,
  COUNT(*) AS ROW_COUNT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
GROUP BY CASE_ID
HAVING COUNT(*) > 1
ORDER BY ROW_COUNT DESC;

SELECT
  'PUBLIC_REGISTRY_DUPLICATE_REGISTRY_ID_CHECK' AS VALIDATION_NAME,
  REGISTRY_ID,
  COUNT(*) AS ROW_COUNT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
GROUP BY REGISTRY_ID
HAVING COUNT(*) > 1
ORDER BY ROW_COUNT DESC;

-- =========================================================
-- 16. PUBLIC VIEW SCORE LEAKAGE CHECK
-- Expected: 0 rows
-- =========================================================

SELECT
  'PUBLIC_REGISTRY_SCORE_LEAKAGE_CHECK' AS VALIDATION_NAME,
  COLUMN_NAME
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  AND UPPER(COLUMN_NAME) IN (
    'SCORE',
    'FINAL_SCORE',
    'TOTAL_SCORE',
    'CERTIFIED_SCORE',
    'TIER',
    'BAND',
    'CERTIFIED_TIER',
    'CERTIFIED_BAND'
  );

-- =========================================================
-- 17. PUBLIC AI SYSTEMS VIEW VALIDATION
-- =========================================================

SELECT *
FROM GAFAIG_DB.CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
LIMIT 10;

SELECT
  'PUBLIC_AI_SYSTEMS_CASE_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
WHERE CASE_ID IS NULL
   OR TRIM(CASE_ID) = '';

SELECT
  'PUBLIC_AI_SYSTEMS_SCORE_LEAKAGE_CHECK' AS VALIDATION_NAME,
  COLUMN_NAME
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_AI_SYSTEMS_PUBLIC'
  AND UPPER(COLUMN_NAME) IN (
    'SCORE',
    'FINAL_SCORE',
    'TOTAL_SCORE',
    'CERTIFIED_SCORE',
    'TIER',
    'BAND',
    'CERTIFIED_TIER',
    'CERTIFIED_BAND'
  );

-- =========================================================
-- 18. EXPLORER VIEW VALIDATION
-- =========================================================

SELECT *
FROM GAFAIG_DB.CORE.V_EXPLORER_STATS
LIMIT 10;

-- =========================================================
-- 19. END-TO-END PUBLIC RECORD COUNTS
-- =========================================================

SELECT
  'PUBLIC_RECORD_COUNT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS PUBLIC_RECORD_COUNT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC;

SELECT
  'CERTIFIED_RECORD_COUNT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS CERTIFIED_RECORD_COUNT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
WHERE UPPER(TRIM(CERTIFICATION_STATUS)) = 'CERTIFIED';

SELECT
  'ACTIVE_CERTIFIED_RECORD_COUNT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS ACTIVE_CERTIFIED_RECORD_COUNT
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
WHERE UPPER(TRIM(CERTIFICATION_STATUS)) = 'CERTIFIED'
  AND LOWER(TRIM(COALESCE(LIFECYCLE_STATUS, ''))) = 'active';

-- =========================================================
-- 20. SAMPLE RECORD FOR API / UI / WIDGET TESTING
-- Use REGISTRY_ID for:
-- /api/verify/{REGISTRY_ID}
-- /registry/{REGISTRY_ID}
-- /verify/{REGISTRY_ID}
-- /widget-preview/{REGISTRY_ID}
-- =========================================================

SELECT
  REGISTRY_ID,
  CASE_ID,
  ENTITY_NAME,
  CERTIFICATION_STATUS,
  VALID_FROM,
  VALID_TO,
  RENEWAL_STATUS,
  LIFECYCLE_STATUS,
  VERIFICATION_ELIGIBLE,
  BADGE_ELIGIBLE
FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 5;

-- =========================================================
-- 21. CANONICAL PASS / FAIL SUMMARY
-- =========================================================

WITH CHECKS AS (
  SELECT
    'DECISIONS_NULL_CASE_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.CORE.DECISIONS
  WHERE CASE_ID IS NULL OR TRIM(CASE_ID) = ''

  UNION ALL

  SELECT
    'APPROVED_DECISIONS_MISSING_VALIDITY' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.CORE.DECISIONS
  WHERE UPPER(TRIM(COALESCE(DECISION_STATUS, ''))) = 'APPROVED'
    AND (VALID_FROM IS NULL OR VALID_TO IS NULL)

  UNION ALL

  SELECT
    'DECISION_OVERLAPS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.CORE.DECISIONS D1
  JOIN GAFAIG_DB.CORE.DECISIONS D2
    ON TRIM(UPPER(D1.CASE_ID)) = TRIM(UPPER(D2.CASE_ID))
   AND D1.DECISION_ID < D2.DECISION_ID
  WHERE D1.VALID_FROM < D2.VALID_TO
    AND D2.VALID_FROM < D1.VALID_TO

  UNION ALL

  SELECT
    'ACTIVE_RENEWAL_NULL_EXPIRY' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.CORE.V_CASE_RENEWAL_STATUS
  WHERE IS_CURRENTLY_VALID = TRUE
    AND DAYS_TO_EXPIRY IS NULL

  UNION ALL

  SELECT
    'PUBLIC_REGISTRY_REQUIRED_FIELDS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
  WHERE REGISTRY_ID IS NULL
     OR TRIM(REGISTRY_ID) = ''
     OR CASE_ID IS NULL
     OR TRIM(CASE_ID) = ''
     OR CERTIFICATION_STATUS IS NULL
     OR VALID_FROM IS NULL
     OR VALID_TO IS NULL
     OR PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'PUBLIC_REGISTRY_DUPLICATE_CASES' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT CASE_ID
    FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
    GROUP BY CASE_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'PUBLIC_REGISTRY_DUPLICATE_REGISTRY_IDS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT REGISTRY_ID
    FROM GAFAIG_DB.CORE.V_REGISTRY_PUBLIC
    GROUP BY REGISTRY_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'PUBLIC_REGISTRY_SCORE_LEAKAGE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
    AND UPPER(COLUMN_NAME) IN (
      'SCORE',
      'FINAL_SCORE',
      'TOTAL_SCORE',
      'CERTIFIED_SCORE',
      'TIER',
      'BAND',
      'CERTIFIED_TIER',
      'CERTIFIED_BAND'
    )

  UNION ALL

  SELECT
    'PUBLIC_AI_SYSTEMS_NULL_CASE_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
  WHERE CASE_ID IS NULL
     OR TRIM(CASE_ID) = ''

  UNION ALL

  SELECT
    'PUBLIC_AI_SYSTEMS_SCORE_LEAKAGE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_AI_SYSTEMS_PUBLIC'
    AND UPPER(COLUMN_NAME) IN (
      'SCORE',
      'FINAL_SCORE',
      'TOTAL_SCORE',
      'CERTIFIED_SCORE',
      'TIER',
      'BAND',
      'CERTIFIED_TIER',
      'CERTIFIED_BAND'
    )
)
SELECT
  CHECK_NAME,
  BAD_ROWS,
  CASE
    WHEN BAD_ROWS = 0 THEN 'PASS'
    ELSE 'FAIL'
  END AS STATUS
FROM CHECKS
ORDER BY CHECK_NAME;

-- =========================================================
-- 22. FINAL NON-DESTRUCTIVE VALIDATION MARKER
-- =========================================================

SELECT
  'GAFAIG_CANONICAL_PIPELINE_VALIDATION_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

-- =========================================================
-- END: 99_RUN_CANONICAL_PIPELINE.sql
-- =========================================================