-- =========================================================
-- 99A_RUN_CORE_VALIDATION.sql
-- GAFAIG — NON-DESTRUCTIVE CORE OPERATIONAL VALIDATION BATCH
-- Last Updated: 2026-05-15
-- =========================================================

-- Canonical doctrine:
-- Snowflake is the source of truth.
-- API is pass-through only.
-- UI is display only.
-- Registry is append-only.
-- Certification is private.
-- Publication is explicit.
-- Verification uses proof.messageString only.
-- AI is advisory only.
-- This batch is non-destructive and validation-only.
-- Operational dependency discipline must remain explicit.

USE ROLE ACCOUNTADMIN;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 00A. OPERATIONAL GOVERNANCE CONTEXT VALIDATION
-- =========================================================

SELECT
  'OPERATIONAL_GOVERNANCE_CONTEXT_VALIDATION' AS VALIDATION_NAME,
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS VALIDATED_AT;

SELECT
  'CANONICAL_OPERATIONAL_LAYERING_ACTIVE' AS STATUS,
  'Layer 1 — Deterministic Schema Build' AS LAYER_1,
  'Layer 2 — Governance Workflow Infrastructure' AS LAYER_2,
  'Layer 3 — Publication + Verification Infrastructure' AS LAYER_3,
  'Layer 4 — Operational Validation Infrastructure' AS LAYER_4;

-- =========================================================
-- 01. CORE TABLE EXISTENCE CHECKS
-- =========================================================

SHOW TABLES LIKE 'VERIFICATION_CASES' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_FINDINGS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVIDENCE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'VERIFICATION_EVENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'CASE_SCORE_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'DECISIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'REGISTRY_AI_SYSTEMS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 02. AI TABLE EXISTENCE CHECKS
-- =========================================================

SHOW TABLES LIKE 'AI_OBSERVATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RECOMMENDATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RISK_PATTERNS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_STANDARD_UPDATES' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RECOMMENDATION_REVIEWS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_REVIEW_ASSIGNMENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_COMMITTEE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_CONSENSUS_DECISIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_POLICY_REQUIREMENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_POLICY_MAPPINGS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_RISK_SNAPSHOTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_DRIFT_EVENTS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_REMEDIATION_TASKS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_WORKFLOW_ACTIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_EXECUTIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_APPROVALS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_STATE_TRANSITIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_CONTINUOUS_MONITORING' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_RECERTIFICATION_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_SIMULATION_SCENARIOS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_SIMULATION_RUNS' IN SCHEMA GAFAIG_DB.CORE;
SHOW TABLES LIKE 'AI_GOVERNANCE_SIMULATION_EVENTS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 03. CORE VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_REGISTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_LATEST_APPROVED' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_AI_SYSTEMS_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_CASE_RENEWAL_STATUS' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 04. AI INPUT VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_AI_CASE_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_FINDING_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_EVIDENCE_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_EVENT_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_DECISION_INPUT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REGISTRY_SNAPSHOT_INPUT' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 05. CORE AI OPERATIONS VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_AI_OBSERVATION_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_RECOMMENDATION_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_REVIEW_AUDIT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_FEEDBACK' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_GOVERNANCE_FEEDBACK_ROLLUP' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_PENDING_REVIEW_QUEUE' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_WORKFLOW_METRICS' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_CASE_GOVERNANCE_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 06. PROCEDURE EXISTENCE CHECKS
-- =========================================================

SHOW PROCEDURES LIKE 'SP_CREATE_CASE_FROM_APPLICATION' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_SCORE_CASE_ENTERPRISE' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_PUBLISH_CASE_TO_REGISTRY_V4' IN SCHEMA GAFAIG_DB.CORE;

SHOW PROCEDURES LIKE 'SP_AI_GENERATE_CASE_OBSERVATIONS' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_REVIEW_RECOMMENDATION_V2' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_PROMOTE_APPROVED_RECOMMENDATION' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 06A. OPERATIONAL DEPENDENCY VALIDATION
-- =========================================================
-- These checks validate deterministic operational dependency integrity.
-- They do not mutate infrastructure.
-- They do not alter governance state.

SELECT
  'DEPENDENCY_CORE_PUBLIC_VIEW_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC';

SELECT
  'DEPENDENCY_CORE_AI_INPUT_VIEW_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_AI_CASE_INPUT';

SELECT
  'DEPENDENCY_PUBLISH_PROCEDURE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'CORE'
  AND PROCEDURE_NAME = 'SP_PUBLISH_CASE_TO_REGISTRY_V4';

SELECT
  'DEPENDENCY_SCORE_PROCEDURE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'CORE'
  AND PROCEDURE_NAME = 'SP_SCORE_CASE_ENTERPRISE';

SELECT
  'DEPENDENCY_CASE_TABLE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'VERIFICATION_CASES';

SELECT
  'DEPENDENCY_REGISTRY_SNAPSHOT_TABLE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'REGISTRY_SNAPSHOTS';

-- =========================================================
-- 07. PUBLIC GOVERNANCE TRUST SURFACE CHECKS
-- =========================================================

SELECT
  COUNT(*) AS PUBLIC_GOVERNANCE_TRUST_SURFACES
FROM CORE.V_REGISTRY_PUBLIC;

SELECT
  REGISTRY_ID,
  ENTITY_NAME,
  CERTIFICATION_STATUS,
  VISIBILITY_STATUS,
  PUBLISHED_AT
FROM CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

SELECT
  'PUBLIC_GOVERNANCE_TRUST_CONTRACT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS PUBLIC_GOVERNANCE_TRUST_SURFACES
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') = 'public'
  AND PUBLISHED_AT IS NOT NULL;

-- =========================================================
-- 08. PUBLICATION STATE CHECKS
-- =========================================================

SELECT
  COUNT(*) AS TOTAL_SNAPSHOTS,
  COUNT_IF(PUBLISHED = TRUE) AS PUBLISHED_TRUE,
  COUNT_IF(COALESCE(PUBLISHED, FALSE) = FALSE) AS PUBLISHED_FALSE
FROM CORE.REGISTRY_SNAPSHOTS;

-- =========================================================
-- 09. PUBLIC GOVERNANCE TRUST VISIBILITY ENFORCEMENT CHECKS
-- =========================================================

SELECT
  'PUBLIC_VIEW_UNPUBLISHED_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

SELECT
  'PUBLIC_VIEW_MISSING_PUBLISHED_AT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE PUBLISHED_AT IS NULL;

SELECT
  'PUBLISH_V4_CONTRACT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.REGISTRY_SNAPSHOTS
WHERE PUBLISHED = FALSE
  AND PUBLISHED_AT IS NOT NULL;

SELECT
  'PUBLIC_GOVERNANCE_TRUST_SURFACE_STATUS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'
   OR PUBLISHED_AT IS NULL;

-- =========================================================
-- 09A. VERIFICATION ENFORCEMENT VALIDATION
-- =========================================================
-- These checks validate verification enforcement doctrine integrity.
-- Verification MUST remain publication-bound.
-- Verification MUST remain deterministic.

SELECT
  'PUBLIC_VERIFICATION_SURFACE_EXISTS' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC';

SELECT
  'PUBLIC_VERIFICATION_SURFACE_REQUIRED_FIELDS' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE REGISTRY_ID IS NULL
   OR VISIBILITY_STATUS IS NULL
   OR PUBLISHED_AT IS NULL;

SELECT
  'PUBLIC_VERIFICATION_SURFACE_VISIBILITY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

-- =========================================================
-- 10. PRIVATE SNAPSHOT SUPPORT CHECK
-- =========================================================

SELECT
  'PRIVATE_SNAPSHOT_EXISTENCE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS PRIVATE_SNAPSHOTS
FROM CORE.REGISTRY_SNAPSHOTS
WHERE COALESCE(PUBLISHED, FALSE) = FALSE;

-- =========================================================
-- 10A. OPERATIONAL ISOLATION VALIDATION
-- =========================================================
-- These checks validate operational governance isolation integrity.

SELECT
  'AI_COLUMN_LEAKAGE_IN_PUBLIC_SURFACES' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  AND COLUMN_NAME LIKE 'AI_%';

SELECT
  'PRIVATE_PUBLICATION_STATE_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public';

-- =========================================================
-- 11. BATCH A PASS / FAIL SUMMARY
-- =========================================================

WITH CHECKS AS (

  SELECT
    'DEPENDENCY_CORE_PUBLIC_VIEW_EXISTS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  HAVING COUNT(*) = 0

  UNION ALL

  SELECT
    'DEPENDENCY_CORE_AI_INPUT_VIEW_EXISTS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_AI_CASE_INPUT'
  HAVING COUNT(*) = 0

  UNION ALL

  SELECT
    'DEPENDENCY_PUBLISH_PROCEDURE_EXISTS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
  WHERE PROCEDURE_SCHEMA = 'CORE'
    AND PROCEDURE_NAME = 'SP_PUBLISH_CASE_TO_REGISTRY_V4'
  HAVING COUNT(*) = 0

  UNION ALL

  SELECT
    'DEPENDENCY_SCORE_PROCEDURE_EXISTS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.PROCEDURES
  WHERE PROCEDURE_SCHEMA = 'CORE'
    AND PROCEDURE_NAME = 'SP_SCORE_CASE_ENTERPRISE'
  HAVING COUNT(*) = 0

  UNION ALL

  SELECT
    'PUBLIC_VIEW_MISSING_PUBLISHED_AT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'PUBLIC_VIEW_UNPUBLISHED_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'

  UNION ALL

  SELECT
    'PUBLISH_V4_CONTRACT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.REGISTRY_SNAPSHOTS
  WHERE PUBLISHED = FALSE
    AND PUBLISHED_AT IS NOT NULL

  UNION ALL

  SELECT
    'PUBLIC_VERIFICATION_SURFACE_REQUIRED_FIELDS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE REGISTRY_ID IS NULL
     OR VISIBILITY_STATUS IS NULL
     OR PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'AI_COLUMN_LEAKAGE_IN_PUBLIC_SURFACES' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
    AND COLUMN_NAME LIKE 'AI_%'

  UNION ALL

  SELECT
    'PRIVATE_PUBLICATION_STATE_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'

)

SELECT
  CHECK_NAME,
  BAD_ROWS,
  CASE
    WHEN BAD_ROWS = 0 THEN 'PASS'
    ELSE 'FAIL'
  END AS STATUS
FROM CHECKS;

-- =========================================================
-- 12. FINAL MARKERS
-- =========================================================

SELECT
  'GAFAIG_CORE_VALIDATION_BATCH_A_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_OPERATIONAL_DEPENDENCY_VALIDATION_BATCH_A_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_PUBLICATION_ENFORCEMENT_VALIDATION_BATCH_A_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_VERIFICATION_ENFORCEMENT_VALIDATION_BATCH_A_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;