-- =========================================================
-- 99B_RUN_GOVERNANCE_CONTINUITY_VALIDATION.sql
-- GAFAIG — NON-DESTRUCTIVE GOVERNANCE CONTINUITY VALIDATION BATCH
-- Last Updated: 2026-05-16
-- =========================================================

-- Canonical doctrine:
-- Snowflake is the source of truth.
-- API is pass-through only.
-- UI is display only.
-- Registry is append-only.
-- Certification is private.
-- Publication is explicit.
-- Verification uses proof.messageString only.
-- AI is advisory only.
-- Simulation is operational only.
-- Governance intelligence must NEVER override deterministic trust.
-- This batch is non-destructive and validation-only.
-- Governance continuity validation must remain deterministic.
-- Operational validation infrastructure must never mutate governance state.

USE ROLE ACCOUNTADMIN;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 00A. GOVERNANCE CONTINUITY CONTEXT VALIDATION
-- =========================================================

SELECT
  'GOVERNANCE_CONTINUITY_VALIDATION_BATCH_B_ACTIVE' AS STATUS,
  'Layer 2 — Governance Workflow Infrastructure' AS PRIMARY_LAYER,
  'Layer 4 — Operational Validation Infrastructure' AS VALIDATION_LAYER,
  CURRENT_TIMESTAMP() AS VALIDATED_AT;

-- =========================================================
-- 01. AI TABLE STRUCTURE VALIDATION
-- =========================================================

DESC TABLE CORE.AI_OBSERVATIONS;
DESC TABLE CORE.AI_RECOMMENDATIONS;
DESC TABLE CORE.AI_RISK_PATTERNS;
DESC TABLE CORE.AI_STANDARD_UPDATES;
DESC TABLE CORE.AI_RECOMMENDATION_REVIEWS;
DESC TABLE CORE.AI_REVIEW_ASSIGNMENTS;
DESC TABLE CORE.AI_GOVERNANCE_COMMITTEE;
DESC TABLE CORE.AI_CONSENSUS_DECISIONS;
DESC TABLE CORE.AI_POLICY_REQUIREMENTS;
DESC TABLE CORE.AI_POLICY_MAPPINGS;
DESC TABLE CORE.AI_GOVERNANCE_RISK_SNAPSHOTS;
DESC TABLE CORE.AI_GOVERNANCE_DRIFT_EVENTS;
DESC TABLE CORE.AI_GOVERNANCE_REMEDIATION_TASKS;
DESC TABLE CORE.AI_GOVERNANCE_WORKFLOW_ACTIONS;
DESC TABLE CORE.AI_GOVERNANCE_EXECUTIONS;
DESC TABLE CORE.AI_GOVERNANCE_APPROVALS;
DESC TABLE CORE.AI_GOVERNANCE_STATE_TRANSITIONS;
DESC TABLE CORE.AI_CONTINUOUS_MONITORING;
DESC TABLE CORE.AI_RECERTIFICATION_QUEUE;

-- =========================================================
-- 02. AI INPUT VIEW SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_CASE_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_FINDING_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_EVIDENCE_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_EVENT_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_DECISION_INPUT LIMIT 5;
SELECT * FROM CORE.V_AI_REGISTRY_SNAPSHOT_INPUT LIMIT 5;

-- =========================================================
-- 03. AI OUTPUT SMOKE TESTS
-- =========================================================

SELECT *
FROM CORE.AI_OBSERVATIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_RECOMMENDATIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT
  REVIEW_ID,
  AI_RECOMMENDATION_ID,
  REVIEW_DECISION,
  REVIEWER_ID,
  REVIEWED_AT,
  CREATED_AT
FROM CORE.AI_RECOMMENDATION_REVIEWS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_STANDARD_UPDATES
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_RISK_PATTERNS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_CONSENSUS_DECISIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_POLICY_MAPPINGS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_RISK_SNAPSHOTS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_DRIFT_EVENTS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_REMEDIATION_TASKS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_WORKFLOW_ACTIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_EXECUTIONS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_GOVERNANCE_APPROVALS
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_CONTINUOUS_MONITORING
ORDER BY CREATED_AT DESC
LIMIT 5;

SELECT *
FROM CORE.AI_RECERTIFICATION_QUEUE
ORDER BY CREATED_AT DESC
LIMIT 5;

-- =========================================================
-- 04. AI ANALYTICS VIEW SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_OBSERVATION_SUMMARY LIMIT 5;
SELECT * FROM CORE.V_AI_RECOMMENDATION_SUMMARY LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEW_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_FEEDBACK LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_FEEDBACK_ROLLUP LIMIT 5;

-- =========================================================
-- 05. AI OPERATIONS DASHBOARD SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_PENDING_REVIEW_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_HIGH_CONFIDENCE_RECOMMENDATIONS LIMIT 5;
SELECT * FROM CORE.V_AI_HIGH_SEVERITY_OBSERVATION_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_ACTION_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEWER_THROUGHPUT LIMIT 5;
SELECT * FROM CORE.V_AI_WORKFLOW_METRICS;
SELECT * FROM CORE.V_AI_CASE_GOVERNANCE_SUMMARY LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_ESCALATION_QUEUE LIMIT 5;

-- =========================================================
-- 06. AI ORCHESTRATION SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_REVIEW_ROUTING_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEW_SLA_AGING LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEWER_WORKLOAD LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_CATEGORY_ROUTING LIMIT 5;
SELECT * FROM CORE.V_AI_ORCHESTRATION_METRICS;
SELECT * FROM CORE.V_AI_GOVERNANCE_AUDIT_HISTORY LIMIT 5;
SELECT * FROM CORE.V_AI_CONSENSUS_READINESS LIMIT 5;

-- =========================================================
-- 07. AI CONSENSUS GOVERNANCE SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_CONSENSUS_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_ESCALATED_CONSENSUS LIMIT 5;
SELECT * FROM CORE.V_AI_REVIEW_ASSIGNMENT_STATUS LIMIT 5;
SELECT * FROM CORE.V_AI_COMMITTEE_WORKLOAD LIMIT 5;
SELECT * FROM CORE.V_AI_CONSENSUS_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_LATEST_CONSENSUS LIMIT 5;

-- =========================================================
-- 08. AI POLICY / RISK / DRIFT SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_POLICY_MATCHES LIMIT 5;
SELECT * FROM CORE.V_AI_POLICY_EXPOSURES LIMIT 5;
SELECT * FROM CORE.V_AI_LATEST_GOVERNANCE_RISK LIMIT 5;
SELECT * FROM CORE.V_AI_OPEN_GOVERNANCE_DRIFT LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_RISK_ANALYTICS LIMIT 5;
SELECT * FROM CORE.V_AI_DRIFT_ESCALATION_QUEUE LIMIT 5;

-- =========================================================
-- 09. AI REMEDIATION / AUTOMATION / EXECUTION SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_REMEDIATION_QUEUE LIMIT 5;
SELECT * FROM CORE.V_AI_OVERDUE_REMEDIATIONS LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_RECOVERY LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_DEBT_BURNDOWN LIMIT 5;
SELECT * FROM CORE.V_AI_WORKFLOW_ACTION_AUDIT LIMIT 5;

SELECT * FROM CORE.V_AI_DRIFT_REMEDIATION_CANDIDATES LIMIT 5;
SELECT * FROM CORE.V_AI_STALE_REVIEW_CANDIDATES LIMIT 5;
SELECT * FROM CORE.V_AI_POLICY_REMEDIATION_CANDIDATES LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_RECOVERY_READINESS LIMIT 5;
SELECT * FROM CORE.V_AI_AUTOMATION_COMMAND_QUEUE LIMIT 5;

SELECT * FROM CORE.V_AI_LATEST_GOVERNANCE_STATE LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_EXECUTION_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_GOVERNANCE_APPROVAL_AUDIT LIMIT 5;
SELECT * FROM CORE.V_AI_CERTIFICATION_ELIGIBILITY_CANDIDATES LIMIT 5;

-- =========================================================
-- 10. AI CONTINUOUS MONITORING SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_TRUST_DECAY_ANALYTICS LIMIT 10;
SELECT * FROM CORE.V_AI_RECERTIFICATION_CANDIDATES LIMIT 10;

SELECT
  COUNT(*) AS ACTIVE_MONITORING_COUNT
FROM CORE.AI_CONTINUOUS_MONITORING
WHERE MONITORING_STATUS = 'ACTIVE';

SELECT
  CASE_ID,
  REGISTRY_ID,
  COUNT(*) AS ACTIVE_ROWS
FROM CORE.AI_CONTINUOUS_MONITORING
WHERE MONITORING_STATUS = 'ACTIVE'
GROUP BY CASE_ID, REGISTRY_ID
HAVING COUNT(*) > 1;

-- =========================================================
-- 10A. GOVERNANCE CONTINUITY VALIDATION
-- =========================================================
-- These checks validate deterministic governance continuity integrity.

SELECT
  'ACTIVE_MONITORING_DUPLICATE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    CASE_ID,
    REGISTRY_ID,
    COUNT(*) AS ACTIVE_ROWS
  FROM CORE.AI_CONTINUOUS_MONITORING
  WHERE MONITORING_STATUS = 'ACTIVE'
  GROUP BY CASE_ID, REGISTRY_ID
  HAVING COUNT(*) > 1
);

SELECT
  'RECERTIFICATION_QUEUE_NULL_CASE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RECERTIFICATION_QUEUE
WHERE CASE_ID IS NULL;

SELECT
  'RECERTIFICATION_QUEUE_NULL_REGISTRY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RECERTIFICATION_QUEUE
WHERE REGISTRY_ID IS NULL;

-- =========================================================
-- 11. REVIEW STATUS VALIDATION
-- =========================================================

SELECT
  'AI_REVIEW_STATUS_INVALID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RECOMMENDATIONS
WHERE REVIEW_STATUS IS NOT NULL
  AND REVIEW_STATUS NOT IN (
    'PENDING',
    'APPROVED',
    'REJECTED',
    'DEFERRED',
    'NEEDS_MORE_EVIDENCE'
  );

-- =========================================================
-- 12. OBSERVATION DATA VALIDATION
-- =========================================================

SELECT
  'AI_OBSERVATIONS_WITHOUT_CASE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_OBSERVATIONS
WHERE CASE_ID IS NULL;

-- =========================================================
-- 13. GOVERNANCE FEEDBACK VALIDATION
-- =========================================================

SELECT
  'STANDARD_UPDATES_WITHOUT_APPROVED_RECOMMENDATION_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_STANDARD_UPDATES su
LEFT JOIN CORE.AI_RECOMMENDATIONS r
  ON TRIM(UPPER(su.RECOMMENDATION_ID)) = TRIM(UPPER(r.AI_RECOMMENDATION_ID))
WHERE su.RECOMMENDATION_ID IS NOT NULL
  AND COALESCE(UPPER(TRIM(r.REVIEW_STATUS)), '') <> 'APPROVED';

SELECT
  'RISK_PATTERNS_MISSING_DESCRIPTION_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_RISK_PATTERNS
WHERE TRIM(COALESCE(PATTERN_DESCRIPTION, '')) = '';

SELECT
  'STANDARD_UPDATES_MISSING_PROPOSED_CHANGE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_STANDARD_UPDATES
WHERE TRIM(COALESCE(PROPOSED_CHANGE, '')) = '';

-- =========================================================
-- 14. OPERATIONS / ORCHESTRATION VALIDATION
-- =========================================================

SELECT
  'AI_CONSENSUS_INVALID_REVIEW_COUNT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_CONSENSUS_READINESS
WHERE REVIEW_COUNT < DISTINCT_REVIEWER_COUNT;

SELECT
  'AI_ORCHESTRATION_NEGATIVE_METRICS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_ORCHESTRATION_METRICS
WHERE PENDING_REVIEW_COUNT < 0
   OR APPROVED_REVIEW_COUNT < 0
   OR REJECTED_REVIEW_COUNT < 0
   OR SLA_BREACHED_COUNT < 0
   OR SLA_AT_RISK_COUNT < 0
   OR CRITICAL_REVIEW_COUNT < 0
   OR HIGH_PRIORITY_REVIEW_COUNT < 0;

SELECT
  'AI_WORKFLOW_NEGATIVE_METRICS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_WORKFLOW_METRICS
WHERE TOTAL_OBSERVATIONS < 0
   OR TOTAL_RECOMMENDATIONS < 0
   OR PENDING_RECOMMENDATIONS < 0
   OR APPROVED_RECOMMENDATIONS < 0
   OR REJECTED_RECOMMENDATIONS < 0
   OR TOTAL_STANDARD_UPDATES < 0
   OR TOTAL_RISK_PATTERNS < 0;

-- =========================================================
-- 15. ADVANCED AI GOVERNANCE VALIDATION
-- =========================================================

SELECT
  'AI_LATEST_CONSENSUS_DUPLICATE_RECOMMENDATION_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    AI_RECOMMENDATION_ID,
    COUNT(*) AS ROW_COUNT
  FROM CORE.V_AI_LATEST_CONSENSUS
  GROUP BY AI_RECOMMENDATION_ID
  HAVING COUNT(*) > 1
);

SELECT
  'AI_GOVERNANCE_RISK_NEGATIVE_SCORE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_LATEST_GOVERNANCE_RISK
WHERE GOVERNANCE_RISK_SCORE < 0
   OR GOVERNANCE_DEBT_COUNT < 0;

SELECT
  'AI_OPEN_DRIFT_RESOLVED_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_OPEN_GOVERNANCE_DRIFT
WHERE UPPER(COALESCE(RESOLUTION_STATUS, '')) <> 'OPEN';

SELECT
  'AI_REMEDIATION_QUEUE_RESOLVED_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_REMEDIATION_QUEUE
WHERE UPPER(COALESCE(TASK_STATUS, '')) = 'RESOLVED';

SELECT
  'AI_DUPLICATE_ACTIVE_MONITORING_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    CASE_ID,
    REGISTRY_ID,
    COUNT(*) AS ACTIVE_ROWS
  FROM CORE.AI_CONTINUOUS_MONITORING
  WHERE MONITORING_STATUS = 'ACTIVE'
  GROUP BY CASE_ID, REGISTRY_ID
  HAVING COUNT(*) > 1
);

-- =========================================================
-- 16. BATCH B PASS / FAIL SUMMARY
-- =========================================================

WITH CHECKS AS (

  SELECT
    'ACTIVE_MONITORING_DUPLICATE_CHECK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      CASE_ID,
      REGISTRY_ID,
      COUNT(*) AS ACTIVE_ROWS
    FROM CORE.AI_CONTINUOUS_MONITORING
    WHERE MONITORING_STATUS = 'ACTIVE'
    GROUP BY CASE_ID, REGISTRY_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'RECERTIFICATION_QUEUE_NULL_CASE_CHECK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RECERTIFICATION_QUEUE
  WHERE CASE_ID IS NULL

  UNION ALL

  SELECT
    'RECERTIFICATION_QUEUE_NULL_REGISTRY_CHECK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RECERTIFICATION_QUEUE
  WHERE REGISTRY_ID IS NULL

  UNION ALL

  SELECT
    'AI_REVIEW_STATUS_INVALID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RECOMMENDATIONS
  WHERE REVIEW_STATUS IS NOT NULL
    AND REVIEW_STATUS NOT IN (
      'PENDING',
      'APPROVED',
      'REJECTED',
      'DEFERRED',
      'NEEDS_MORE_EVIDENCE'
    )

  UNION ALL

  SELECT
    'AI_OBSERVATIONS_WITHOUT_CASE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_OBSERVATIONS
  WHERE CASE_ID IS NULL

  UNION ALL

  SELECT
    'STANDARD_UPDATES_WITHOUT_APPROVED_RECOMMENDATION' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_STANDARD_UPDATES su
  LEFT JOIN CORE.AI_RECOMMENDATIONS r
    ON TRIM(UPPER(su.RECOMMENDATION_ID)) = TRIM(UPPER(r.AI_RECOMMENDATION_ID))
  WHERE su.RECOMMENDATION_ID IS NOT NULL
    AND COALESCE(UPPER(TRIM(r.REVIEW_STATUS)), '') <> 'APPROVED'

  UNION ALL

  SELECT
    'RISK_PATTERNS_MISSING_DESCRIPTION' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_RISK_PATTERNS
  WHERE TRIM(COALESCE(PATTERN_DESCRIPTION, '')) = ''

  UNION ALL

  SELECT
    'STANDARD_UPDATES_MISSING_PROPOSED_CHANGE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_STANDARD_UPDATES
  WHERE TRIM(COALESCE(PROPOSED_CHANGE, '')) = ''

  UNION ALL

  SELECT
    'AI_CONSENSUS_INVALID_REVIEW_COUNT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_CONSENSUS_READINESS
  WHERE REVIEW_COUNT < DISTINCT_REVIEWER_COUNT

  UNION ALL

  SELECT
    'AI_ORCHESTRATION_NEGATIVE_METRICS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_ORCHESTRATION_METRICS
  WHERE PENDING_REVIEW_COUNT < 0
     OR APPROVED_REVIEW_COUNT < 0
     OR REJECTED_REVIEW_COUNT < 0
     OR SLA_BREACHED_COUNT < 0
     OR SLA_AT_RISK_COUNT < 0
     OR CRITICAL_REVIEW_COUNT < 0
     OR HIGH_PRIORITY_REVIEW_COUNT < 0

  UNION ALL

  SELECT
    'AI_WORKFLOW_NEGATIVE_METRICS' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_WORKFLOW_METRICS
  WHERE TOTAL_OBSERVATIONS < 0
     OR TOTAL_RECOMMENDATIONS < 0
     OR PENDING_RECOMMENDATIONS < 0
     OR APPROVED_RECOMMENDATIONS < 0
     OR REJECTED_RECOMMENDATIONS < 0
     OR TOTAL_STANDARD_UPDATES < 0
     OR TOTAL_RISK_PATTERNS < 0

  UNION ALL

  SELECT
    'AI_LATEST_CONSENSUS_DUPLICATE_RECOMMENDATION' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      AI_RECOMMENDATION_ID,
      COUNT(*) AS ROW_COUNT
    FROM CORE.V_AI_LATEST_CONSENSUS
    GROUP BY AI_RECOMMENDATION_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'AI_GOVERNANCE_RISK_NEGATIVE_SCORE' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_LATEST_GOVERNANCE_RISK
  WHERE GOVERNANCE_RISK_SCORE < 0
     OR GOVERNANCE_DEBT_COUNT < 0

  UNION ALL

  SELECT
    'AI_OPEN_DRIFT_RESOLVED_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_OPEN_GOVERNANCE_DRIFT
  WHERE UPPER(COALESCE(RESOLUTION_STATUS, '')) <> 'OPEN'

  UNION ALL

  SELECT
    'AI_REMEDIATION_QUEUE_RESOLVED_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_REMEDIATION_QUEUE
  WHERE UPPER(COALESCE(TASK_STATUS, '')) = 'RESOLVED'

  UNION ALL

  SELECT
    'AI_DUPLICATE_ACTIVE_MONITORING' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      CASE_ID,
      REGISTRY_ID,
      COUNT(*) AS ACTIVE_ROWS
    FROM CORE.AI_CONTINUOUS_MONITORING
    WHERE MONITORING_STATUS = 'ACTIVE'
    GROUP BY CASE_ID, REGISTRY_ID
    HAVING COUNT(*) > 1
  )

)

SELECT
  CHECK_NAME,
  BAD_ROWS,
  CASE
    WHEN BAD_ROWS = 0 THEN 'PASS'
    ELSE 'FAIL'
  END AS STATUS
FROM CHECKS;

-- =========================================================
-- 17. FINAL MARKERS
-- =========================================================

SELECT
  'GAFAIG_GOVERNANCE_CONTINUITY_VALIDATION_BATCH_B_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_AI_GOVERNANCE_VALIDATION_BATCH_B_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_GOVERNANCE_WORKFLOW_VALIDATION_BATCH_B_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_GOVERNANCE_CONTINUITY_ENFORCEMENT_BATCH_B_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;