-- =========================================================
-- 99C_RUN_GOVERNANCE_SIMULATION_VALIDATION.sql
-- GAFAIG — NON-DESTRUCTIVE GOVERNANCE SIMULATION VALIDATION BATCH
-- Last Updated: 2026-05-16
-- =========================================================

-- Canonical doctrine:
-- Snowflake is the source of truth.
-- API is pass-through only.
-- UI is display only.
-- Registry is append-only.
-- Certification is private.
-- Publication is explicit.
-- Verification uses proof.messageString only.
-- AI is advisory only.
-- Simulation is operational only.
-- Governance intelligence must NEVER override deterministic trust.
-- This batch is non-destructive and validation-only.
-- Governance simulations must never mutate certification, publication, registry, or proof state.

USE ROLE ACCOUNTADMIN;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 00A. GOVERNANCE SIMULATION CONTEXT VALIDATION
-- =========================================================

SELECT
  'GOVERNANCE_SIMULATION_VALIDATION_BATCH_C_ACTIVE' AS STATUS,
  'Layer 2 — Governance Workflow Infrastructure' AS PRIMARY_LAYER,
  'Layer 4 — Operational Validation Infrastructure' AS VALIDATION_LAYER,
  CURRENT_TIMESTAMP() AS VALIDATED_AT;

-- =========================================================
-- 01. SIMULATION TABLE STRUCTURE VALIDATION
-- =========================================================

DESC TABLE CORE.AI_GOVERNANCE_SIMULATION_SCENARIOS;
DESC TABLE CORE.AI_GOVERNANCE_SIMULATION_RUNS;
DESC TABLE CORE.AI_GOVERNANCE_SIMULATION_EVENTS;

-- =========================================================
-- 02. SIMULATION PROCEDURE EXISTENCE CHECKS
-- =========================================================

SHOW PROCEDURES LIKE 'SP_AI_CREATE_SIMULATION_SCENARIO' IN SCHEMA GAFAIG_DB.CORE;
SHOW PROCEDURES LIKE 'SP_AI_RUN_GOVERNANCE_SIMULATION' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 03. SIMULATION VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_AI_SIMULATION_SCENARIO_LIBRARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_SIMULATION_RUN_SUMMARY' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_SIMULATION_IMPACT' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_AI_SIMULATION_DASHBOARD_ROLLUP' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 04. SIMULATION / STRESS TESTING SMOKE TESTS
-- =========================================================

SELECT * FROM CORE.V_AI_SIMULATION_SCENARIO_LIBRARY LIMIT 10;

SELECT *
FROM CORE.V_AI_SIMULATION_RUN_SUMMARY
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT *
FROM CORE.V_AI_SIMULATION_IMPACT
ORDER BY CREATED_AT DESC
LIMIT 10;

SELECT *
FROM CORE.V_AI_SIMULATION_DASHBOARD_ROLLUP;

-- =========================================================
-- 05. SIMULATION DATA VALIDATION
-- =========================================================

SELECT
  'SIMULATION_SCENARIO_NULL_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_GOVERNANCE_SIMULATION_SCENARIOS
WHERE AI_SIMULATION_SCENARIO_ID IS NULL;

SELECT
  'SIMULATION_RUN_NULL_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
WHERE AI_SIMULATION_RUN_ID IS NULL;

SELECT
  'SIMULATION_EVENT_NULL_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_GOVERNANCE_SIMULATION_EVENTS
WHERE AI_SIMULATION_EVENT_ID IS NULL;

SELECT
  'SIMULATION_RUN_NULL_SCENARIO_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
WHERE AI_SIMULATION_SCENARIO_ID IS NULL;

SELECT
  'SIMULATION_EVENT_NULL_RUN_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.AI_GOVERNANCE_SIMULATION_EVENTS
WHERE AI_SIMULATION_RUN_ID IS NULL;

-- =========================================================
-- 06. SIMULATION NON-DESTRUCTIVE BOUNDARY VALIDATION
-- =========================================================
-- These checks validate that simulation infrastructure remains operational only.
-- Simulations must not mutate certification, publication, registry, or proof state.

SELECT
  'SIMULATION_REGISTRY_ID_REFERENCE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS SIMULATION_RUNS_WITH_REGISTRY_REFERENCE
FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
WHERE REGISTRY_ID IS NOT NULL;

SELECT
  'SIMULATION_CASE_ID_REFERENCE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS SIMULATION_RUNS_WITH_CASE_REFERENCE
FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
WHERE CASE_ID IS NOT NULL;

SELECT
  'SIMULATION_EVENT_CASE_REFERENCE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS SIMULATION_EVENTS_WITH_CASE_REFERENCE
FROM CORE.AI_GOVERNANCE_SIMULATION_EVENTS
WHERE CASE_ID IS NOT NULL;

-- =========================================================
-- 07. SIMULATION DUPLICATE RUN VALIDATION
-- =========================================================

SELECT
  'AI_SIMULATION_RECENT_DUPLICATE_RUN_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    CASE_ID,
    REGISTRY_ID,
    AI_SIMULATION_SCENARIO_ID,
    COUNT(*) AS RUN_COUNT
  FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
  WHERE CREATED_AT >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP())
  GROUP BY CASE_ID, REGISTRY_ID, AI_SIMULATION_SCENARIO_ID
  HAVING COUNT(*) > 1
);

-- =========================================================
-- 08. SIMULATION VIEW INTEGRITY VALIDATION
-- =========================================================

SELECT
  'SIMULATION_RUN_SUMMARY_NULL_RUN_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_SIMULATION_RUN_SUMMARY
WHERE AI_SIMULATION_RUN_ID IS NULL;

SELECT
  'SIMULATION_IMPACT_NULL_RUN_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_SIMULATION_IMPACT
WHERE AI_SIMULATION_RUN_ID IS NULL;

SELECT
  'SIMULATION_SCENARIO_LIBRARY_NULL_SCENARIO_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_AI_SIMULATION_SCENARIO_LIBRARY
WHERE AI_SIMULATION_SCENARIO_ID IS NULL;

-- =========================================================
-- 09. BATCH C PASS / FAIL SUMMARY
-- =========================================================

WITH CHECKS AS (

  SELECT
    'SIMULATION_SCENARIO_NULL_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_GOVERNANCE_SIMULATION_SCENARIOS
  WHERE AI_SIMULATION_SCENARIO_ID IS NULL

  UNION ALL

  SELECT
    'SIMULATION_RUN_NULL_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
  WHERE AI_SIMULATION_RUN_ID IS NULL

  UNION ALL

  SELECT
    'SIMULATION_EVENT_NULL_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_GOVERNANCE_SIMULATION_EVENTS
  WHERE AI_SIMULATION_EVENT_ID IS NULL

  UNION ALL

  SELECT
    'SIMULATION_RUN_NULL_SCENARIO' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
  WHERE AI_SIMULATION_SCENARIO_ID IS NULL

  UNION ALL

  SELECT
    'SIMULATION_EVENT_NULL_RUN' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.AI_GOVERNANCE_SIMULATION_EVENTS
  WHERE AI_SIMULATION_RUN_ID IS NULL

  UNION ALL

  SELECT
    'AI_SIMULATION_RECENT_DUPLICATE_RUN' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      CASE_ID,
      REGISTRY_ID,
      AI_SIMULATION_SCENARIO_ID,
      COUNT(*) AS RUN_COUNT
    FROM CORE.AI_GOVERNANCE_SIMULATION_RUNS
    WHERE CREATED_AT >= DATEADD(MINUTE, -5, CURRENT_TIMESTAMP())
    GROUP BY CASE_ID, REGISTRY_ID, AI_SIMULATION_SCENARIO_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'SIMULATION_RUN_SUMMARY_NULL_RUN_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_SIMULATION_RUN_SUMMARY
  WHERE AI_SIMULATION_RUN_ID IS NULL

  UNION ALL

  SELECT
    'SIMULATION_IMPACT_NULL_RUN_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_SIMULATION_IMPACT
  WHERE AI_SIMULATION_RUN_ID IS NULL

  UNION ALL

  SELECT
    'SIMULATION_SCENARIO_LIBRARY_NULL_SCENARIO_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_AI_SIMULATION_SCENARIO_LIBRARY
  WHERE AI_SIMULATION_SCENARIO_ID IS NULL

)

SELECT
  CHECK_NAME,
  BAD_ROWS,
  CASE
    WHEN BAD_ROWS = 0 THEN 'PASS'
    ELSE 'FAIL'
  END AS STATUS
FROM CHECKS;

-- =========================================================
-- 10. FINAL MARKERS
-- =========================================================

SELECT
  'GAFAIG_GOVERNANCE_SIMULATION_VALIDATION_BATCH_C_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_SIMULATION_NON_DESTRUCTIVE_BOUNDARY_BATCH_C_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_SIMULATION_VIEW_INTEGRITY_BATCH_C_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_SIMULATION_OPERATIONAL_VALIDATION_BATCH_C_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;