-- =========================================================
-- 99D_RUN_PUBLIC_SURFACE_VALIDATION.sql
-- GAFAIG — NON-DESTRUCTIVE PUBLIC SURFACE VALIDATION BATCH
-- Last Updated: 2026-05-16
-- =========================================================

-- Canonical doctrine:
-- Snowflake is the source of truth.
-- API is pass-through only.
-- UI is display only.
-- Registry is append-only.
-- Certification is private.
-- Publication is explicit.
-- Verification uses proof.messageString only.
-- Public governance trust surfaces must remain publication-controlled.
-- This batch is non-destructive and validation-only.
-- Public surfaces must never expose unpublished or private governance data.
-- Public observability surfaces may be aggregate and are not required to be registry-granular.

USE ROLE ACCOUNTADMIN;
USE DATABASE GAFAIG_DB;
USE SCHEMA CORE;
USE WAREHOUSE GAFAIG_WH;

-- =========================================================
-- 00. CONTEXT CHECK
-- =========================================================

SELECT
  CURRENT_DATABASE() AS CURRENT_DATABASE,
  CURRENT_SCHEMA() AS CURRENT_SCHEMA,
  CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
  CURRENT_ROLE() AS CURRENT_ROLE,
  CURRENT_TIMESTAMP() AS RUN_AT;

-- =========================================================
-- 00A. PUBLIC SURFACE CONTEXT VALIDATION
-- =========================================================

SELECT
  'PUBLIC_SURFACE_VALIDATION_BATCH_D_ACTIVE' AS STATUS,
  'Layer 3 — Public Governance Trust Infrastructure' AS PRIMARY_LAYER,
  'Layer 4 — Operational Validation Infrastructure' AS VALIDATION_LAYER,
  CURRENT_TIMESTAMP() AS VALIDATED_AT;

-- =========================================================
-- 01. PUBLIC REGISTRY VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_REGISTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_LATEST_APPROVED' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_AI_SYSTEMS_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_REGISTRY_PUBLIC_SEARCH' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 02. PUBLIC OBSERVABILITY VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_LIFECYCLE_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_LIFECYCLE_BY_COUNTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_LIFECYCLE_BY_ORGANIZATION_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_RENEWAL_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_RENEWAL_BY_COUNTRY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_RENEWAL_BY_ORGANIZATION_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;

SHOW VIEWS LIKE 'V_OBSERVABILITY_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 03. PUBLIC INTELLIGENCE VIEW EXISTENCE CHECKS
-- =========================================================

SHOW VIEWS LIKE 'V_COUNTRY_INTELLIGENCE_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;
SHOW VIEWS LIKE 'V_ORGANIZATION_INTELLIGENCE_PUBLIC' IN SCHEMA GAFAIG_DB.CORE;

-- =========================================================
-- 04. PUBLIC REGISTRY SURFACE SMOKE TESTS
-- =========================================================

SELECT *
FROM CORE.V_REGISTRY_PUBLIC
ORDER BY PUBLISHED_AT DESC
LIMIT 10;

SELECT *
FROM CORE.V_REGISTRY_LATEST_APPROVED
LIMIT 10;

SELECT *
FROM CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
LIMIT 10;

-- =========================================================
-- 05. PUBLIC OBSERVABILITY SURFACE SMOKE TESTS
-- =========================================================

SELECT *
FROM CORE.V_LIFECYCLE_PUBLIC
LIMIT 10;

SELECT *
FROM CORE.V_LIFECYCLE_BY_COUNTRY_PUBLIC
LIMIT 10;

SELECT *
FROM CORE.V_LIFECYCLE_BY_ORGANIZATION_PUBLIC
LIMIT 10;

SELECT *
FROM CORE.V_RENEWAL_PUBLIC
LIMIT 10;

SELECT *
FROM CORE.V_RENEWAL_BY_COUNTRY_PUBLIC
LIMIT 10;

SELECT *
FROM CORE.V_RENEWAL_BY_ORGANIZATION_PUBLIC
LIMIT 10;

SELECT *
FROM CORE.V_OBSERVABILITY_PUBLIC
LIMIT 10;

-- =========================================================
-- 06. PUBLIC SURFACE PUBLICATION ENFORCEMENT VALIDATION
-- =========================================================

SELECT
  'REGISTRY_PUBLIC_VISIBILITY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'
   OR PUBLISHED_AT IS NULL;

SELECT
  'REGISTRY_AI_SYSTEMS_PUBLIC_VISIBILITY_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
WHERE REGISTRY_ID IS NULL;

SELECT
  'LIFECYCLE_PUBLIC_REQUIRED_FIELDS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_LIFECYCLE_PUBLIC
WHERE REGISTRY_ID IS NULL;

SELECT
  'RENEWAL_PUBLIC_REQUIRED_FIELDS_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_RENEWAL_PUBLIC
WHERE REGISTRY_ID IS NULL;

-- =========================================================
-- 07. PUBLIC SURFACE PRIVATE DATA LEAKAGE VALIDATION
-- =========================================================

SELECT
  'REGISTRY_PUBLIC_PRIVATE_ID_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_COLUMNS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
  AND COLUMN_NAME IN (
    'APPLICATION_ID',
    'CASE_ID',
    'FINDING_ID',
    'EVIDENCE_ID',
    'INTERNAL_SCORE',
    'FINAL_SCORE',
    'SCORE',
    'TIER',
    'BAND'
  );

SELECT
  'REGISTRY_AI_SYSTEMS_PUBLIC_PRIVATE_ID_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_COLUMNS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_REGISTRY_AI_SYSTEMS_PUBLIC'
  AND COLUMN_NAME IN (
    'APPLICATION_ID',
    'CASE_ID',
    'FINDING_ID',
    'EVIDENCE_ID',
    'INTERNAL_SCORE',
    'FINAL_SCORE',
    'SCORE',
    'TIER',
    'BAND'
  );

SELECT
  'PUBLIC_OBSERVABILITY_AI_COLUMN_LEAK_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_COLUMNS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME IN (
    'V_LIFECYCLE_PUBLIC',
    'V_RENEWAL_PUBLIC',
    'V_OBSERVABILITY_PUBLIC'
  )
  AND COLUMN_NAME LIKE 'AI_%';

-- =========================================================
-- 08. PUBLIC SURFACE VERIFICATION-SAFE CONTRACT VALIDATION
-- =========================================================

SELECT
  'REGISTRY_PUBLIC_VERIFICATION_CONTRACT_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM CORE.V_REGISTRY_PUBLIC
WHERE REGISTRY_ID IS NULL
   OR CERTIFICATION_STATUS IS NULL
   OR VISIBILITY_STATUS IS NULL
   OR PUBLISHED_AT IS NULL;

SELECT
  'REGISTRY_PUBLIC_DUPLICATE_REGISTRY_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    REGISTRY_ID,
    COUNT(*) AS ROW_COUNT
  FROM CORE.V_REGISTRY_PUBLIC
  GROUP BY REGISTRY_ID
  HAVING COUNT(*) > 1
);

SELECT
  'REGISTRY_AI_SYSTEMS_PUBLIC_DUPLICATE_SYSTEM_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    REGISTRY_ID,
    SYSTEM_ID,
    COUNT(*) AS ROW_COUNT
  FROM CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
  GROUP BY REGISTRY_ID, SYSTEM_ID
  HAVING COUNT(*) > 1
);

-- =========================================================
-- 09. PUBLIC LIFECYCLE / RENEWAL INTEGRITY
-- =========================================================

SELECT
  'LIFECYCLE_PUBLIC_DUPLICATE_REGISTRY_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    REGISTRY_ID,
    COUNT(*) AS ROW_COUNT
  FROM CORE.V_LIFECYCLE_PUBLIC
  GROUP BY REGISTRY_ID
  HAVING COUNT(*) > 1
);

SELECT
  'RENEWAL_PUBLIC_DUPLICATE_REGISTRY_ID_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_ROWS
FROM (
  SELECT
    REGISTRY_ID,
    COUNT(*) AS ROW_COUNT
  FROM CORE.V_RENEWAL_PUBLIC
  GROUP BY REGISTRY_ID
  HAVING COUNT(*) > 1
);

-- =========================================================
-- 09A. PUBLIC OBSERVABILITY AGGREGATE CONTRACT VALIDATION
-- =========================================================
-- V_OBSERVABILITY_PUBLIC may be aggregate-level and is not required to expose REGISTRY_ID.

SELECT
  'OBSERVABILITY_PUBLIC_VIEW_AVAILABLE_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS MATCHING_OBJECTS
FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_OBSERVABILITY_PUBLIC';

SELECT
  'OBSERVABILITY_PUBLIC_PRIVATE_ID_COLUMN_CHECK' AS VALIDATION_NAME,
  COUNT(*) AS BAD_COLUMNS
FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND TABLE_NAME = 'V_OBSERVABILITY_PUBLIC'
  AND COLUMN_NAME IN (
    'APPLICATION_ID',
    'CASE_ID',
    'FINDING_ID',
    'EVIDENCE_ID',
    'INTERNAL_SCORE',
    'FINAL_SCORE',
    'SCORE',
    'TIER',
    'BAND'
  );

-- =========================================================
-- 10. BATCH D PASS / FAIL SUMMARY
-- =========================================================

WITH CHECKS AS (

  SELECT
    'REGISTRY_PUBLIC_VISIBILITY' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE COALESCE(VISIBILITY_STATUS, '') <> 'public'
     OR PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'REGISTRY_AI_SYSTEMS_PUBLIC_MISSING_REGISTRY_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
  WHERE REGISTRY_ID IS NULL

  UNION ALL

  SELECT
    'LIFECYCLE_PUBLIC_MISSING_REGISTRY_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_LIFECYCLE_PUBLIC
  WHERE REGISTRY_ID IS NULL

  UNION ALL

  SELECT
    'RENEWAL_PUBLIC_MISSING_REGISTRY_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_RENEWAL_PUBLIC
  WHERE REGISTRY_ID IS NULL

  UNION ALL

  SELECT
    'REGISTRY_PUBLIC_PRIVATE_ID_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_REGISTRY_PUBLIC'
    AND COLUMN_NAME IN (
      'APPLICATION_ID',
      'CASE_ID',
      'FINDING_ID',
      'EVIDENCE_ID',
      'INTERNAL_SCORE',
      'FINAL_SCORE',
      'SCORE',
      'TIER',
      'BAND'
    )

  UNION ALL

  SELECT
    'PUBLIC_OBSERVABILITY_AI_COLUMN_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME IN (
      'V_LIFECYCLE_PUBLIC',
      'V_RENEWAL_PUBLIC',
      'V_OBSERVABILITY_PUBLIC'
    )
    AND COLUMN_NAME LIKE 'AI_%'

  UNION ALL

  SELECT
    'REGISTRY_PUBLIC_VERIFICATION_CONTRACT' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM CORE.V_REGISTRY_PUBLIC
  WHERE REGISTRY_ID IS NULL
     OR CERTIFICATION_STATUS IS NULL
     OR VISIBILITY_STATUS IS NULL
     OR PUBLISHED_AT IS NULL

  UNION ALL

  SELECT
    'REGISTRY_PUBLIC_DUPLICATE_REGISTRY_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      REGISTRY_ID,
      COUNT(*) AS ROW_COUNT
    FROM CORE.V_REGISTRY_PUBLIC
    GROUP BY REGISTRY_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'REGISTRY_AI_SYSTEMS_PUBLIC_DUPLICATE_SYSTEM' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      REGISTRY_ID,
      SYSTEM_ID,
      COUNT(*) AS ROW_COUNT
    FROM CORE.V_REGISTRY_AI_SYSTEMS_PUBLIC
    GROUP BY REGISTRY_ID, SYSTEM_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'LIFECYCLE_PUBLIC_DUPLICATE_REGISTRY_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      REGISTRY_ID,
      COUNT(*) AS ROW_COUNT
    FROM CORE.V_LIFECYCLE_PUBLIC
    GROUP BY REGISTRY_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'RENEWAL_PUBLIC_DUPLICATE_REGISTRY_ID' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM (
    SELECT
      REGISTRY_ID,
      COUNT(*) AS ROW_COUNT
    FROM CORE.V_RENEWAL_PUBLIC
    GROUP BY REGISTRY_ID
    HAVING COUNT(*) > 1
  )

  UNION ALL

  SELECT
    'OBSERVABILITY_PUBLIC_VIEW_AVAILABLE' AS CHECK_NAME,
    CASE
      WHEN COUNT(*) = 0 THEN 1
      ELSE 0
    END AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_OBSERVABILITY_PUBLIC'

  UNION ALL

  SELECT
    'OBSERVABILITY_PUBLIC_PRIVATE_ID_COLUMN_LEAK' AS CHECK_NAME,
    COUNT(*) AS BAD_ROWS
  FROM GAFAIG_DB.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'CORE'
    AND TABLE_NAME = 'V_OBSERVABILITY_PUBLIC'
    AND COLUMN_NAME IN (
      'APPLICATION_ID',
      'CASE_ID',
      'FINDING_ID',
      'EVIDENCE_ID',
      'INTERNAL_SCORE',
      'FINAL_SCORE',
      'SCORE',
      'TIER',
      'BAND'
    )

)

SELECT
  CHECK_NAME,
  BAD_ROWS,
  CASE
    WHEN BAD_ROWS = 0 THEN 'PASS'
    ELSE 'FAIL'
  END AS STATUS
FROM CHECKS;

-- =========================================================
-- 11. FINAL MARKERS
-- =========================================================

SELECT
  'GAFAIG_PUBLIC_SURFACE_VALIDATION_BATCH_D_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_PUBLIC_OBSERVABILITY_VALIDATION_BATCH_D_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_PUBLIC_CONTRACT_VALIDATION_BATCH_D_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;

SELECT
  'GAFAIG_PUBLIC_GOVERNANCE_TRUST_SURFACE_BATCH_D_COMPLETE' AS STATUS,
  CURRENT_TIMESTAMP() AS COMPLETED_AT;