GET_DDL('DATABASE', 'GAFAIG_DB')
create or replace database GAFAIG_DB;

create or replace schema AI_REGISTRY;

create or replace schema AUDIT;

create or replace schema CORE;

create or replace sequence REGISTRY_ID_SEQ start with 1 increment by 1 noorder;
create or replace TABLE APPLICATIONS (
	REQUEST_ID VARCHAR(16777216) NOT NULL,
	TYPE VARCHAR(16777216) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	ORG_NAME VARCHAR(16777216) NOT NULL,
	EMAIL VARCHAR(16777216) NOT NULL,
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	APPLICATION_ID VARCHAR(16777216),
	ORG_TYPE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	primary key (REQUEST_ID)
);
create or replace TABLE CASE_APPROVAL_LOG (
	LOG_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
	CASE_ID VARCHAR(16777216) NOT NULL,
	ACTION VARCHAR(16777216) NOT NULL,
	ACTOR VARCHAR(16777216),
	ACTION_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES VARCHAR(16777216)
);
create or replace TABLE CASE_CONTROL_ATTESTATIONS (
	CASE_ID VARCHAR(16777216),
	STANDARD_CODE VARCHAR(16777216) DEFAULT 'HG',
	STANDARD_VERSION VARCHAR(16777216) DEFAULT 'v1.0',
	CONTROL_CODE VARCHAR(16777216),
	CONTROL_STATUS VARCHAR(16777216),
	EVIDENCE_COUNT NUMBER(18,0) DEFAULT 0,
	HAS_SUMMARY BOOLEAN DEFAULT FALSE,
	LAST_TESTED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE CASE_SCORES_V1 (
	SNAPSHOT_ID VARCHAR(16777216),
	CASE_ID VARCHAR(16777216),
	MODEL_VERSION VARCHAR(16777216),
	SCORE NUMBER(10,4),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE CASE_SCORE_SNAPSHOTS (
	CASE_ID VARCHAR(16777216) NOT NULL,
	SCORING_MODEL_VERSION VARCHAR(16777216) NOT NULL,
	SNAPSHOT_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TIER VARCHAR(16777216),
	BAND VARCHAR(16777216),
	FINAL_SCORE NUMBER(10,4),
	CONTROLS_PCT NUMBER(10,4),
	COVERAGE_PCT NUMBER(10,4),
	FRESHNESS_PCT NUMBER(10,4),
	SUMMARY_PCT NUMBER(10,4),
	FINDINGS_TOTAL NUMBER(38,0),
	EVIDENCE_TOTAL NUMBER(38,0),
	EVIDENCE_WITH_SUMMARY NUMBER(38,0),
	LAST_ACTIVITY_AT TIMESTAMP_NTZ(9),
	SNAPSHOT_ID VARCHAR(16777216),
	APPLICATION_ID VARCHAR(16777216),
	TOTAL_SCORE NUMBER(38,0),
	SCORE_COMPONENTS VARIANT,
	CALCULATED_AT TIMESTAMP_NTZ(9),
	primary key (CASE_ID, SCORING_MODEL_VERSION)
);
create or replace TABLE CASE_SCORE_SNAPSHOTS_V2 cluster by (CASE_ID, SCORING_MODEL_VERSION)(
	SNAPSHOT_ID VARCHAR(16777216) NOT NULL DEFAULT UUID_STRING(),
	CASE_ID VARCHAR(16777216) NOT NULL,
	SCORING_MODEL_VERSION VARCHAR(16777216) NOT NULL,
	SNAPSHOT_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TIER VARCHAR(16777216),
	BAND VARCHAR(16777216),
	FINAL_SCORE NUMBER(10,4),
	CONTROLS_PCT NUMBER(10,4),
	COVERAGE_PCT NUMBER(10,4),
	FRESHNESS_PCT NUMBER(10,4),
	SUMMARY_PCT NUMBER(10,4),
	FINDINGS_TOTAL NUMBER(38,0),
	EVIDENCE_TOTAL NUMBER(38,0),
	EVIDENCE_WITH_SUMMARY NUMBER(38,0),
	LAST_ACTIVITY_AT TIMESTAMP_NTZ(9),
	SNAPSHOT_ACTION VARCHAR(16777216),
	SNAPSHOT_ACTOR VARCHAR(16777216),
	SNAPSHOT_NOTES VARCHAR(16777216),
	primary key (SNAPSHOT_ID)
);
create or replace TABLE DECISIONS (
	DECISION_ID VARCHAR(16777216),
	APPLICATION_ID VARCHAR(16777216),
	SNAPSHOT_ID VARCHAR(16777216),
	DECISION_STATUS VARCHAR(16777216),
	CERTIFICATION_TIER VARCHAR(16777216),
	CERTIFICATION_BAND VARCHAR(16777216),
	VALID_FROM TIMESTAMP_NTZ(9),
	VALID_TO TIMESTAMP_NTZ(9),
	DECISION_NOTES VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE EVENTS (
	EVENT_ID VARCHAR(16777216),
	APPLICATION_ID VARCHAR(16777216),
	FINDING_ID VARCHAR(16777216),
	EVIDENCE_ID VARCHAR(16777216),
	EVENT_TYPE VARCHAR(16777216),
	ACTOR_TYPE VARCHAR(16777216),
	ACTOR_ID VARCHAR(16777216),
	EVENT_DETAILS VARIANT,
	CREATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE EVIDENCE (
	EVIDENCE_ID VARCHAR(16777216),
	FINDING_ID VARCHAR(16777216),
	APPLICATION_ID VARCHAR(16777216),
	EVIDENCE_TYPE VARCHAR(16777216),
	TITLE VARCHAR(16777216),
	SOURCE_URL VARCHAR(16777216),
	STORAGE_REF VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE EVIDENCE_SUMMARIES (
	EVIDENCE_ID VARCHAR(16777216) NOT NULL,
	STYLE VARCHAR(16777216) NOT NULL,
	MODEL VARCHAR(16777216) NOT NULL,
	SUMMARY VARCHAR(16777216) NOT NULL,
	CORTEX_AVAILABLE BOOLEAN,
	CORTEX_ERROR VARCHAR(16777216),
	PROMPT_VERSION VARCHAR(16777216),
	INPUT_CHARS NUMBER(38,0),
	OUTPUT_CHARS NUMBER(38,0),
	CREATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE FINDINGS (
	FINDING_ID VARCHAR(16777216),
	APPLICATION_ID VARCHAR(16777216),
	PARTICIPANT_ID VARCHAR(16777216),
	CONTROL_CODE VARCHAR(16777216),
	CONTROL_DOMAIN VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	SEVERITY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE FINDING_EVIDENCE_MAP (
	CASE_ID VARCHAR(16777216) NOT NULL,
	FINDING_ID VARCHAR(16777216) NOT NULL,
	EVIDENCE_ID VARCHAR(16777216) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT CURRENT_USER(),
	constraint PK_FINDING_EVIDENCE_MAP primary key (CASE_ID, FINDING_ID, EVIDENCE_ID)
);
create or replace TABLE PARTICIPANTS (
	PARTICIPANT_ID VARCHAR(16777216) NOT NULL DEFAULT UUID_STRING(),
	PARTICIPANT_TYPE VARCHAR(16777216),
	JURISDICTION_LEVEL VARCHAR(16777216),
	NAME VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	WEBSITE VARCHAR(16777216),
	PROFILE_SLUG VARCHAR(16777216),
	DESIGNATION_LEVEL VARCHAR(16777216),
	VERIFICATION_STATUS VARCHAR(16777216) DEFAULT 'unverified',
	CONTACT_EMAIL VARCHAR(16777216),
	PUBLIC_SUMMARY VARCHAR(16777216),
	LOGO_URL VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(16777216) DEFAULT 'unverified',
	APPLICATION_ID VARCHAR(16777216),
	ENTITY_NAME VARCHAR(16777216),
	ENTITY_TYPE VARCHAR(16777216),
	constraint PK_PARTICIPANTS primary key (PARTICIPANT_ID)
);
create or replace TABLE REGISTRY_AI_SYSTEMS (
	SYSTEM_ID VARCHAR(16777216) NOT NULL,
	REGISTRY_ID VARCHAR(16777216) NOT NULL,
	APPLICATION_ID VARCHAR(16777216),
	CASE_ID VARCHAR(16777216),
	SYSTEM_NAME VARCHAR(16777216) NOT NULL,
	SYSTEM_TYPE VARCHAR(16777216),
	INTENDED_USE VARCHAR(16777216),
	DEPLOYMENT_STATUS VARCHAR(16777216),
	OVERSIGHT_LEVEL VARCHAR(16777216),
	RISK_TIER VARCHAR(16777216),
	PUBLIC_SUMMARY VARCHAR(16777216),
	IS_PUBLIC BOOLEAN DEFAULT TRUE,
	DISPLAY_ORDER NUMBER(38,0) DEFAULT 100,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_REGISTRY_AI_SYSTEMS primary key (SYSTEM_ID)
);
create or replace TABLE REGISTRY_ENTITIES (
	REGISTRY_ID VARCHAR(16777216),
	APPLICATION_ID VARCHAR(16777216),
	PARTICIPANT_ID VARCHAR(16777216),
	ENTITY_NAME VARCHAR(16777216),
	ENTITY_TYPE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE REGISTRY_SNAPSHOTS cluster by (CASE_ID, APPROVED_AT)(
	SNAPSHOT_ID VARCHAR(16777216) NOT NULL,
	CASE_ID VARCHAR(16777216) NOT NULL,
	ORG_ID VARCHAR(16777216),
	STANDARD_CODE VARCHAR(16777216),
	STANDARD_VERSION VARCHAR(16777216),
	FINAL_SCORE NUMBER(10,4),
	TIER VARCHAR(16777216),
	BAND VARCHAR(16777216),
	SUBSCORES VARIANT,
	COUNTS VARIANT,
	CASE_STATUS VARCHAR(16777216),
	LAST_ACTIVITY_AT TIMESTAMP_NTZ(9),
	APPROVED_AT TIMESTAMP_NTZ(9) NOT NULL,
	APPROVED_BY VARCHAR(16777216),
	SOURCE_VIEW VARCHAR(16777216),
	SOURCE_HASH VARCHAR(16777216),
	PAYLOAD VARIANT,
	CREATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE SCORING_CONFIG (
	CONFIG_KEY VARCHAR(16777216) NOT NULL,
	CONFIG_VALUE VARIANT NOT NULL,
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_SCORING_CONFIG primary key (CONFIG_KEY)
);
create or replace TABLE SCORING_MODEL_VERSIONS (
	SCORING_MODEL_VERSION VARCHAR(16777216) NOT NULL,
	DISPLAY_NAME VARCHAR(16777216),
	IS_DETERMINISTIC BOOLEAN,
	VIEW_NAME VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES VARCHAR(16777216),
	MODEL_NAME VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	primary key (SCORING_MODEL_VERSION)
);
create or replace TABLE SEVERITY_WEIGHTS (
	SEVERITY VARCHAR(16777216) NOT NULL,
	WEIGHT NUMBER(10,2) NOT NULL,
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_SEVERITY_WEIGHTS primary key (SEVERITY)
);
create or replace TABLE STANDARD_CONTROLS (
	STANDARD_CODE VARCHAR(16777216),
	STANDARD_VERSION VARCHAR(16777216),
	CONTROL_CODE VARCHAR(16777216),
	CONTROL_TITLE VARCHAR(16777216),
	CONTROL_DESC VARCHAR(16777216),
	WEIGHT NUMBER(10,4),
	REQUIRED BOOLEAN,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE SUBMISSIONS (
	REQUEST_ID VARCHAR(16777216) NOT NULL,
	SUBMISSION_TYPE VARCHAR(16777216),
	ORG_NAME VARCHAR(16777216),
	CONTACT_EMAIL VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	REQUESTED_TIER VARCHAR(16777216),
	RENEWAL_PERIOD VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	RAW VARIANT,
	TYPE VARCHAR(16777216),
	primary key (REQUEST_ID)
);
create or replace TABLE USER_ORG_ACCESS (
	USERNAME VARCHAR(16777216) NOT NULL,
	ORG_ID VARCHAR(16777216) NOT NULL,
	constraint PK_USER_ORG_ACCESS primary key (USERNAME, ORG_ID)
);
create or replace TABLE VERIFICATION_ASSIGNMENTS (
	ASSIGNMENT_ID VARCHAR(16777216) NOT NULL,
	CASE_ID VARCHAR(16777216) NOT NULL,
	ASSIGNED_TO VARCHAR(16777216) NOT NULL,
	ROLE VARCHAR(16777216) DEFAULT 'reviewer',
	ASSIGNED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ASSIGNMENT_ID)
);
create or replace TABLE VERIFICATION_CASES (
	CASE_ID VARCHAR(16777216) NOT NULL,
	PARTICIPANT_ID VARCHAR(16777216) NOT NULL,
	STANDARD_CODE VARCHAR(16777216) NOT NULL,
	STANDARD_VERSION VARCHAR(16777216) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	PRIORITY VARCHAR(16777216),
	SUBMITTED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	STARTED_AT TIMESTAMP_NTZ(9),
	DECIDED_AT TIMESTAMP_NTZ(9),
	REVIEW_DUE_AT TIMESTAMP_NTZ(9),
	RENEWAL_DUE_AT TIMESTAMP_NTZ(9),
	ASSIGNED_REVIEWER VARCHAR(16777216),
	DECISION_SUMMARY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ENTITY_NAME VARCHAR(16777216),
	VERIFICATION_TYPE VARCHAR(16777216),
	ORG_ID VARCHAR(16777216) NOT NULL,
	APPROVED_AT TIMESTAMP_NTZ(9),
	APPROVED_BY VARCHAR(16777216),
	APPROVAL_NOTES VARCHAR(16777216),
	UNAPPROVED_AT TIMESTAMP_NTZ(9),
	UNAPPROVED_BY VARCHAR(16777216),
	UNAPPROVAL_NOTES VARCHAR(16777216),
	primary key (CASE_ID)
) WITH ROW ACCESS POLICY GAFAIG_DB.CORE.RAP_CASES_BY_ORG ON (ORG_ID)
;
create or replace TABLE VERIFICATION_DECISIONS (
	DECISION_ID VARCHAR(16777216) NOT NULL,
	CASE_ID VARCHAR(16777216) NOT NULL,
	DECISION VARCHAR(16777216) NOT NULL,
	DECIDED_BY VARCHAR(16777216),
	DECIDED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SUMMARY VARCHAR(16777216),
	CONDITIONS VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	ORG_ID VARCHAR(16777216),
	primary key (DECISION_ID)
) WITH ROW ACCESS POLICY GAFAIG_DB.CORE.RAP_CASES_BY_ORG ON (ORG_ID)
;
create or replace TABLE VERIFICATION_EVENTS (
	EVENT_ID VARCHAR(16777216) NOT NULL,
	CASE_ID VARCHAR(16777216) NOT NULL,
	EVENT_TYPE VARCHAR(16777216) NOT NULL,
	ACTOR VARCHAR(16777216),
	DETAILS VARIANT,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ORG_ID VARCHAR(16777216),
	primary key (EVENT_ID)
) WITH ROW ACCESS POLICY GAFAIG_DB.CORE.RAP_CASES_BY_ORG ON (ORG_ID)
;
create or replace TABLE VERIFICATION_EVIDENCE cluster by (CASE_ID, CREATED_AT)(
	EVIDENCE_ID VARCHAR(16777216) NOT NULL,
	CASE_ID VARCHAR(16777216) NOT NULL,
	EVIDENCE_TYPE VARCHAR(16777216) NOT NULL,
	TITLE VARCHAR(16777216) NOT NULL,
	DESCRIPTION VARCHAR(16777216),
	SOURCE_URL VARCHAR(16777216),
	STORAGE_REF VARCHAR(16777216),
	SUBMITTED_BY VARCHAR(16777216),
	SUBMITTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	ORG_ID VARCHAR(16777216),
	primary key (EVIDENCE_ID)
) WITH ROW ACCESS POLICY GAFAIG_DB.CORE.RAP_CASES_BY_ORG ON (ORG_ID)
;
create or replace TABLE VERIFICATION_FINDINGS (
	FINDING_ID VARCHAR(16777216) NOT NULL,
	CASE_ID VARCHAR(16777216) NOT NULL,
	CONTROL_ID VARCHAR(16777216) NOT NULL,
	CONTROL_TITLE VARCHAR(16777216) NOT NULL,
	RESULT VARCHAR(16777216) NOT NULL,
	RATIONALE VARCHAR(16777216),
	SEVERITY VARCHAR(16777216) NOT NULL DEFAULT 'medium',
	EVIDENCE_IDS ARRAY,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ORG_ID VARCHAR(16777216),
	primary key (FINDING_ID)
) WITH ROW ACCESS POLICY GAFAIG_DB.CORE.RAP_CASES_BY_ORG ON (ORG_ID)
;
create or replace TABLE VERIFICATION_FINDING_EVIDENCE (
	FINDING_ID VARCHAR(16777216) NOT NULL,
	EVIDENCE_ID VARCHAR(16777216) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ORG_ID VARCHAR(16777216)
) WITH ROW ACCESS POLICY GAFAIG_DB.CORE.RAP_CASES_BY_ORG ON (ORG_ID)
;
create or replace view PARTICIPANTS_PUBLIC(
	"participantId",
	"participantType",
	"jurisdictionLevel",
	"name",
	"country",
	"website",
	"profileSlug",
	"designationLevel",
	"verificationStatus",
	"publicSummary",
	"logoUrl",
	"createdAt",
	"updatedAt"
) as
SELECT
  PARTICIPANT_ID as "participantId",
  PARTICIPANT_TYPE as "participantType",
  JURISDICTION_LEVEL as "jurisdictionLevel",
  NAME as "name",
  COUNTRY as "country",
  WEBSITE as "website",
  PROFILE_SLUG as "profileSlug",
  DESIGNATION_LEVEL as "designationLevel",
  VERIFICATION_STATUS as "verificationStatus",
  PUBLIC_SUMMARY as "publicSummary",
  LOGO_URL as "logoUrl",
  CREATED_AT as "createdAt",
  UPDATED_AT as "updatedAt"
FROM GAFAIG_DB.CORE.PARTICIPANTS
WHERE VERIFICATION_STATUS = 'verified';
create or replace view V_ADMIN_SUBMISSIONS(
	REQUEST_ID,
	TYPE,
	STATUS,
	ORG_NAME,
	CONTACT_EMAIL,
	UPDATED_AT,
	SOURCE_TABLE
) as

SELECT
  REQUEST_ID,
  TYPE,
  STATUS,
  ORG_NAME,
  EMAIL AS CONTACT_EMAIL,
  UPDATED_AT,
  'APPLICATIONS' AS SOURCE_TABLE
FROM CORE.APPLICATIONS

UNION ALL

SELECT
  REQUEST_ID,
  TYPE,
  STATUS,
  ORG_NAME,
  CONTACT_EMAIL,
  UPDATED_AT,
  'SUBMISSIONS' AS SOURCE_TABLE
FROM CORE.SUBMISSIONS;
create or replace view V_CASE_CONTROL_SCORE_CALC_V1(
	CASE_ID,
	CONTROL_CODE,
	WEIGHT,
	CONTROL_STATUS,
	EVIDENCE_COUNT,
	HAS_SUMMARY,
	LAST_TESTED_AT,
	STATUS_SCORE,
	CONTROL_POINTS,
	CONTROL_DENOM,
	COVERAGE_FLAG,
	SUMMARY_FLAG
) as
SELECT
  a.CASE_ID,
  a.CONTROL_CODE,
  c.WEIGHT,
  a.CONTROL_STATUS,
  a.EVIDENCE_COUNT,
  a.HAS_SUMMARY,
  a.LAST_TESTED_AT,

  CASE a.CONTROL_STATUS
    WHEN 'met' THEN 1.0
    WHEN 'partial' THEN 0.5
    WHEN 'not_met' THEN 0.0
    ELSE NULL
  END AS STATUS_SCORE,

  (CASE a.CONTROL_STATUS
    WHEN 'met' THEN 1.0
    WHEN 'partial' THEN 0.5
    WHEN 'not_met' THEN 0.0
    ELSE NULL
   END) * c.WEIGHT AS CONTROL_POINTS,

  c.WEIGHT AS CONTROL_DENOM,

  IFF(a.EVIDENCE_COUNT > 0,1.0,0.0) AS COVERAGE_FLAG,
  IFF(a.HAS_SUMMARY,1.0,0.0) AS SUMMARY_FLAG

FROM CASE_CONTROL_ATTESTATIONS a
JOIN STANDARD_CONTROLS c
  ON a.CONTROL_CODE = c.CONTROL_CODE
WHERE a.STANDARD_CODE='HG'
  AND a.STANDARD_VERSION='v1.0';
create or replace view V_CASE_INPUTS(
	CASE_ID,
	FINDINGS_TOTAL,
	FINDINGS_PASS,
	FINDINGS_FAIL,
	FINDINGS_NA,
	FINDINGS_APPLICABLE,
	FINDINGS_COVERED,
	EVIDENCE_TOTAL,
	EVIDENCE_WITH_SUMMARY,
	NEWEST_VALID_EVIDENCE_AT,
	CONTROLS_PCT,
	COVERAGE_PCT,
	SUMMARY_PCT,
	FRESHNESS_PCT
) as
WITH

F AS (
  SELECT
    TRIM(CASE_ID) AS CASE_ID,
    TRIM(FINDING_ID) AS FINDING_ID,
    UPPER(TRIM(RESULT)) AS STATUS
  FROM CORE.VERIFICATION_FINDINGS
),

E AS (
  SELECT
    TRIM(CASE_ID) AS CASE_ID,
    TRIM(EVIDENCE_ID) AS EVIDENCE_ID,
    COALESCE(SUBMITTED_AT, CREATED_AT) AS EVIDENCE_AT
  FROM CORE.VERIFICATION_EVIDENCE
),

S AS (
  SELECT
    TRIM(EVIDENCE_ID) AS EVIDENCE_ID,
    IFF(SUMMARY IS NOT NULL AND LENGTH(TRIM(SUMMARY)) > 0, 1, 0) AS HAS_SUMMARY,
    ROW_NUMBER() OVER (
      PARTITION BY TRIM(EVIDENCE_ID)
      ORDER BY CREATED_AT DESC
    ) AS RN
  FROM CORE.EVIDENCE_SUMMARIES
),

S_LATEST AS (
  SELECT EVIDENCE_ID, HAS_SUMMARY
  FROM S
  WHERE RN = 1
),

M AS (
  SELECT
    TRIM(CASE_ID) AS CASE_ID,
    TRIM(FINDING_ID) AS FINDING_ID,
    TRIM(EVIDENCE_ID) AS EVIDENCE_ID
  FROM CORE.FINDING_EVIDENCE_MAP
),

VALID_EVIDENCE AS (
  SELECT DISTINCT
    m.CASE_ID,
    m.FINDING_ID,
    m.EVIDENCE_ID
  FROM M m
  JOIN S_LATEST s
    ON s.EVIDENCE_ID = m.EVIDENCE_ID
   AND s.HAS_SUMMARY = 1
),

F_COUNTS AS (
  SELECT
    CASE_ID,
    COUNT(*) AS FINDINGS_TOTAL,
    SUM(IFF(STATUS = 'PASS', 1, 0)) AS FINDINGS_PASS,
    SUM(IFF(STATUS = 'FAIL', 1, 0)) AS FINDINGS_FAIL,
    SUM(IFF(STATUS = 'NA',   1, 0)) AS FINDINGS_NA,
    SUM(IFF(STATUS IN ('PASS','FAIL'), 1, 0)) AS FINDINGS_APPLICABLE
  FROM F
  GROUP BY CASE_ID
),

COVERAGE AS (
  SELECT
    f.CASE_ID,
    COUNT(DISTINCT IFF(f.STATUS IN ('PASS','FAIL')
      AND ve.FINDING_ID IS NOT NULL, f.FINDING_ID, NULL)
    ) AS FINDINGS_COVERED
  FROM F f
  LEFT JOIN (SELECT DISTINCT CASE_ID, FINDING_ID FROM VALID_EVIDENCE) ve
    ON ve.CASE_ID = f.CASE_ID
   AND ve.FINDING_ID = f.FINDING_ID
  GROUP BY f.CASE_ID
),

E_COUNTS AS (
  SELECT CASE_ID, COUNT(*) AS EVIDENCE_TOTAL
  FROM E
  GROUP BY CASE_ID
),

E_WITH_SUMMARY AS (
  SELECT
    e.CASE_ID,
    COUNT(DISTINCT e.EVIDENCE_ID) AS EVIDENCE_WITH_SUMMARY
  FROM E e
  JOIN S_LATEST s
    ON s.EVIDENCE_ID = e.EVIDENCE_ID
   AND s.HAS_SUMMARY = 1
  GROUP BY e.CASE_ID
),

NEWEST_VALID AS (
  SELECT
    ve.CASE_ID,
    MAX(e.EVIDENCE_AT) AS NEWEST_VALID_EVIDENCE_AT
  FROM (SELECT DISTINCT CASE_ID, EVIDENCE_ID FROM VALID_EVIDENCE) ve
  JOIN E e
    ON e.CASE_ID = ve.CASE_ID
   AND e.EVIDENCE_ID = ve.EVIDENCE_ID
  GROUP BY ve.CASE_ID
)

SELECT
  fc.CASE_ID,
  fc.FINDINGS_TOTAL,
  fc.FINDINGS_PASS,
  fc.FINDINGS_FAIL,
  fc.FINDINGS_NA,
  fc.FINDINGS_APPLICABLE,
  COALESCE(cv.FINDINGS_COVERED, 0) AS FINDINGS_COVERED,
  COALESCE(ec.EVIDENCE_TOTAL, 0) AS EVIDENCE_TOTAL,
  COALESCE(es.EVIDENCE_WITH_SUMMARY, 0) AS EVIDENCE_WITH_SUMMARY,
  nv.NEWEST_VALID_EVIDENCE_AT,

  IFF(fc.FINDINGS_APPLICABLE = 0, 0,
      (fc.FINDINGS_PASS::FLOAT / fc.FINDINGS_APPLICABLE::FLOAT) * 100
  ) AS CONTROLS_PCT,

  IFF(fc.FINDINGS_APPLICABLE = 0, 0,
      (COALESCE(cv.FINDINGS_COVERED,0)::FLOAT / fc.FINDINGS_APPLICABLE::FLOAT) * 100
  ) AS COVERAGE_PCT,

  IFF(COALESCE(ec.EVIDENCE_TOTAL,0) = 0, 0,
      (COALESCE(es.EVIDENCE_WITH_SUMMARY,0)::FLOAT / ec.EVIDENCE_TOTAL::FLOAT) * 100
  ) AS SUMMARY_PCT,

  CASE
    WHEN nv.NEWEST_VALID_EVIDENCE_AT IS NULL THEN 0
    ELSE
      CASE
        WHEN DATEDIFF('day', nv.NEWEST_VALID_EVIDENCE_AT::DATE, CURRENT_DATE()) BETWEEN 0 AND 90 THEN 100
        WHEN DATEDIFF('day', nv.NEWEST_VALID_EVIDENCE_AT::DATE, CURRENT_DATE()) BETWEEN 91 AND 180 THEN 80
        WHEN DATEDIFF('day', nv.NEWEST_VALID_EVIDENCE_AT::DATE, CURRENT_DATE()) BETWEEN 181 AND 365 THEN 60
        WHEN DATEDIFF('day', nv.NEWEST_VALID_EVIDENCE_AT::DATE, CURRENT_DATE()) BETWEEN 366 AND 730 THEN 40
        ELSE 20
      END
  END AS FRESHNESS_PCT

FROM F_COUNTS fc
LEFT JOIN COVERAGE cv ON cv.CASE_ID = fc.CASE_ID
LEFT JOIN E_COUNTS ec ON ec.CASE_ID = fc.CASE_ID
LEFT JOIN E_WITH_SUMMARY es ON es.CASE_ID = fc.CASE_ID
LEFT JOIN NEWEST_VALID nv ON nv.CASE_ID = fc.CASE_ID
;
create or replace view V_CASE_INPUTS_V1(
	CASE_ID,
	FINDINGS_TOTAL,
	FINDINGS_PASS,
	FINDINGS_FAIL,
	FINDINGS_NA,
	FINDINGS_APPLICABLE,
	FINDINGS_COVERED,
	EVIDENCE_TOTAL,
	EVIDENCE_WITH_SUMMARY,
	NEWEST_VALID_EVIDENCE_AT,
	CONTROLS_PCT,
	COVERAGE_PCT,
	SUMMARY_PCT,
	FRESHNESS_PCT
) COMMENT='GAFAIG Scoring Model v1.0 — deterministic engine inputs (locked contract).'
 as
SELECT * FROM CORE.V_CASE_INPUTS;
create or replace view V_CASE_SCORE_CALC_V1(
	CASE_ID,
	SUBSCORE_CONTROLS,
	SUBSCORE_COVERAGE,
	SUBSCORE_SUMMARIES,
	LAST_ACTIVITY_AT,
	SCORE
) as
SELECT
  CASE_ID,

  100 * SUM(CONTROL_POINTS) / NULLIF(SUM(CONTROL_DENOM),0) AS SUBSCORE_CONTROLS,
  100 * AVG(COVERAGE_FLAG) AS SUBSCORE_COVERAGE,
  100 * AVG(SUMMARY_FLAG) AS SUBSCORE_SUMMARIES,
  MAX(LAST_TESTED_AT) AS LAST_ACTIVITY_AT,

  LEAST(100,
    (0.5 * (100 * SUM(CONTROL_POINTS) / NULLIF(SUM(CONTROL_DENOM),0)))
  + (0.2 * (100 * AVG(COVERAGE_FLAG)))
  + (0.15 * (100 * AVG(SUMMARY_FLAG)))
  + (0.15 * 
      CASE
        WHEN MAX(LAST_TESTED_AT) IS NULL THEN 0
        WHEN DATEDIFF('day',MAX(LAST_TESTED_AT),CURRENT_TIMESTAMP()) <= 90 THEN 100
        WHEN DATEDIFF('day',MAX(LAST_TESTED_AT),CURRENT_TIMESTAMP()) <= 180 THEN 75
        ELSE 40
      END
    )
  ) AS SCORE

FROM V_CASE_CONTROL_SCORE_CALC_V1
GROUP BY CASE_ID;
create or replace view V_CASE_SCORE_LATEST_V1(
	SNAPSHOT_ID,
	CASE_ID,
	MODEL_VERSION,
	SCORE,
	CREATED_AT
) as
SELECT *
FROM CASE_SCORES_V1
QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_ID ORDER BY CREATED_AT DESC)=1;
create or replace view V_CASE_SCORING(
	CASE_ID,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	FINAL_SCORE
) as
SELECT
  CASE_ID,
  CONTROLS_PCT,
  COVERAGE_PCT,
  FRESHNESS_PCT,
  SUMMARY_PCT,

  (CONTROLS_PCT * 0.40) +
  (COVERAGE_PCT * 0.25) +
  (FRESHNESS_PCT * 0.20) +
  (SUMMARY_PCT   * 0.15) AS FINAL_SCORE

FROM CORE.V_CASE_INPUTS
;
create or replace view V_CASE_SCORING_V1(
	CASE_ID,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	FINAL_SCORE
) COMMENT='GAFAIG Scoring Model v1.0 — weighted score output (locked contract).'
 as
SELECT * FROM CORE.V_CASE_SCORING;
create or replace view V_EVIDENCE_UI(
	EVIDENCE_ID,
	CASE_ID,
	PARTICIPANT_ID,
	FINDING_ID,
	FINDING_TITLE,
	EVIDENCE_TYPE,
	EVIDENCE_TITLE,
	DESCRIPTION,
	SOURCE_URL,
	STORAGE_REF,
	SUBMITTED_BY,
	SUBMITTED_AT,
	CREATED_AT,
	UPDATED_AT
) as
SELECT
  e.EVIDENCE_ID,
  e.CASE_ID,
  vc.PARTICIPANT_ID,

  fe.FINDING_ID,
  vf.CONTROL_TITLE AS FINDING_TITLE,

  e.EVIDENCE_TYPE,
  e.TITLE       AS EVIDENCE_TITLE,
  e.DESCRIPTION,

  e.SOURCE_URL,
  e.STORAGE_REF,

  e.SUBMITTED_BY,
  e.SUBMITTED_AT,
  e.CREATED_AT,
  e.UPDATED_AT
FROM CORE.VERIFICATION_EVIDENCE e
LEFT JOIN CORE.VERIFICATION_CASES vc
  ON vc.CASE_ID = e.CASE_ID
LEFT JOIN CORE.VERIFICATION_FINDING_EVIDENCE fe
  ON fe.EVIDENCE_ID = e.EVIDENCE_ID
LEFT JOIN CORE.VERIFICATION_FINDINGS vf
  ON vf.FINDING_ID = fe.FINDING_ID;
create or replace view V_GOVERNANCE_SCORE(
	CASE_ID,
	FINAL_SCORE,
	BAND,
	TIER,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT
) as
SELECT
  CASE_ID,
  FINAL_SCORE,

  CASE
    WHEN FINAL_SCORE >= 90 THEN 'A'
    WHEN FINAL_SCORE >= 80 THEN 'B'
    WHEN FINAL_SCORE >= 70 THEN 'C'
    ELSE 'D'
  END AS BAND,

  CASE
    WHEN FINAL_SCORE >= 80 THEN 'Standard Assurance'
    WHEN FINAL_SCORE >= 70 THEN 'Conditional'
    ELSE 'Not Verified'
  END AS TIER,

  CONTROLS_PCT,
  COVERAGE_PCT,
  FRESHNESS_PCT,
  SUMMARY_PCT

FROM CORE.V_CASE_SCORING
;
create or replace view V_GOVERNANCE_SCORE_CASE(
	CASE_ID,
	FINAL_SCORE,
	BAND,
	TIER,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT
) as
select
  case_id,
  final_score,
  band,
  tier,

  -- Optional score components (exist in your current scoring output per screenshot)
  controls_pct,
  coverage_pct,
  freshness_pct,
  summary_pct

from CORE.V_GOVERNANCE_SCORE;
create or replace view V_GOVERNANCE_SCORE_V1(
	CASE_ID,
	FINAL_SCORE,
	BAND,
	TIER,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT
) COMMENT='GAFAIG Scoring Model v1.0 — final score + band + tier (locked contract).'
 as
SELECT * FROM CORE.V_GOVERNANCE_SCORE;
create or replace view V_LATEST_PUBLISHED_SNAPSHOT_V1(
	SNAPSHOT_ID,
	CASE_ID,
	SCORING_MODEL_VERSION,
	SNAPSHOT_AT,
	TIER,
	BAND,
	FINAL_SCORE,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	FINDINGS_TOTAL,
	EVIDENCE_TOTAL,
	EVIDENCE_WITH_SUMMARY,
	LAST_ACTIVITY_AT
) as
SELECT
  s.*
FROM CORE.CASE_SCORE_SNAPSHOTS_V2 s
JOIN (
  SELECT
    CASE_ID,
    SCORING_MODEL_VERSION,
    MAX(SNAPSHOT_AT) AS MAX_SNAPSHOT_AT
  FROM CORE.CASE_SCORE_SNAPSHOTS_V2
  GROUP BY 1,2
) mx
  ON mx.CASE_ID = s.CASE_ID
 AND mx.SCORING_MODEL_VERSION = s.SCORING_MODEL_VERSION
 AND mx.MAX_SNAPSHOT_AT = s.SNAPSHOT_AT
;
create or replace view V_PUBLIC_REGISTRY(
	REGISTRY_RECORD_ID,
	ENTITY_NAME,
	ENTITY_TYPE,
	COUNTRY,
	CERTIFIED_TIER,
	CERTIFIED_BAND,
	CERTIFIED_SCORE,
	CERTIFIED_AT,
	DECISION_STATUS,
	VALID_FROM,
	VALID_TO,
	TOTAL_FINDINGS,
	TOTAL_EVIDENCE,
	TOTAL_EVENTS,
	LAST_ACTIVITY_AT
) as
SELECT
  -- Stable public record id (use application_id for now; later you can introduce a registry_id)
  application_id                         AS registry_record_id,

  -- Public-facing entity fields
  COALESCE(entity_name, org_name)        AS entity_name,
  COALESCE(entity_type, org_type)        AS entity_type,
  COALESCE(participant_country, country) AS country,

  -- Public certification (prefer decision outputs; fall back to score snapshot if available)
  COALESCE(certification_tier, scored_tier) AS certified_tier,
  COALESCE(certification_band, scored_band) AS certified_band,
  total_score                               AS certified_score,
  scored_at                                 AS certified_at,

  -- Public validity (only meaningful when a decision exists)
  decision_status,
  valid_from,
  valid_to,

  -- Minimal auditability / transparency fields (safe)
  total_findings,
  total_evidence,
  total_events,
  last_activity_at

FROM CORE.V_VERIFICATION_CASE_DETAIL
WHERE
  -- “Approved” logic:
  (
    -- If a decision exists, use decision_status as truth
    (decision_status IS NOT NULL AND LOWER(decision_status) = 'approved')
    OR
    -- If no decision exists yet, allow approved applications to appear
    (decision_status IS NULL AND LOWER(application_status) = 'approved')
  )
  AND
  -- Validity window only enforced when a decision exists
  (
    decision_status IS NULL
    OR (
      (valid_from IS NULL OR valid_from <= CURRENT_TIMESTAMP())
      AND (valid_to   IS NULL OR valid_to   >  CURRENT_TIMESTAMP())
    )
  )
;
create or replace view V_PUBLIC_REGISTRY_CASES_V1(
	ORG_ID,
	CASE_ID,
	STANDARD_CODE,
	STANDARD_VERSION,
	CASE_STATUS,
	APPROVED_AT,
	APPROVED_BY,
	SCORING_MODEL_VERSION,
	SNAPSHOT_AT,
	TIER,
	BAND,
	FINAL_SCORE,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	LAST_ACTIVITY_AT
) as
WITH latest_approve AS (
  SELECT
    CASE_ID,
    ACTOR        AS APPROVED_BY,
    ACTION_AT    AS APPROVED_AT,
    NOTES        AS APPROVAL_NOTES
  FROM CORE.CASE_APPROVAL_LOG
  WHERE ACTION = 'APPROVE'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_ID ORDER BY ACTION_AT DESC) = 1
),
latest_score_snapshot AS (
  SELECT
    CASE_ID,
    SCORING_MODEL_VERSION,
    SNAPSHOT_AT,
    TIER,
    BAND,
    FINAL_SCORE,
    CONTROLS_PCT,
    COVERAGE_PCT,
    FRESHNESS_PCT,
    SUMMARY_PCT,
    LAST_ACTIVITY_AT
  FROM CORE.CASE_SCORE_SNAPSHOTS_V2
  WHERE SNAPSHOT_ACTION = 'APPROVE'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_ID ORDER BY SNAPSHOT_AT DESC) = 1
)
SELECT
  c.ORG_ID,
  c.CASE_ID,
  c.STANDARD_CODE,
  c.STANDARD_VERSION,
  c.STATUS                              AS CASE_STATUS,

  a.APPROVED_AT,
  a.APPROVED_BY,

  s.SCORING_MODEL_VERSION,
  s.SNAPSHOT_AT,
  s.TIER,
  s.BAND,
  s.FINAL_SCORE,
  s.CONTROLS_PCT,
  s.COVERAGE_PCT,
  s.FRESHNESS_PCT,
  s.SUMMARY_PCT,
  s.LAST_ACTIVITY_AT

FROM CORE.VERIFICATION_CASES c
JOIN latest_approve a
  ON a.CASE_ID = c.CASE_ID
LEFT JOIN latest_score_snapshot s
  ON s.CASE_ID = c.CASE_ID
WHERE UPPER(c.STATUS) = 'APPROVED';
create or replace view V_REGISTRY_AI_SYSTEMS_BY_REGISTRY(
	SYSTEM_ID,
	REGISTRY_ID,
	SYSTEM_NAME,
	SYSTEM_TYPE,
	INTENDED_USE,
	DEPLOYMENT_STATUS,
	OVERSIGHT_LEVEL,
	RISK_TIER,
	PUBLIC_SUMMARY,
	DISPLAY_ORDER
) as
SELECT
    SYSTEM_ID,
    REGISTRY_ID,
    SYSTEM_NAME,
    SYSTEM_TYPE,
    INTENDED_USE,
    DEPLOYMENT_STATUS,
    OVERSIGHT_LEVEL,
    RISK_TIER,
    PUBLIC_SUMMARY,
    DISPLAY_ORDER
FROM CORE.REGISTRY_AI_SYSTEMS
WHERE REGISTRY_ID IS NOT NULL
ORDER BY DISPLAY_ORDER NULLS LAST, SYSTEM_NAME;
create or replace view V_REGISTRY_AI_SYSTEMS_PUBLIC(
	SYSTEM_ID,
	REGISTRY_ID,
	SYSTEM_NAME,
	SYSTEM_TYPE,
	INTENDED_USE,
	DEPLOYMENT_STATUS,
	OVERSIGHT_LEVEL,
	RISK_TIER,
	PUBLIC_SUMMARY,
	DISPLAY_ORDER
) as
SELECT
    SYSTEM_ID,
    REGISTRY_ID,
    SYSTEM_NAME,
    SYSTEM_TYPE,
    INTENDED_USE,
    DEPLOYMENT_STATUS,
    OVERSIGHT_LEVEL,
    RISK_TIER,
    PUBLIC_SUMMARY,
    DISPLAY_ORDER
FROM GAFAIG_DB.CORE.REGISTRY_AI_SYSTEMS
WHERE REGISTRY_ID IS NOT NULL;
create or replace view V_REGISTRY_CASES_V1(
	CASE_ID,
	ORG_ID,
	PARTICIPANT_ID,
	STANDARD_CODE,
	STANDARD_VERSION,
	CASE_STATUS,
	FINAL_SCORE,
	BAND,
	TIER,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	FINDINGS_TOTAL,
	FINDINGS_SCORED,
	FINDINGS_NA,
	FINDINGS_WITH_EVIDENCE,
	EVIDENCE_TOTAL,
	EVIDENCE_WITH_SUMMARY,
	NEWEST_VALID_EVIDENCE_AT,
	LAST_ACTIVITY_AT
) COMMENT='GAFAIG Registry v1.0 — per-case public-ish summary built on Scoring Model v1.0.'
 as
WITH
-- Findings per case
F AS (
  SELECT
    CASE_ID,
    COUNT(*)                                          AS FINDINGS_TOTAL,
    SUM(IFF(UPPER(RESULT) IN ('PASS','FAIL'), 1, 0))   AS FINDINGS_SCORED,
    SUM(IFF(UPPER(RESULT) = 'NA', 1, 0))               AS FINDINGS_NA,
    MAX(COALESCE(UPDATED_AT, CREATED_AT))              AS FINDINGS_LAST_AT
  FROM CORE.VERIFICATION_FINDINGS
  GROUP BY CASE_ID
),

-- Evidence mapped to findings (junction)
FE AS (
  SELECT
    CASE_ID,
    COUNT(*)                         AS FINDING_EVIDENCE_LINKS,
    COUNT(DISTINCT FINDING_ID)       AS FINDINGS_WITH_EVIDENCE,
    COUNT(DISTINCT EVIDENCE_ID)      AS EVIDENCE_MAPPED_DISTINCT,
    MAX(CREATED_AT)                  AS MAP_LAST_AT
  FROM CORE.FINDING_EVIDENCE_MAP
  GROUP BY CASE_ID
),

-- Evidence per case (from VERIFICATION_EVIDENCE)
E AS (
  SELECT
    CASE_ID,
    COUNT(*)                                              AS EVIDENCE_TOTAL,
    COUNT(DISTINCT EVIDENCE_ID)                           AS EVIDENCE_DISTINCT,
    MAX(COALESCE(SUBMITTED_AT, CREATED_AT))               AS EVIDENCE_LAST_AT,
    MAX(COALESCE(SUBMITTED_AT, CREATED_AT))               AS NEWEST_EVIDENCE_AT
  FROM CORE.VERIFICATION_EVIDENCE
  GROUP BY CASE_ID
),

-- Evidence summaries (non-empty) per case
ES AS (
  SELECT
    e.CASE_ID,
    COUNT(*) AS EVIDENCE_WITH_SUMMARY,
    MAX(s.UPDATED_AT) AS SUMMARY_LAST_AT
  FROM CORE.VERIFICATION_EVIDENCE e
  JOIN CORE.EVIDENCE_SUMMARIES s
    ON s.EVIDENCE_ID = e.EVIDENCE_ID
  WHERE LENGTH(TRIM(COALESCE(s.SUMMARY,''))) > 0
  GROUP BY e.CASE_ID
),

-- "Valid evidence" for freshness: evidence that is BOTH
-- (a) mapped to a finding, and (b) has a non-empty summary
NV AS (
  SELECT
    m.CASE_ID,
    MAX(COALESCE(e.SUBMITTED_AT, e.CREATED_AT)) AS NEWEST_VALID_EVIDENCE_AT
  FROM CORE.FINDING_EVIDENCE_MAP m
  JOIN CORE.VERIFICATION_EVIDENCE e
    ON e.CASE_ID = m.CASE_ID
   AND e.EVIDENCE_ID = m.EVIDENCE_ID
  JOIN CORE.EVIDENCE_SUMMARIES s
    ON s.EVIDENCE_ID = e.EVIDENCE_ID
  WHERE LENGTH(TRIM(COALESCE(s.SUMMARY,''))) > 0
  GROUP BY m.CASE_ID
)

SELECT
  c.CASE_ID,
  c.ORG_ID,
  c.PARTICIPANT_ID,
  c.STANDARD_CODE,
  c.STANDARD_VERSION,
  c.STATUS                         AS CASE_STATUS,

  -- v1.0 score outputs (locked contract)
  gs.FINAL_SCORE,
  gs.BAND,
  gs.TIER,
  gs.CONTROLS_PCT,
  gs.COVERAGE_PCT,
  gs.FRESHNESS_PCT,
  gs.SUMMARY_PCT,

  -- Counts / auditability signals
  COALESCE(f.FINDINGS_TOTAL, 0)            AS FINDINGS_TOTAL,
  COALESCE(f.FINDINGS_SCORED, 0)           AS FINDINGS_SCORED,
  COALESCE(f.FINDINGS_NA, 0)               AS FINDINGS_NA,
  COALESCE(fe.FINDINGS_WITH_EVIDENCE, 0)   AS FINDINGS_WITH_EVIDENCE,

  COALESCE(e.EVIDENCE_TOTAL, 0)            AS EVIDENCE_TOTAL,
  COALESCE(es.EVIDENCE_WITH_SUMMARY, 0)    AS EVIDENCE_WITH_SUMMARY,

  -- Freshness anchor
  nv.NEWEST_VALID_EVIDENCE_AT,

  -- Last activity (best-effort)
  GREATEST(
    COALESCE(c.UPDATED_AT, c.CREATED_AT),
    COALESCE(f.FINDINGS_LAST_AT, TO_TIMESTAMP_NTZ('1970-01-01')),
    COALESCE(fe.MAP_LAST_AT,      TO_TIMESTAMP_NTZ('1970-01-01')),
    COALESCE(e.EVIDENCE_LAST_AT,  TO_TIMESTAMP_NTZ('1970-01-01')),
    COALESCE(es.SUMMARY_LAST_AT,  TO_TIMESTAMP_NTZ('1970-01-01'))
  ) AS LAST_ACTIVITY_AT

FROM CORE.VERIFICATION_CASES c
LEFT JOIN CORE.V_GOVERNANCE_SCORE_V1 gs
  ON gs.CASE_ID = c.CASE_ID
LEFT JOIN F  f  ON f.CASE_ID  = c.CASE_ID
LEFT JOIN FE fe ON fe.CASE_ID = c.CASE_ID
LEFT JOIN E  e  ON e.CASE_ID  = c.CASE_ID
LEFT JOIN ES es ON es.CASE_ID = c.CASE_ID
LEFT JOIN NV nv ON nv.CASE_ID = c.CASE_ID
;
create or replace view V_REGISTRY_EXPORT_V1(
	ORG_ID,
	CASE_ID,
	STANDARD_CODE,
	STANDARD_VERSION,
	CASE_STATUS,
	APPROVED_AT,
	APPROVED_BY,
	SCORING_MODEL_VERSION,
	SNAPSHOT_AT,
	TIER,
	BAND,
	FINAL_SCORE,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	LAST_ACTIVITY_AT
) as
SELECT *
FROM CORE.V_PUBLIC_REGISTRY_CASES_V1;
create or replace view V_REGISTRY_LATEST_APPROVED(
	SNAPSHOT_ID,
	CASE_ID,
	ORG_ID,
	STANDARD_CODE,
	STANDARD_VERSION,
	FINAL_SCORE,
	TIER,
	BAND,
	SUBSCORES,
	COUNTS,
	CASE_STATUS,
	LAST_ACTIVITY_AT,
	APPROVED_AT,
	APPROVED_BY,
	SOURCE_VIEW,
	SOURCE_HASH,
	PAYLOAD,
	CREATED_AT,
	RN
) as
WITH ranked AS (
  SELECT
    s.*,
    ROW_NUMBER() OVER (
      PARTITION BY s.case_id
      ORDER BY s.approved_at DESC, s.created_at DESC
    ) AS rn
  FROM CORE.REGISTRY_SNAPSHOTS s
  WHERE UPPER(s.case_status) = 'APPROVED'
)
SELECT *
FROM ranked
WHERE rn = 1;
create or replace view V_REGISTRY_PUBLIC(
	REGISTRY_ID,
	APPLICATION_ID,
	ENTITY_NAME,
	ENTITY_TYPE,
	COUNTRY,
	CERTIFIED_TIER,
	CERTIFIED_BAND,
	VALID_FROM,
	VALID_TO,
	DECISION_STATUS,
	CERTIFIED_AT,
	LAST_ACTIVITY_AT
) as
SELECT
  re.registry_id                                  AS registry_id,
  v.application_id                                AS application_id,

  -- Entity (prefer registry identity; fallback to application surface)
  COALESCE(re.entity_name, v.org_name)            AS entity_name,
  re.entity_type                                  AS entity_type,
  re.country                                      AS country,

  -- Certification outcome
  v.certification_tier                            AS certified_tier,
  v.certification_band                            AS certified_band,
  v.valid_from                                    AS valid_from,
  v.valid_to                                      AS valid_to,
  v.decision_status                               AS decision_status,

  -- Useful public metadata
  v.certified_at                                  AS certified_at,
  v.last_activity_at                              AS last_activity_at

FROM CORE.REGISTRY_ENTITIES re
JOIN CORE.V_VERIFICATION_CASE_DETAIL v
  ON v.application_id = re.application_id

WHERE
  LOWER(v.decision_status) = 'approved'
  AND (v.valid_from IS NULL OR v.valid_from <= CURRENT_TIMESTAMP())
  AND (v.valid_to   IS NULL OR v.valid_to   >  CURRENT_TIMESTAMP())
;
create or replace view V_REGISTRY_PUBLIC_SEARCH(
	REGISTRY_ID,
	APPLICATION_ID,
	ENTITY_NAME,
	ENTITY_TYPE,
	COUNTRY,
	CERTIFIED_TIER,
	CERTIFIED_BAND,
	VALID_FROM,
	VALID_TO,
	DECISION_STATUS,
	CERTIFIED_AT,
	LAST_ACTIVITY_AT,
	REGISTRY_ID_NORM,
	ENTITY_NAME_NORM,
	COUNTRY_NORM,
	Q
) as
SELECT
  registry_id,
  application_id,

  entity_name,
  entity_type,
  country,

  certified_tier,
  certified_band,
  valid_from,
  valid_to,
  decision_status,

  certified_at,
  last_activity_at,

  -- Normalized fields for UI filtering/search
  UPPER(TRIM(registry_id))                         AS registry_id_norm,
  UPPER(TRIM(COALESCE(entity_name, '')))           AS entity_name_norm,
  UPPER(TRIM(COALESCE(country, '')))               AS country_norm,

  -- Single search blob (simple + effective)
  UPPER(
    TRIM(COALESCE(registry_id, '')) || ' ' ||
    TRIM(COALESCE(entity_name, '')) || ' ' ||
    TRIM(COALESCE(country, ''))     || ' ' ||
    TRIM(COALESCE(entity_type, ''))
  )                                                AS q

FROM CORE.V_REGISTRY_PUBLIC
;
create or replace view V_SCORE_FOR_SNAPSHOT_V1(
	CASE_ID,
	SCORING_MODEL_VERSION,
	TIER,
	BAND,
	FINAL_SCORE,
	CONTROLS_PCT,
	COVERAGE_PCT,
	FRESHNESS_PCT,
	SUMMARY_PCT,
	FINDINGS_TOTAL,
	EVIDENCE_TOTAL,
	EVIDENCE_WITH_SUMMARY,
	LAST_ACTIVITY_AT
) as
SELECT
  s.CASE_ID,
  s.SCORING_MODEL_VERSION,
  s.TIER,
  s.BAND,
  s.FINAL_SCORE,
  s.CONTROLS_PCT,
  s.COVERAGE_PCT,
  s.FRESHNESS_PCT,
  s.SUMMARY_PCT,
  s.FINDINGS_TOTAL,
  s.EVIDENCE_TOTAL,
  s.EVIDENCE_WITH_SUMMARY,
  s.LAST_ACTIVITY_AT
FROM CORE.CASE_SCORE_SNAPSHOTS_V2 s
WHERE s.SCORING_MODEL_VERSION = 'GAFAIG Scoring Model v1.0'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY s.CASE_ID, s.SCORING_MODEL_VERSION
  ORDER BY s.SNAPSHOT_AT DESC
) = 1
;
create or replace view V_VERIFICATION_CASE_DETAIL(
	APPLICATION_ID,
	REQUEST_ID,
	ORG_NAME,
	APPLICATION_STATUS,
	SUBMISSION_TYPE,
	CONTACT_EMAIL,
	SUBMISSION_STATUS,
	SUBMISSION_CREATED_AT,
	SNAPSHOT_ID,
	TOTAL_SCORE,
	SCORE_TIER,
	SCORE_CALCULATED_AT,
	DECISION_ID,
	DECISION_STATUS,
	CERTIFICATION_TIER,
	CERTIFICATION_BAND,
	VALID_FROM,
	VALID_TO,
	DECISION_CREATED_AT,
	CERTIFIED_AT,
	LAST_ACTIVITY_AT,
	TOTAL_FINDINGS,
	TOTAL_EVIDENCE,
	TOTAL_EVENTS
) as
WITH
latest_snapshot AS (
  SELECT
    css.*,
    ROW_NUMBER() OVER (
      PARTITION BY css.application_id
      ORDER BY css.calculated_at DESC NULLS LAST
    ) AS rn
  FROM CORE.CASE_SCORE_SNAPSHOTS css
),
latest_decision AS (
  SELECT
    d.*,
    ROW_NUMBER() OVER (
      PARTITION BY d.application_id
      ORDER BY d.created_at DESC NULLS LAST
    ) AS rn
  FROM CORE.DECISIONS d
),
finding_counts AS (
  SELECT
    f.application_id,
    COUNT(*) AS total_findings
  FROM CORE.FINDINGS f
  GROUP BY f.application_id
),
evidence_counts AS (
  SELECT
    f.application_id,
    COUNT(e.evidence_id) AS total_evidence
  FROM CORE.FINDINGS f
  LEFT JOIN CORE.EVIDENCE e
    ON e.finding_id = f.finding_id
  GROUP BY f.application_id
),
event_counts AS (
  SELECT
    ev.application_id,
    COUNT(*) AS total_events
  FROM CORE.EVENTS ev
  GROUP BY ev.application_id
)

SELECT
  -- Identity
  a.application_id                                           AS application_id,
  a.request_id                                               AS request_id,

  -- Application surface
  a.org_name                                                 AS org_name,
  a.status                                                   AS application_status,

  -- Submissions (best-effort: your SUBMISSIONS table uses REQUEST_ID)
  s.submission_type                                          AS submission_type,
  s.contact_email                                            AS contact_email,
  s.status                                                   AS submission_status,
  s.created_at                                               AS submission_created_at,

  -- Latest score snapshot (if any)
  ls.snapshot_id                                             AS snapshot_id,
  ls.total_score                                             AS total_score,
  ls.tier                                                    AS score_tier,
  ls.calculated_at                                           AS score_calculated_at,

  -- Latest decision (if any)
  d.decision_id                                              AS decision_id,
  d.decision_status                                          AS decision_status,
  d.certification_tier                                       AS certification_tier,
  d.certification_band                                       AS certification_band,
  d.valid_from                                               AS valid_from,
  d.valid_to                                                 AS valid_to,
  d.created_at                                               AS decision_created_at,

  -- This powers the public registry ordering
  d.created_at                                               AS certified_at,

  -- Last activity (max across key timestamps we have)
  GREATEST(
    COALESCE(d.created_at,        '1970-01-01'::timestamp),
    COALESCE(ls.calculated_at,    '1970-01-01'::timestamp),
    COALESCE(s.created_at,        '1970-01-01'::timestamp)
  )                                                          AS last_activity_at,

  -- Counts (for admin dashboards / QA)
  COALESCE(fc.total_findings, 0)                             AS total_findings,
  COALESCE(ec.total_evidence, 0)                             AS total_evidence,
  COALESCE(ev.total_events,   0)                             AS total_events

FROM CORE.APPLICATIONS a

-- submissions join on REQUEST_ID (your earlier diagnostics show this matches)
LEFT JOIN CORE.SUBMISSIONS s
  ON s.request_id = a.request_id

LEFT JOIN latest_snapshot ls
  ON ls.application_id = a.application_id
 AND ls.rn = 1

LEFT JOIN latest_decision d
  ON d.application_id = a.application_id
 AND d.rn = 1

LEFT JOIN finding_counts fc
  ON fc.application_id = a.application_id

LEFT JOIN evidence_counts ec
  ON ec.application_id = a.application_id

LEFT JOIN event_counts ev
  ON ev.application_id = a.application_id
;
CREATE OR REPLACE PROCEDURE "APPROVE_CASE_V1"("P_CASE_ID" VARCHAR, "P_ACTOR" VARCHAR, "P_NOTES" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ACTOR STRING;
  V_NOTES STRING;
  V_EXISTS NUMBER;
BEGIN
  V_ACTOR := COALESCE(P_ACTOR, CURRENT_USER());
  V_NOTES := COALESCE(P_NOTES, ''Initial public registry publish'');

  SELECT COUNT(*)
    INTO :V_EXISTS
  FROM CORE.VERIFICATION_CASES
  WHERE CASE_ID = :P_CASE_ID;

  IF (:V_EXISTS = 0) THEN
    RETURN OBJECT_CONSTRUCT(
      ''ok'', FALSE,
      ''error'', ''Case not found'',
      ''caseId'', P_CASE_ID
    );
  END IF;

  UPDATE CORE.VERIFICATION_CASES
     SET STATUS = ''approved''
   WHERE CASE_ID = :P_CASE_ID;

  -- IMPORTANT: use INSERT...SELECT (avoids UUID_STRING() in VALUES issues)
  INSERT INTO CORE.CASE_APPROVAL_LOG (LOG_ID, CASE_ID, ACTION, ACTOR, ACTION_AT, NOTES)
  SELECT
    UUID_STRING(),
    :P_CASE_ID,
    ''APPROVE'',
    :V_ACTOR,
    CURRENT_TIMESTAMP(),
    :V_NOTES;

  RETURN OBJECT_CONSTRUCT(
    ''ok'', TRUE,
    ''caseId'', P_CASE_ID,
    ''actor'', V_ACTOR,
    ''notes'', V_NOTES
  );
END;
';
CREATE OR REPLACE FUNCTION "CURRENT_ORG_ID"()
RETURNS VARCHAR
LANGUAGE SQL
AS '
  (SELECT ORG_ID
   FROM CORE.USER_ORG_ACCESS
   WHERE USERNAME = CURRENT_USER()
   QUALIFY ROW_NUMBER() OVER (ORDER BY ORG_ID) = 1)
';
CREATE OR REPLACE PROCEDURE "SP_CREATE_CASE"("P_CASE_ID" VARCHAR, "P_PARTICIPANT_ID" VARCHAR, "P_STATUS" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ORG STRING;
BEGIN
  LET V_ORG := CORE.CURRENT_ORG_ID();

  IF (V_ORG IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''No ORG mapping for user'', ''user'', CURRENT_USER());
  END IF;

  INSERT INTO CORE.VERIFICATION_CASES (CASE_ID, PARTICIPANT_ID, ORG_ID, STATUS)
  VALUES (P_CASE_ID, P_PARTICIPANT_ID, V_ORG, P_STATUS);

  RETURN OBJECT_CONSTRUCT(''ok'', TRUE, ''caseId'', P_CASE_ID, ''orgId'', V_ORG);
END;
';
CREATE OR REPLACE PROCEDURE "SP_CREATE_EVIDENCE"("P_EVIDENCE_ID" VARCHAR, "P_CASE_ID" VARCHAR, "P_EVIDENCE_TYPE" VARCHAR, "P_TITLE" VARCHAR, "P_DESCRIPTION" VARCHAR, "P_SOURCE_URL" VARCHAR, "P_STORAGE_REF" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ORG STRING;
  V_OK INTEGER;
BEGIN
  LET V_ORG := CORE.CURRENT_ORG_ID();

  IF (V_ORG IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''No ORG mapping for user'');
  END IF;

  -- Ensure case belongs to caller org
  SELECT COUNT(*) INTO :V_OK
  FROM CORE.VERIFICATION_CASES
  WHERE CASE_ID = P_CASE_ID
    AND ORG_ID = V_ORG;

  IF (V_OK = 0) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''Case not found in org'');
  END IF;

  INSERT INTO CORE.VERIFICATION_EVIDENCE
  (
    EVIDENCE_ID,
    CASE_ID,
    ORG_ID,
    EVIDENCE_TYPE,
    TITLE,
    DESCRIPTION,
    SOURCE_URL,
    STORAGE_REF,
    SUBMITTED_BY,
    SUBMITTED_AT,
    CREATED_AT
  )
  VALUES
  (
    P_EVIDENCE_ID,
    P_CASE_ID,
    V_ORG,
    P_EVIDENCE_TYPE,
    P_TITLE,
    P_DESCRIPTION,
    P_SOURCE_URL,
    P_STORAGE_REF,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
  );

  RETURN OBJECT_CONSTRUCT(''ok'', TRUE, ''evidenceId'', P_EVIDENCE_ID, ''orgId'', V_ORG);
END;
';
CREATE OR REPLACE PROCEDURE "SP_CREATE_EVIDENCE"("P_EVIDENCE_ID" VARCHAR, "P_EVIDENCE_TYPE" VARCHAR, "P_TITLE" VARCHAR, "P_DESCRIPTION" VARCHAR, "P_SOURCE_URL" VARCHAR, "P_STORAGE_REF" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ORG STRING;
BEGIN
  LET V_ORG := CORE.CURRENT_ORG_ID();

  IF (V_ORG IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''No ORG mapping for user'', ''user'', CURRENT_USER());
  END IF;

  INSERT INTO CORE.VERIFICATION_EVIDENCE
    (EVIDENCE_ID, ORG_ID, EVIDENCE_TYPE, TITLE, DESCRIPTION, SOURCE_URL, STORAGE_REF, CREATED_AT)
  VALUES
    (P_EVIDENCE_ID, V_ORG, P_EVIDENCE_TYPE, P_TITLE, P_DESCRIPTION, P_SOURCE_URL, P_STORAGE_REF, CURRENT_TIMESTAMP());

  RETURN OBJECT_CONSTRUCT(''ok'', TRUE, ''evidenceId'', P_EVIDENCE_ID, ''orgId'', V_ORG);
END;
';
CREATE OR REPLACE PROCEDURE "SP_LINK_FINDING_EVIDENCE"("P_FINDING_ID" VARCHAR, "P_EVIDENCE_ID" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ORG STRING;
  V_OK INTEGER;
BEGIN
  LET V_ORG := CORE.CURRENT_ORG_ID();

  IF (V_ORG IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''No ORG mapping for user'', ''user'', CURRENT_USER());
  END IF;

  -- verify finding is in same org
  SELECT COUNT(*) INTO :V_OK
  FROM CORE.VERIFICATION_FINDINGS
  WHERE FINDING_ID = P_FINDING_ID
    AND ORG_ID = V_ORG;

  IF (V_OK = 0) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''Finding not found in org'', ''findingId'', P_FINDING_ID, ''orgId'', V_ORG);
  END IF;

  -- verify evidence is in same org
  SELECT COUNT(*) INTO :V_OK
  FROM CORE.VERIFICATION_EVIDENCE
  WHERE EVIDENCE_ID = P_EVIDENCE_ID
    AND ORG_ID = V_ORG;

  IF (V_OK = 0) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''Evidence not found in org'', ''evidenceId'', P_EVIDENCE_ID, ''orgId'', V_ORG);
  END IF;

  -- insert link (idempotent pattern optional; keeping simple)
  INSERT INTO CORE.VERIFICATION_FINDING_EVIDENCE (FINDING_ID, EVIDENCE_ID, ORG_ID, CREATED_AT)
  VALUES (P_FINDING_ID, P_EVIDENCE_ID, V_ORG, CURRENT_TIMESTAMP());

  RETURN OBJECT_CONSTRUCT(''ok'', TRUE, ''findingId'', P_FINDING_ID, ''evidenceId'', P_EVIDENCE_ID, ''orgId'', V_ORG);
END;
';
CREATE OR REPLACE PROCEDURE "SP_PUBLISH_CASE_TO_REGISTRY_V3"("CASE_ID_IN" VARCHAR, "APPROVED_BY_IN" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  v_case_id           VARCHAR;
  v_snapshot_id       VARCHAR;
  v_final_score       NUMBER(10,4);
  v_tier              VARCHAR;
  v_band              VARCHAR;

  v_controls_pct      NUMBER(10,4);
  v_coverage_pct      NUMBER(10,4);
  v_freshness_pct     NUMBER(10,4);
  v_summary_pct       NUMBER(10,4);

  v_subscores         VARIANT;
  v_counts            VARIANT;
  v_payload           VARIANT;

BEGIN
  v_case_id := CASE_ID_IN;

  -- Pull latest score for this case
  SELECT
    case_id,
    final_score,
    tier,
    band,
    controls_pct,
    coverage_pct,
    freshness_pct,
    summary_pct
  INTO
    v_case_id,
    v_final_score,
    v_tier,
    v_band,
    v_controls_pct,
    v_coverage_pct,
    v_freshness_pct,
    v_summary_pct
  FROM CORE.V_GOVERNANCE_SCORE_CASE
  WHERE case_id = :v_case_id;   -- ✅ bind var

  -- Snapshot id
  v_snapshot_id := ''SNP-'' || REPLACE(UUID_STRING(), ''-'', '''');

  -- Minimal structured payloads (variants)
  v_subscores := OBJECT_CONSTRUCT(
    ''controls'',  v_controls_pct,
    ''coverage'',  v_coverage_pct,
    ''freshness'', v_freshness_pct,
    ''summaries'', v_summary_pct
  );

  v_counts := OBJECT_CONSTRUCT(
    ''findingsTotal'', NULL,
    ''evidenceTotal'', NULL
  );

  v_payload := OBJECT_CONSTRUCT(
    ''caseId'', v_case_id,
    ''tier'', v_tier,
    ''band'', v_band,
    ''finalScore'', v_final_score,
    ''subscores'', v_subscores,
    ''counts'', v_counts
  );

  -- ✅ IMPORTANT FIX:
  -- Use INSERT ... SELECT (not VALUES) to avoid VARIANT bind compilation issues.
  INSERT INTO CORE.REGISTRY_SNAPSHOTS (
    SNAPSHOT_ID,
    CASE_ID,
    ORG_ID,
    STANDARD_CODE,
    STANDARD_VERSION,
    FINAL_SCORE,
    TIER,
    BAND,
    SUBSCORES,
    COUNTS,
    CASE_STATUS,
    LAST_ACTIVITY_AT,
    APPROVED_AT,
    APPROVED_BY,
    SOURCE_VIEW,
    SOURCE_HASH,
    PAYLOAD,
    CREATED_AT
  )
  SELECT
    :v_snapshot_id,
    :v_case_id,
    NULL,                     -- ORG_ID (optional)
    NULL,                     -- STANDARD_CODE (optional)
    NULL,                     -- STANDARD_VERSION (optional)
    :v_final_score,
    :v_tier,
    :v_band,
    :v_subscores,
    :v_counts,
    ''APPROVED'',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    :APPROVED_BY_IN,          -- bind param
    ''CORE.V_GOVERNANCE_SCORE_CASE'',
    SHA2(TO_VARCHAR(:v_payload), 256),
    :v_payload,
    CURRENT_TIMESTAMP();

  RETURN OBJECT_CONSTRUCT(
    ''ok'', TRUE,
    ''caseId'', :v_case_id,
    ''snapshotId'', :v_snapshot_id,
    ''finalScore'', :v_final_score,
    ''tier'', :v_tier,
    ''band'', :v_band
  );
END;
';
CREATE OR REPLACE PROCEDURE "SP_PUBLISH_CASE_TO_REGISTRY_V4"("CASE_ID_IN" VARCHAR, "APPROVED_BY_IN" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
declare
  v_now timestamp_ntz;
  v_snapshot_id string;

  v_case_id string;
  v_org_id string;
  v_standard_code string;
  v_standard_version string;
  v_case_status string;
  v_last_activity_at timestamp_ntz;

  v_controls number(35,9);
  v_coverage number(22,6);
  v_freshness float;
  v_summaries number(22,6);

  v_findings_total number(18,0);
  v_findings_scored number(13,0);
  v_findings_na number(13,0);
  v_findings_with_evidence number(13,0);
  v_evidence_total number(18,0);
  v_evidence_with_summary number(13,0);

  v_final_score float;
  v_tier string;
  v_band string;

  v_subscores variant;
  v_counts variant;
  v_payload variant;
begin
  v_now := current_timestamp();
  v_snapshot_id := ''SNP-'' || to_varchar(date_part(epoch_second, v_now)) || ''-'' || substr(uuid_string(), 1, 8);

  -- Pull the scoring row (single row)
  select
    case_id,
    participant_id,
    standard_code,
    standard_version,
    case_status,
    last_activity_at,
    controls_score,
    coverage_score,
    freshness_score,
    summaries_score,
    findings_total,
    findings_scored,
    findings_na,
    findings_with_evidence,
    evidence_total,
    evidence_with_summary,
    governance_score
  into
    :v_case_id,
    :v_org_id,
    :v_standard_code,
    :v_standard_version,
    :v_case_status,
    :v_last_activity_at,
    :v_controls,
    :v_coverage,
    :v_freshness,
    :v_summaries,
    :v_findings_total,
    :v_findings_scored,
    :v_findings_na,
    :v_findings_with_evidence,
    :v_evidence_total,
    :v_evidence_with_summary,
    :v_final_score
  from GAFAIG_DB.CORE.V_GOVERNANCE_SCORE_CASE
  where case_id = :CASE_ID_IN;

  if (v_case_id is null) then
    return object_construct(
      ''ok'', false,
      ''error'', ''Case not found in V_GOVERNANCE_SCORE_CASE'',
      ''caseId'', CASE_ID_IN
    );
  end if;

  -- Deterministic tier/band mapping (canonical)
  if (v_final_score >= 90) then
    v_tier := ''High Assurance''; v_band := ''A'';
  elseif (v_final_score >= 75) then
    v_tier := ''Standard Assurance''; v_band := ''B'';
  elseif (v_final_score >= 60) then
    v_tier := ''Conditional''; v_band := ''C'';
  else
    v_tier := ''Not Verified''; v_band := ''D'';
  end if;

  -- Build VARIANT objects (NO PARSE_JSON — we already have native types)
  v_subscores := object_construct(
    ''controls'', v_controls,
    ''coverage'', v_coverage,
    ''freshness'', v_freshness,
    ''summaries'', v_summaries
  );

  v_counts := object_construct(
    ''findingsTotal'', v_findings_total,
    ''findingsScored'', v_findings_scored,
    ''findingsNA'', v_findings_na,
    ''findingsWithEvidence'', v_findings_with_evidence,
    ''evidenceTotal'', v_evidence_total,
    ''evidenceWithSummary'', v_evidence_with_summary
  );

  v_payload := object_construct(
    ''caseId'', v_case_id,
    ''orgId'', v_org_id,
    ''standard'', object_construct(''code'', v_standard_code, ''version'', v_standard_version),
    ''caseStatus'', v_case_status,
    ''tier'', v_tier,
    ''band'', v_band,
    ''finalScore'', v_final_score,
    ''subscores'', v_subscores,
    ''counts'', v_counts,
    ''lastActivityAt'', v_last_activity_at
  );

  -- Insert snapshot (IMPORTANT: insert VARIANT variables directly)
  insert into GAFAIG_DB.CORE.REGISTRY_SNAPSHOTS (
    SNAPSHOT_ID,
    CASE_ID,
    ORG_ID,
    STANDARD_CODE,
    STANDARD_VERSION,
    FINAL_SCORE,
    TIER,
    BAND,
    SUBSCORES,
    COUNTS,
    CASE_STATUS,
    LAST_ACTIVITY_AT,
    APPROVED_AT,
    APPROVED_BY,
    SOURCE_VIEW,
    SOURCE_HASH,
    PAYLOAD,
    CREATED_AT
  )
  values (
    :v_snapshot_id,
    :v_case_id,
    :v_org_id,
    :v_standard_code,
    :v_standard_version,
    :v_final_score::number(10,4),
    :v_tier,
    :v_band,
    :v_subscores,
    :v_counts,
    :v_case_status,
    :v_last_activity_at,
    :v_now,
    :APPROVED_BY_IN,
    ''CORE.V_GOVERNANCE_SCORE_CASE'',
    sha2(to_varchar(:v_payload), 256),
    :v_payload,
    :v_now
  );

  return object_construct(
    ''ok'', true,
    ''snapshotId'', v_snapshot_id,
    ''caseId'', v_case_id,
    ''approvedAt'', v_now,
    ''tier'', v_tier,
    ''band'', v_band,
    ''finalScore'', v_final_score
  );
end;
';
CREATE OR REPLACE PROCEDURE "SP_SCORE_CASE_V1"("P_CASE_ID" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  v_snapshot_id STRING;
BEGIN
  v_snapshot_id := CONCAT(
    ''SNP-'',
    TO_VARCHAR(CURRENT_TIMESTAMP(), ''YYYYMMDDHH24MISSFF3''),
    ''-'',
    UUID_STRING()
  );

  INSERT INTO GAFAIG_DB.CORE.CASE_SCORE_SNAPSHOTS_V2
    (SNAPSHOT_ID, CASE_ID, SCORING_MODEL_VERSION, SNAPSHOT_AT, TIER)
  VALUES
    (:v_snapshot_id, :P_CASE_ID, ''v1.0'', CURRENT_TIMESTAMP(), ''Standard Assurance'');

  RETURN OBJECT_CONSTRUCT(
    ''ok'', true,
    ''snapshotId'', v_snapshot_id,
    ''caseId'', P_CASE_ID,
    ''modelVersion'', ''v1.0''
  );
END;
';
CREATE OR REPLACE PROCEDURE "SP_UPSERT_EVIDENCE_SUMMARY"("P_EVIDENCE_ID" VARCHAR, "P_SUMMARY" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ORG STRING;
  V_OK INTEGER;
BEGIN
  LET V_ORG := CORE.CURRENT_ORG_ID();

  IF (V_ORG IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''No ORG mapping for user'', ''user'', CURRENT_USER());
  END IF;

  SELECT COUNT(*) INTO :V_OK
  FROM CORE.VERIFICATION_EVIDENCE
  WHERE EVIDENCE_ID = P_EVIDENCE_ID
    AND ORG_ID = V_ORG;

  IF (V_OK = 0) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''Evidence not found in org'', ''evidenceId'', P_EVIDENCE_ID, ''orgId'', V_ORG);
  END IF;

  MERGE INTO CORE.EVIDENCE_SUMMARIES t
  USING (SELECT P_EVIDENCE_ID AS EVIDENCE_ID, V_ORG AS ORG_ID, P_SUMMARY AS SUMMARY) s
  ON t.EVIDENCE_ID = s.EVIDENCE_ID AND t.ORG_ID = s.ORG_ID
  WHEN MATCHED THEN UPDATE SET SUMMARY = s.SUMMARY, UPDATED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (EVIDENCE_ID, ORG_ID, SUMMARY, CREATED_AT)
    VALUES (s.EVIDENCE_ID, s.ORG_ID, s.SUMMARY, CURRENT_TIMESTAMP());

  RETURN OBJECT_CONSTRUCT(''ok'', TRUE, ''evidenceId'', P_EVIDENCE_ID, ''orgId'', V_ORG);
END;
';
CREATE OR REPLACE PROCEDURE "UNAPPROVE_CASE_V1"("P_CASE_ID" VARCHAR, "P_ACTOR" VARCHAR, "P_NOTES" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ACTOR STRING;
  V_NOTES STRING;
  V_EXISTS NUMBER;
BEGIN
  V_ACTOR := COALESCE(P_ACTOR, CURRENT_USER());
  V_NOTES := COALESCE(P_NOTES, ''Unpublish'');

  SELECT COUNT(*)
    INTO :V_EXISTS
  FROM CORE.VERIFICATION_CASES
  WHERE CASE_ID = :P_CASE_ID;

  IF (:V_EXISTS = 0) THEN
    RETURN OBJECT_CONSTRUCT(
      ''ok'', FALSE,
      ''error'', ''Case not found'',
      ''caseId'', P_CASE_ID
    );
  END IF;

  UPDATE CORE.VERIFICATION_CASES
     SET STATUS = ''submitted''
   WHERE CASE_ID = :P_CASE_ID;

  -- IMPORTANT: use INSERT...SELECT (avoids UUID_STRING() in VALUES issues)
  INSERT INTO CORE.CASE_APPROVAL_LOG (LOG_ID, CASE_ID, ACTION, ACTOR, ACTION_AT, NOTES)
  SELECT
    UUID_STRING(),
    :P_CASE_ID,
    ''UNAPPROVE'',
    :V_ACTOR,
    CURRENT_TIMESTAMP(),
    :V_NOTES;

  RETURN OBJECT_CONSTRUCT(
    ''ok'', TRUE,
    ''caseId'', P_CASE_ID,
    ''actor'', V_ACTOR,
    ''notes'', V_NOTES
  );
END;
';
create or replace row access policy RAP_CASES_BY_ORG as (ORG_ID VARCHAR) 
returns BOOLEAN ->
(
    -- Regulators see everything
    IS_ROLE_IN_SESSION('GAFAIG_REGULATOR_ROLE')

    OR

    -- App user only sees mapped orgs
    EXISTS (
        SELECT 1
        FROM USER_ORG_ACCESS ua
        WHERE ua.USERNAME = CURRENT_USER()
          AND ua.ORG_ID = ORG_ID
    )
)
;
create or replace schema CORE_API;

CREATE OR REPLACE PROCEDURE "SP_CREATE_CASE"("P_CASE_ID" VARCHAR, "P_PARTICIPANT_ID" VARCHAR, "P_STATUS" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ORG STRING;
BEGIN
  SELECT ORG_ID INTO :V_ORG
  FROM GAFAIG_DB.CORE.USER_ORG_ACCESS
  WHERE USERNAME = CURRENT_USER()
  QUALIFY ROW_NUMBER() OVER (ORDER BY ORG_ID) = 1;

  IF (V_ORG IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''ok'', FALSE, ''error'', ''No ORG mapping for user'', ''user'', CURRENT_USER());
  END IF;

  INSERT INTO GAFAIG_DB.CORE.VERIFICATION_CASES (CASE_ID, PARTICIPANT_ID, ORG_ID, STATUS)
  VALUES (P_CASE_ID, P_PARTICIPANT_ID, V_ORG, P_STATUS);

  RETURN OBJECT_CONSTRUCT(''ok'', TRUE, ''caseId'', P_CASE_ID, ''orgId'', V_ORG);
END;
';
create or replace schema GOVERNANCE;

create or replace schema PUBLIC;
